DFE-Digital/get-into-teaching-api

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/CandidateAccessTokenRequest.cs, GetIntoTeachingApi/Models/CandidateIdentification.cs, GetIntoTeachingApi/Models/Validators/CandidateAccessTokenRequestValidator.cs, GetIntoTeachingApi/Models/Validators/CandidateIdentificationValidator.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Models/CandidateAccessTokenRequestTests.cs, GetIntoTeachingApiTests/Models/CandidateIdentification.cs, GetIntoTeachingApiTests/Models/Validators/CandidateAccessTokenRequestValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateIdentificationValidatorTests.cs, README.md
Stubs out the controller actions we will need for the Get into Teaching website (TTA registration, events and mailing list). The request models have been created where possible, but in places that will hook into the generated OData entities for Dynamics I've left the models as `Object`.
Model validation uses [FluentValidation](https://fluentvalidation.net/) and I've also added [FluentAssertions](https://fluentassertions.com/) and [Moq](https://github.com/Moq/moq4/wiki/Quickstart) for testing.
Started migrating the Swagger documentation into the source code using [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) (which can [integrate nicely with FluentValidation](https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation)) - when this has been fully …
=> Stub GiT controller actions, request models/validation

GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/CandidateAccessTokenChallenge.cs, GetIntoTeachingApi/Services/CandidateAccessTokenService.cs, GetIntoTeachingApi/Services/ICandidateAccessTokenService.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Models/CandidateAccessTokenChallengeTests.cs, GetIntoTeachingApiTests/Services/CandidateAccessTokenServiceTests.cs
Adds a `CandidateAccessTokenService` class that is able to generate Timed One Time Password (TOTP) codes. These can then be emailed out and later verified (the verification also checks a shared secret that should be sent from the client consuming the API). 
Currently, the TOTPs are configured with a 30 second 'step', which means a new code will be generated every 30 seconds and they have a window size of 2, meaning the user will have 1 minute (plus the time left in the current 'step') in order to send the code back in a candidate request. We can change this later on if we want to allow longer (by adjusting the windows size - the step size should remain as per the RFC).
We configure the TOTP secret to be a compound value of candidate email address and shared secret; this results in …
=> Add Timed One Time Password (TOTP) for candidate access tokens

GetIntoTeachingApi/Auth/SharedSecretHandler.cs, GetIntoTeachingApi/Auth/SharedSecretRequirement.cs, GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/OperationFilters/AuthResponsesOperationFilter.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Auth/SharedSecretHandlerTests.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Utils/PolicyTestHelpers.cs
We want to ensure that requests to the API originate from our server(s) - to enforce this we are going to have clients send an `Authorization: Bearer <shared_secret>` header. This PR adds a policy handler and requirement for the presence of the header, matching it to the APIs shared secret value. The policy is applied to all controllers and the Swagger docs have been updated to detail the authorization mechanism.
=> Protect endpoints with auth policy

GetIntoTeachingApi/Adapters/INotificationClientAdapter.cs, GetIntoTeachingApi/Adapters/NotificationClientAdapter.cs, GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Services/INotifyService.cs, GetIntoTeachingApi/Services/NotifyService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Services/NotifyServiceTests.cs, GetIntoTeachingApiTests/Utils/LoggerTestHelpers.cs, README.md
Includes the GOV.UK Notify C# client and wraps it in an adapter so that its mockable in unit tests. This is utilised by a basic `NotifyService` in order to send emails using a given `templateId` and `personalisation` (template attributes).
The `CandidatesController` has been updated to generate and email out a PIN code to a candidate for a valid `CandidateAccessTokenRequest`. There is a `// TODO:` in the action which will later be the call out to the CRM to find a matching candidate (so we only send a PIN code if there is a matching candidate in the CRM).
=> Send PIN code email via GOV.UK Notify service

GetIntoTeachingApi/Adapters/IOrganizationServiceContextAdapter.cs, GetIntoTeachingApi/Adapters/NotificationClientAdapter.cs, GetIntoTeachingApi/Adapters/OrganizationServiceContextAdapter.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/TypeEntity.cs, GetIntoTeachingApi/Profiles/TypeEntityProfile.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Models/TypeEntityTests.cs, GetIntoTeachingApiTests/Profiles/ProfileTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, README.md
Add an `TypeEntity` model so that we can model generic 'types' (e.g. Country, Teaching Subject) (`Type` is a keyword, hence `TypeEntity`).
Add a service that encapsulates the interactions with the Dynamics365 instance. Currently it supports getting countries and teaching subjects, however it will be extended to write back to Dynamics as well.
Use the `CdsServiceClient` SDK which is currently in ALPHA. We may swap over to .NET Framework in the future so that we can use the stable `CrmServiceClient` instead.
Wrap the `IOrganizationServiceContext` in an adapter so that we can mock it in unit tests and execute the LINQ queries against an in-memory `IQueryable`.
AutoMapper is used to translate between `Entity` objects returned from the SDK and our models (in this case the `TypeEntity` model.
=> Add CrmService to encapsulate interactions with Dynamics365

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidateAccessTokenRequest.cs, GetIntoTeachingApi/Profiles/CandidateProfile.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Models/CandidateAccessTokenRequestTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Profiles/CandidateProfileTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Utils/MapperHelpers.cs
We need to be able to retrieve a candidate from the CRM by email address so that we can match it to an incoming `CandidateAccessTokenRequest`.
Add basic `Candidate` model with minimal attributes (to be fleshed out in a later PR where we return the `Candidate` from our API).
Add profile to map from Dynamics `Entity` to our `Candidate` model.
When a request for an existing candidate arrives we compare email address as well as first, last name and date of birth with what we have stored in the CRM. If the email matches in addition to 2/3 of the additional attributes then we go ahead and email a pin code to the candidate email address (they can then exchange this for the existing candidate details).
=> Match CandidateAccessTokenRequest with existing candidate

GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs, GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Models/TypeEntity.cs, GetIntoTeachingApi/Profiles/TypeEntityProfile.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Profiles/TypeEntityProfileTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
The `contact` entity in Dynamics has a number of attributes that have a preset list of possible values. These are stored in 'pick list item' objects in Dynamics. This PR exposes these items under the `/types` endpoint so that the client can query possible values.
The `CdsServiceClient` also caches all of the Dynamics metadata, which contains both these pick list items and the lookup objects (countries/teachings subjects). Whilst there's no control over how the cache works, they do provide a mechanism to clear the cache - so if we find it becomes out of date too often we will be able to manually clear it periodically.
Updates the `CrmService` to use a couple of generic methods for retrieving pick list items and lookups; the side effect of this is that the Dynamics domain now leaks out of …
=> Add endpoints for pick list options

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Models/ExistingCandidateRequest.cs, GetIntoTeachingApi/Models/Validators/ExistingCandidateRequestValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Models/ExistingCandidateRequestTests.cs, GetIntoTeachingApiTests/Models/Validators/ExistingCandidateRequestValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Candidate matching is currently performed in the controller, however we are going to be matching requests to existing candidates in other places so it makes sense to perform that operation within the `CrmService` so it can be reused.
This PR updates the logic so we try and match up to 20 candidates by email, returning the first/latest candidate that matches the additional attributes successfully.
=> Perform candidate matching in CrmService

GetIntoTeachingApi/Models/Validators/AddressValidator.cs, GetIntoTeachingApi/Models/Validators/CandidatePastTeachingPositionValidator.cs, GetIntoTeachingApi/Models/Validators/CandidateQualificationValidator.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/ExistingCandidateRequestValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Models/Validators/AddressValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidatePastTeachingPositionValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateQualificationValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/ExistingCandidateRequestValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Add validators for the `Candidate` model and all associated models.
When a model attribute links to a preset list of Dynamics `Entity` objects we call out to the CRM to ensure that the `Id` of the association matches a record. The `CdsServiceClient` will maintain a cache of the Dynamics metadata, meaning these calls should almost always be satisfied in-memory.
Add additional method to `CrmService` to get recent privacy policies; we validate that the user is accepting one of the 3 most recent privacy policies to account for the CRM potentially being down and a policy update happening in quick succession (while our jobs to register a new candidate are queued). We may want to make this 2 going forward; I've raised it as a question.
=> Add candidate validation

GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs, GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApi/Models/Validators/CandidatePastTeachingPositionValidator.cs, GetIntoTeachingApi/Models/Validators/CandidatePrivacyPolicyValidator.cs, GetIntoTeachingApi/Models/Validators/CandidateQualificationValidator.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/PhoneCallValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Auth/SharedSecretHandlerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Models/CandidatePastTeachingPositionTests.cs, GetIntoTeachingApiTests/Models/CandidatePrivacyPolicyTests.cs, GetIntoTeachingApiTests/Models/CandidateQualificationTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/PhoneCallTests.cs, GetIntoTeachingApiTests/Models/PrivacyPolicyTests.cs, GetIntoTeachingApiTests/Models/TypeEntityTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidatePrivacyPolicyValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/PhoneCallValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
The general process for upserting an model to the CRM is:
- Create a blank `Entity` in an OrganizationalServiceContext (set `Id` if updating)
- Get the model to populate the fields of the `Entity`
- Configure any relationships between the entities being upserted
- Save the context (upserting in a single transaction)
`IOrganizationServiceAdapter` is used to abstract the interactions with the context so that we can mock out the process in unit tests.
`204` is returned from the controller action to update a candidate as the operation will end up in a background job.
`PhoneCall`/`CandidatePrivacyPolicy` have been pulled out into their own models for consistency.
A privacy policy is only accepted again if it hasn't already been accepted by the candidate previously.
=> Upsert candidate details to CRM

GetIntoTeachingApi/Services/CrmCache.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmCache.cs, GetIntoTeachingApi/Services/NotifyService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs, GetIntoTeachingApiTests/Services/CrmCacheTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/NotifyServiceTests.cs
The in-memory cache will store responses from the CRM that are used in validation logic, so that we can still accept requests from a client when the CRM is offline. This covers:
- Lookup items
- PickList items
- Privacy policy entities
The cache will be refreshed every 3 hours, however if the CRM is offline when a refresh is attempted the stale data will remain available in the cache so that the API can continue to function.
As this cache is in-memory, if the API server restarts when the CRM is offline it will not be able to function until the CRM comes back online. We expect the chance of this happening to be slim and will monitor our logs to see if it is worth the effort of implementing a persistent cache.
=> Add in-memory cache for CrmService

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
- Add endpoint to retrieve teaching event types
- Add initial `TeachingEvent` model
- Add `UpcomingTeachingEvents` to `CrmService`
- Plumb in upcoming teaching events endpoint to `CrmService`
All events are currently loaded into the in-memory cache, however it is TBC if events need to be available whilst the CRM is offline.
=> Add upcoming events endpoint

GetIntoTeachingApiTests/Services/CrmCacheTests.cs
We are testing that a functional parameter throws an exception; the function requires a string return type but it will never be reached as we always throw the exception. This commit suppresses the build warning about unreachable code.
=> Suppress unreachable code warning

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/TeachingEventRegistrationTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Add a new `TeachingEventRegistration` model that maps a candidate to an event.
Add a method to the CRM to check if a candidate is already registered for an event.
Update `BaseModel` with hook to prevent an entity being mapped - implement the hook in `TeachingEventRegistration` to ensure candidates are not re-registered for the same event again.
Plumb in `TeachingEventsController` create action to lookup the attendee and event then save the `EventRegistration`.
=> Add ability to register attendee for events

GetIntoTeachingApi/Adapters/IPerformContextAdapter.cs, GetIntoTeachingApi/Adapters/PerformContextAdapter.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Jobs/BaseJob.cs, GetIntoTeachingApi/Jobs/CandidateRegistrationJob.cs, GetIntoTeachingApi/Jobs/JobConfiguration.cs, GetIntoTeachingApi/Jobs/TeachingEventRegistrationJob.cs, GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApi/Services/NotifyService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Jobs/CandidateRegistrationJobTests.cs, GetIntoTeachingApiTests/Jobs/TeachingEventRegistrationJobTests.cs, README.md
We currently send data to dynamics within the request/response cycle. This is fine if Dynamics is online, however it can be offline for maintenance for reasonably long periods of time. To ensure the transactions complete this commit adds Hangfire to queue the transaction requests and retry them in the event of failure.
The jobs will be retried once per hour, a maximum of 24 times. If the job is not successful it will be removed from storage and we will attempt to email the candidate informing them that the transaction has failed.
Hangfire is configured to use in-memory storage for development (and also runs a shorter retry/give up cycle). In production we are using PostgreSQL as this is supported by the free version of Hangfire (Redis requires a Hangfire susbcription).
The entire …
=> Move transactions to background jobs

GetIntoTeachingApi/Auth/HangfireDashboardAuthorizationFilter.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Auth/HangfireDashboardAuthorizationFilterTests.cs
The Hangfire dashboard gives visibility of the jobs and their states; it will be useful to have it available in staging as well as development (which is the default).
Add custom authorization filter to check the running environment and expose the dashboard on staging/development.
=> Expose Hangfire dashboard on dev/staging

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Jobs/TeachingEventRegistrationJob.cs, GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Jobs/TeachingEventRegistrationJobTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Previously we only checked for existing candidates when registering a candidate for an event. Instead, we attempt to get the matching, existing candidate if they exist and if not then a new candidate entry
is created and registered with the event.
If the registration job fails after creating a candidate then on the next run the candidate will be matched, so we won't end up creating a bunch of duplicate candidates in the event of job failures.
=> Enable new candidates to register for events

README.md
We migrated from connection string to reading in the VCAP_SERVICES environment variables containing postgres credentials.
=> Update README with correct db instructions

GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApi/Models/TeachingEventBuilding.cs, GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs
As part of mapping Dynamics entities to our models we need to dynamically instantiate BaseModel subtypes using reflection; if a subtype doesn't have the constructor we expect a runtime error will
occur. As it's used with reflection we don't get a compile time error if the constructor is missing, so this commit introduces a test that will ensure the constructor is present.
=> Ensure BaseModel subtypes have required constructor

GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApiTests/Database/DbConfigurationTests.cs, README.md
The database instance names are unique per environment, so we are reading them in from env variables instead of hardcoding them.
=> Read postgres instance names from ENV variables

GetIntoTeachingApi/Database/DbConfiguration.cs
Add temporary logging to the DbConfiguration so we can see what's going wrong in production. Will be reverted once we have investigated.
=> Add temporary logging to DbConfiguration

GetIntoTeachingApi/Models/TeachingEventBuilding.cs
The Point type is a complex object so it's best not to serialize it; it also clutters the Swagger documentation.
=> JsonIgnore teaching event building coordinate

GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/PhoneCallValidator.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/PhoneCallTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/PhoneCallValidatorTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Send the channel through to the CRM with the Candidate and PhoneCall models.
Update telephone attribute to point to `address1_telephone1` as instructed by CRM team.
=> Add additional fields to Candidate model

GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
The entities and associated metadata in the CRM may be removed as well as added/updated; the sync operation needs to account for this by removing any models that are cached in the database but are no longer returned from the CRM.
=> Delete orphaned models during sync

GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Database/GetIntoTeachingDbContext.cs, GetIntoTeachingApi/Migrations/20200606193812_InitialCreate.Designer.cs, GetIntoTeachingApi/Migrations/20200606193812_InitialCreate.cs, GetIntoTeachingApi/Migrations/GetIntoTeachingDbContextModelSnapshot.cs, GetIntoTeachingApi/Models/Location.cs, GetIntoTeachingApi/Models/TeachingEventBuilding.cs
The migrations were mixing SQLite (used for dev/test) and Postgres configuration options. This PR separates them depending on the active provider and re-generates the migrations from scratch.
Enables the Postgis extension that is needed for running the spatial queries in Postgres.
Re-instates the geography column type; I had removed this in a previous PR believing it to be unsupported by Postgres, but it is actually compatible.
=> Fix postgres in production

GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Database/GetIntoTeachingDbContextFactory.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Helpers/DatabaseTests.cs, README.md
The SQLite provider was being ran at design-time by default, causing the migrations to not work in production. This PR adds a DbContext factory that will be used at design-time to load the Postgres provider, avoiding any future issues.
=> Ensure Postgres provider is ran at design-time

GetIntoTeachingApi/Startup.cs
This is currently taking longer than the 30 minute Hangfire job timeout so it will never succeed. Disabling while it gets refactored into multiple, smaller jobs.
=> Disable location sync job

GetIntoTeachingApi/Jobs/LocationBatchJob.cs, GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Jobs/LocationBatchJobTests.cs, GetIntoTeachingApiTests/Jobs/LocationSyncJobTests.cs
Currently all 1.7 million postcodes are inserted into our database in a single job; this takes longer than 30 minutes, which is the Hangfire job timeout and as a result the job never finishes. This PR splits this job into multiple, smaller jobs where each worker inserts 100 postcodes into the database (this results in around 17,000 individual jobs running with some parallelisation - testing this locally it takes 2-3 minutes to do a full sync of all postcodes).
The 100 postcodes with geolocation data are serialised with the job at the moment; it may be better to store that data elsewhere in the future and just pass a reference to the postcodes to the job.
=> Split location sync into multiple jobs

GetIntoTeachingApi/Services/Store.cs
Previously I updated the sync methods to run in parallel for better performance, however this introduced an issue as the DbContext is shared across each method in the `Store` (multiple threads accessing the same context is not supported).
Change back to running the sync operations in series; it only takes about 10 seconds to do a full sync so performance isn't an issue.
=> Run sync operations in series

GetIntoTeachingApi/Auth/SharedSecretHandler.cs, GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Jobs/BaseJob.cs, GetIntoTeachingApi/Jobs/CandidateRegistrationJob.cs, GetIntoTeachingApi/Jobs/CrmSyncJob.cs, GetIntoTeachingApi/Jobs/LocationBatchJob.cs, GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApi/Jobs/TeachingEventRegistrationJob.cs, GetIntoTeachingApi/Services/NotifyService.cs, GetIntoTeachingApiTests/Auth/SharedSecretHandlerTests.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Helpers/LoggerTestHelpers.cs, GetIntoTeachingApiTests/Jobs/CandidateRegistrationJobTests.cs, GetIntoTeachingApiTests/Jobs/CrmSyncJobTests.cs, GetIntoTeachingApiTests/Jobs/LocationBatchJobTests.cs, GetIntoTeachingApiTests/Jobs/LocationSyncJobTests.cs, GetIntoTeachingApiTests/Jobs/TeachingEventRegistrationJobTests.cs, GetIntoTeachingApiTests/Services/NotifyServiceTests.cs
- Remove `ILogger` from controllers 
The controllers are very thin so there's no need to log anything; any bad request/validation errors etc will be findable by the route and HTTP status codes.
- Log warnings for authentication failures
- Log delayed job events
- Log when sending emails via GOV.UK Notify service
=> Improve logging throughout API

GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Database/GetIntoTeachingDbContextFactory.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Jobs/BaseJob.cs, GetIntoTeachingApi/Jobs/CandidateRegistrationJob.cs, GetIntoTeachingApi/Jobs/CrmSyncJob.cs, GetIntoTeachingApi/Jobs/JobConfiguration.cs, GetIntoTeachingApi/Jobs/LocationBatchJob.cs, GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApi/Jobs/TeachingEventRegistrationJob.cs, GetIntoTeachingApi/Services/HangfirePrometheusExporter.cs, GetIntoTeachingApi/Services/IHangfirePrometheusExporter.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/Extensions.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Database/DbConfigurationTests.cs, GetIntoTeachingApiTests/Jobs/CandidateRegistrationJobTests.cs, GetIntoTeachingApiTests/Jobs/CrmSyncJobTests.cs, GetIntoTeachingApiTests/Jobs/JobConfigurationTests.cs, GetIntoTeachingApiTests/Jobs/LocationBatchJobTests.cs, GetIntoTeachingApiTests/Jobs/LocationSyncJobTests.cs, GetIntoTeachingApiTests/Jobs/TeachingEventRegistrationJobTests.cs, GetIntoTeachingApiTests/Services/HangfirePrometheusExporterTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs, README.md
- Add prometheus-net package
Add the prometheus-net package for collecting and exposing metrics to Prometheus on the `/metrics` endpoint. Gathers .NET Core HTTP request metrics by default.
- Track job duration for CRM and location sync operations
- Expose Hangfire job status to Prometheus on a single instance
Each application instance runs a number of Hangfire workers against the same shared job storage. If we expose the Hangfire statistics to Prometheus for scraping on each instance it will aggregate the results, which would be incorrect. This PR uses the `CF_INSTANCE_INDEX` environment variable to ensure only one instance is exposing the Hangfire job stats.
- Clean up use of `Env` throughout
=> Collect metrics and expose to Prometheus

GetIntoTeachingApi/Startup.cs
The Postgres connection limit (100) is being hit in the test environment shortly after Hangfire starts up. By default the number of workers is a multiple of the number of cores the instance has - we don't know what this is, but assuming 20 cores it would result in `20 * 5 = 100` connections being created and the limit being hit. This PR fixes the number of workers to 10, which should be sufficient for the application.
=> Set fixed number of Hangfire workers

GetIntoTeachingApi/Database/DbConfiguration.cs
Our Postgres instance is configured to accept 100 connections; each application instance is configured to pool up to 100 connections as well, which means we could exhaust the Postgres instance. This PR reduces the pooling to a max of 50 connections.
=> Reduce max pool size to 50

GetIntoTeachingApi/Startup.cs
We had lowered this to debug a connection leak issue in test; switching the Postgres provider for Hangfire appears to have fixed the leak, so we can increase the workers without exhausting the pool.
=> Increase worker count to 20

GetIntoTeachingApi/Startup.cs
There is less support in code generation tools for Swagger v3 with respect to Ruby clients; outputting it as v2 may mean that we can generate a client for the adviser service app.
=> Output Swagger using v2

GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/ExistingCandidateRequestValidator.cs
Validate the email contains an `@` that is not at the start or the end; makes it consistent with Dynamics validation and removes the complex regex that is breaking the auto-generated Ruby client.
=> Simplify email validation

GetIntoTeachingApi/Controllers/CallbackBookingQuotasController.cs, GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Models/CallbackBookingQuota.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/CallbackBookingQuotasControllerTests.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs, GetIntoTeachingApiTests/Models/CallbackBookingQuotaTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Retrieve the callback booking quotas from Dynamics. Returns the booking quotas for the next 14 days, in alignment with the existing TTA process (matches the Azure function the CRM team provided). They also allow filtering to a specific number of weekdays, but I'm not sure if this is a requirement of the new process so I've left that out for now.
```
GET api/callback_booking_quotas
[{
"timeSlot": "9am - 9:30am",
"day": "Friday 19 June",
"startAt": "2020-06-19T08:00:00Z",
"endAt": "2020-06-19T08:30:00Z",
"numberOfBookings": 0,
"quota": 12,
"isAvailable": true,
"id": "6325803b-1c83-ea11-a811-000d3a44a94a"
}]
```
=> Add endpoint to retrieve callback booking quotas

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Jobs/TeachingEventRegistrationJob.cs, GetIntoTeachingApi/Models/ExistingCandidateRequest.cs, GetIntoTeachingApi/Models/TeachingEventRegistrationRequest.cs, GetIntoTeachingApi/Models/Validators/TeachingEventRegistrationRequestValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Jobs/TeachingEventRegistrationJobTests.cs, GetIntoTeachingApiTests/Models/TeachingEventRegistrationRequestTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventRegistrationRequestValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Instead of matching the candidate automatically on event registration we want to manually make the user verify their email address first. The event registration endpoint now accepts a `candidateId` that can be used to add an existing candidate to an event (the id should be obtained from a matchback request and only used once a user has verified the email).
Also adds additional fields to the candidate entity to match the updated event registration process.
=> Update event registration to use manual matchback

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Jobs/MailingListAddMemberJob.cs, GetIntoTeachingApi/Models/MailingListAddMemberRequest.cs, GetIntoTeachingApi/Models/Validators/MailingListAddMemberRequestValidator.cs, GetIntoTeachingApi/Services/NotifyService.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Jobs/MailingListAddMemberJobTests.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberRequestTests.cs, GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberRequestValidatorTests.cs
Add a basic mailing list job to insert a candidate record or update an existing record with the latest field values from the mailing list form. The CRM does not yet contain the schema for subscribing to a mailing list, so this will need to be added in as soon as it's available (in addition to a few other candidate fields we will collect but don't yet have a schema for).
=> Flesh out mailing list endpoint

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
- Rename GetCandidate to MatchCandidate
There is another `GetCandidate` method on the `ICrmService` that accepts a candidate ID; renaming this method to avoid confusion -- this is the method that should be used to 'matchback' an existing candidate.
- Ignore candidates with inactive statecode
According to the CRM team any 'merged' contact records will be set as inactive, so we don't need to explicitly check for the master record.
- Prioritise master records over merged children
Master records have a `merged` attribute of `false`; these should be prioritised over child records (that have been merged into a master record).
=> Ignore inactive contacts and prioritise master records

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
When matching an existing candidate to contacts in the CRM we have been advised that the ideal process is:
- Find all contacts matching the email address
- Exclude those that are inactive
- Order by dfe_duplicatescorecalculated (highest number first)
- Order by modifiedon (latest modified first)
=> Determine master record based on dfe_duplicatescorecalculated field

.github/workflows/sonarcloud.yml
Omits files that cannot be unit tested from coverage reports:
- Migrations
- Adapters (abstracting untestable dependencies)
- Database Factory (used for migrations only)
- Startup.cs
- Program.cs
=> Exclude un-testable files from coverage reports

GetIntoTeachingApi/Models/MappingInfo.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Integration/OperationsControllerIntegrationTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
We will be end-to-end testing separately to ensure the integration with Dynamics is functioning correctly, however we won't run these tests as often as the unit/integration tests. This PR adds a basic integration test that will test the full request/response stack.
=> Add basic integration test

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/PrivacyPolicy.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Models/CandidatePrivacyPolicyTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
- Encapsulate enums in appropriate model
Enum types are currently in the `CrmService` - this was to keep the models unaware of the CRM, however the models are now coupled to the CRM anyway (since the mappings are now data attributes) so it makes more sense for the enum types
to be in the models as well.
- Add additional fields to CandidatePrivacyPolicy
Update the `CandidatePrivacyPolicy` model to include additional, hidden attributes that are required by the CRM.
- Generate v3 OpenAPI docs in development
The UI created by Swashbuckle for V2 Swagger docs is buggy (if you paste in JSON as a request body it doesn't always let you submit the form, but it doesn't give you an error either). This commit updates the Swashbuckle config to generate the more reliable V3 UI when in development, but …
=> Candidate privacy policy schema changes

GetIntoTeachingApi/Attributes/CrmETagAttribute.cs, GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Jobs/JobConfiguration.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Attributes/CrmETagAttributeTests.cs, GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs
Content is currently synced from the CRM on a weekly basis; any requests made should be cachable up until the moment a new sync has been performed. To achieve this, the PR generates an `ETag` based on the next CRM sync job execution date (which changes after a successful sync) along with the request path. When an `If-Not-Modified` header is sent containing the current `ETag` we immediately respond with a 304 (not modified) header, avoiding the overhead of calling the action and querying the data. If an incorrect/outdated `ETag` is present (or no `If-Not-Modified` header is provided) then the request completes as normal and returns an `ETag`.
Another way to do this would be to compute the `ETag` from the response body, but this has the overhead of actually having to fulfil the response …
=> Support HTTP ETag/If-Not-Modified headers for CRM content

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApi/Models/Validators/CandidateQualificationValidator.cs, GetIntoTeachingApi/Models/Validators/PhoneCallValidator.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/PhoneCallTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateQualificationValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/PhoneCallValidatorTests.cs
Certain fields of the `PhoneCall` model are populated using the data already collected in the `Candidate` model. This commit hooks into the mapping process to set the values on the `PhoneCall` before mapping it to an `Entity`.
Add a number of hidden fields with default values that the CRM expects.
=> Update PhoneCall to reflect schema changes

GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Jobs/CandidateRegistrationJob.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/ServiceSubscription.cs, GetIntoTeachingApi/Models/Validators/ServiceSubscriptionValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Jobs/CandidateRegistrationJobTests.cs, GetIntoTeachingApiTests/Models/ServiceSubscriptionTests.cs, GetIntoTeachingApiTests/Models/Validators/ServiceSubscriptionValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
- Add ServiceSubscription model
- Subscribe candidate on sign up for TTA
Subscribe the candidate to the TTA subscription as part of the background job. If a candidate has already subscribed a duplicate subscription will not be created.
Return the subscriptions associated with a candidate as part of the request to exchange an access token for an existing candidate.
=> Add ServiceSubscription and subscribe on TTA sign up

GetIntoTeachingApi/Models/MailingListAddMemberRequest.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberRequestTests.cs
If the `UkDegreeGradeId` is prefilled from an existing qualification, then the `QualificationId` should be sent in the request to add a member to the mailing list in order to update the existing qualification details with whatever the user selects as part of the form submission.
=> Accept QualificationId on MailingListAddMemberRequest

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Models/Validators/MailingListAddMemberValidator.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpRequestValidator.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApi/Models/Validators/TeachingEventAddAttendeeValidator.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberRequestTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpRequestValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventAddAttendeeValidatorTests.cs
- Add validator for TeachingAdviserSignUpRequest
Add basic validation to ensure underlying Candidate is valid - still needs fleshed out for more specific validation based on branches.
- Remove Request suffix from models
These models will be used for response models going forward as well, so it makes sense to drop the `Request` suffix from their name.
- Exchange pin code for TeacherTrainingAdviserSignUp
Instead of returning the base `Candidate` model, it makes more sense to return the request model for a TTA sign up already pre-filled so that the client does not have to map to/from the `Candidate` model and the logic around which qualification/past teaching position to use can be encapsulated in the API.
- Exchange pin code for MailingListAddMember
Add new endpoint to exchange PIN code for …
=> Individual endpoints to exchange PIN code for candidate information

GetIntoTeachingApi/Models/Validators/TeachingEventSearchRequestValidator.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventSearchRequestValidatorTests.cs
It is possible to do a national search in the front-end, so this PR updates the API to support searching without a postcode. If a radius is provided then a postcode must be specified.
=> Make Postcode optional unless Radius is provided

GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/PhoneCallTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
- Update telephone validation
We want to allow pretty much anything from the client as this will be international numbers.
- Determine PhoneCall DestinationId from Telephone
If the number starts with a `+` and is not `+44` then we mark it as international.
- Correct validation around degree type/subject
Pin down the validation around degree subject and type, which is non-intuitive. Essentially:
> Do you have a degree?
```
Yes - status = 222750000 (has degree), type = 222750000 (degree)
No - status = 222750004 (no degree),type = 222750000 (degree)
Studying - status = 222750001 (final)/222750002(second)/222750003(first) (depends on subsequent question), type = 222750000 (degree)
Equivalent - status = 222750000 (has degree), type = 222750005 (equivalent)
```
=> Updates for schema changes/validation corrections

GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
- Set eligibility status for TTA sign up
When signing up to the Teacher Training Service a candidate is eligible to talk to an adviser if:
They have a qualification of type degree.
They are returning to teaching.
- Prevent sign up if candidate does not have a degree
- Set Candidate TypeId based on returner status
=> Mark candidates with eligibility state

GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs
This flag is only required if a phone call is being created, which only happens as part of the teacher training adviser sign up.
=> Do not send EligibilityPassed on mailing list/event sign up

GetIntoTeachingApi/Startup.cs
The events data may change during the course of a day and the output could be that an event needs to be hidden/removed. Syncing hourly will ensure that changes to events populate through to the API/website in a timely fasion.
=> Run CRM sync hourly

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/Validators/CandidateQualificationValidator.cs, GetIntoTeachingApiTests/Models/CandidateQualificationTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateQualificationValidatorTests.cs, README.md
- Rename Subject to DegreeSubject for consistency
The property names of request models should be consistent with the `BaseModel` models that they map to, that way the error message keys can be reconciled back with the request model.
- Document validation error mapping in request models
An error may be present on the request model or a hidden `BaseModel` model that it maps to. The client needs to check for the inclusion of the request model field in any error keys when reconciling errors with particular fields. This commit documents the behaviour in the endpoints that use request models.
- Update README.md with request model validation notes
=> Document validation behaviour for request models

GetIntoTeachingApi/Fixtures/ukpostcodes.dev.csv, GetIntoTeachingApi/Models/TeachingEventSearchRequest.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Jobs/LocationSyncJobTests.cs, GetIntoTeachingApiTests/Models/TeachingEventSearchRequestTests.cs
Previously it was appearing in the Swagger documentation and apparently `JsonIgnore` doesn't work when `[FromQuery]` so instead of writing a custom schema filter to exclude it we can more easily exclude it by making it a method instead of a property.
=> Change RadiusInKm to method

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/MailingListAddMemberValidator.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
- Remove CallbackInformation from Candidate
We are no longer asking for this data when a candidate subscribes to the mailing list.
Combine GCSE maths/english into single field for TeacherTrainingAdviserSignUp
In the front-end we collect GCSE maths and english as a single field; to make mapping back to the API easier we are combining these fields in the API.
=> Update request models to reflect UI changes

GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs
In case the validators in the API mismatch those used in the client, we want to ensure the API has a more relaxed approach to the validation (to avoid a submission that the client thinks is valid returning an error from the API).
=> Relax postcode validation

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Currently we put the event id, which is a long Guid, into the URL in the front-end to be able to retrieve the specific event from the API when the page loads. We want more SEO friendly URLs, so we're changing the API to expose the readable id of the event (which is a CRM-created permalink) and then using this as the lookup in the `GetTeachingEvent` operation.
An example of the readable id: `439_-_Online_TTT_-_London-Summer_20203437949823`
=> Retrieve TeachingEvent by ReadableId instead of Id

GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
To ensure the values are displayed in a natural ordering to the user we can sort based on the CRM `id`.
=> Sort types by Id ascending

GetIntoTeachingApi/Auth/SharedSecretHandler.cs, GetIntoTeachingApiTests/Auth/SharedSecretHandlerTests.cs
The auth schema is called for all requests, regardless of if they require authentication. If a request does not contain an `Authorization` header we returned a failure result, which causes a log message to be written out (twice,
as we were logging it independently as well). This is not actually an issue for endpoints that do not require authentication - instead, we should be returning `AuthenticationResult.NoResult()`.
=> Return AuthenticateResult.NoResult() if no Authorization header present

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/Subscription.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Models/Validators/MailingListAddMemberValidator.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberValidatorTests.cs
- Update DegreeEquivalent id
This was changed in the latest schema updates in the CRM.
- Default GCSE values to NotAnswered
If a GCSE question was not asked (and therefore is `null` when passed from the client) we should default to the new `NotAnswered` option in the `OptionSet`.
- Make Postcode optional in MailingListAddMemberValidator
- Update TeacherTrainingAdviserSignUp subscriptions to match latest schema
The CRM schema has been changed so that we should be opting returning to teaching candidates out of bulk email/postal mail, postal mail and marketing material.
- Default DegreeTypeId to Degree for mailing list sign up
- Opt out of postal mail for mailing list sign up
- Update consent on event sign up
- Update subscription when registering for a teaching event
- Test subscription …
=> Latest schema changes

GetIntoTeachingApi/Adapters/GeocodeClientAdapter.cs, GetIntoTeachingApi/Adapters/IGeocodeClientAdapter.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/Location.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/TeachingEventSearchRequestValidator.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventSearchRequestValidatorTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs, README.md, terraform/paas/application.tf, terraform/paas/variables.tf
- Fallback to Google API for geocoding postcodes
We have a mostly-static database of postcode geolocations that we use when a candidate searches for events (and to geocode the postcode of the events themselves). This will contain almost all valid UK postcodes, however it is rarely updated (once every few months - we check for updates on a cron job weekly). In the event that a candidate uses a postcode we do not have locally, this commit updates the process to fallback to the Google APIs for geocoding the postcode (this will likely only happen for new housing developments, for example).
- Accept any valid postcode on event search
Previously we validated the postcode on event search by checking to ensure it's in our local database of locations (geocodable postcodes). As our local data set …
=> Google api postcode fallback

GetIntoTeachingApi/Services/CandidateAccessTokenService.cs, GetIntoTeachingApiTests/Services/CandidateAccessTokenServiceTests.cs
Currently the TOTP window is 30 seconds (+ the time remaining in the current 'step', which is a maximum of 30 seconds). It has been decided that this is too short and a window of 15 minutes is more suitable. This commit increases the window to 15 minutes (30 * 30 second 'steps').
The future window has been reduced from 1 to 0 as the server is both generating and consuming the TOTPs it should never be the case that a code is valid in a following step.
=> Increase TOTP window to 15 minutes

GetIntoTeachingApi/Adapters/GeocodeClientAdapter.cs, GetIntoTeachingApi/Attributes/CrmETagAttribute.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApiTests/Attributes/CrmETagAttributeTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs
We could probably work this out from the existing metrics that track all HTTP requests (inferring a cache hit as a `304` response) but the endpoints we cache are not completely obvious (i.e. not all `GET` requests), so this will make it easier.
=> Track cache hit/miss as a metric

GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/TeachingEventRegistrationTests.cs
According to the latest schema we should be passing `msevtmgt_iscanceled` and `msevtmgt_registrationnotificationseen` as `false` to new teaching event registrations. There is also two new fields `msevtmgt_publishingstate` and `msevtmgt_syncedwithprovider`, however after consulting with the CRM team we should be fine to leave these as the defaults (which are `No` and `Pending`).
=> Add additional properties to TeachingEventRegistration

GetIntoTeachingApi/Auth/SharedSecretHandler.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Auth/SharedSecretHandlerTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs, terraform/paas/application.tf, terraform/paas/variables.tf
In order to allow the penetration test team to connect to the API without exposing our `SHARED_SECRET` we are adding another valid secret that they can use.
This PR should be reverted once the penetration test is complete.
=> Add PEN_TEST_SHARED_SECRET

GetIntoTeachingApi/Attributes/CrmETagAttribute.cs, GetIntoTeachingApiTests/Attributes/CrmETagAttributeTests.cs
Having the ETag caching enabled in development can make it harder to debug issues; particularly around the store sync process - if the sync fails and you hit the endpoint expecting to get types and it then returns an empty response, that will potentially remain cached even if you fix the bug.
=> Disable ETag cache in development

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
The `teaching_events/search` endpoint was updated so that the postcode is optional, so you can effectively get the upcoming teaching events using that endpoint - making this dedicated endpoint redundant.
=> Remove teaching_events/upcoming endpoint

.github/workflows/sonarcloud.yml, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Migrations/20200810073833_UpdateEventSchema.Designer.cs, GetIntoTeachingApi/Migrations/20200810073833_UpdateEventSchema.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Models/TeachingEventBuilding.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Models/TeachingEventBuildingTests.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
- Update TeachingEvent/Building to match latest schema
- Exclude draft/past events from sync operation
We do not want to display events on the website if they are not in an open/closed status (so draft or other). Events that are in the past should also be excluded from displaying; we are checking the event end date to ensure it is in the future, but the criteria around this may change (it may transpire that we want to display events until the day after they end).
- Exclude migrations from Sonarcloud duplication check
---
The low test coverage is down to this PR mainly adding accessor methods, for which there is little point in testing -- they will be exercised by the integration tests when we get those in place.
=> Latest CRM event schema changes

GetIntoTeachingApi/Database/GetIntoTeachingDbContext.cs, GetIntoTeachingApi/Migrations/20200811151658_TeachingEventBuildingOnDeleteNullify.Designer.cs, GetIntoTeachingApi/Migrations/20200811151658_TeachingEventBuildingOnDeleteNullify.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Models/TeachingEventBuilding.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Currently when a building is deleted from the CRM the sync job fails as it tries to delete the building with the foreign key constraint in the `TeachingEvent` still present. This updates the cascade operation to nullify the foreign key when deleting a `TeachingEventBuilding`.
This should resolve the error:
> MessageText: update or delete on table "TeachingEventBuildings" violates foreign key constraint "FK_TeachingEvents_TeachingEventBuildings_BuildingId" on table "TeachingEvents"
Detail: Key (Id)=(02ae40ce-9b9d-e911-a95e-000d3ab6413d) is still referenced from table "TeachingEvents".
=> Set TeachingEventBuilding OnDelete to nullify foreign key

GetIntoTeachingApi/Jobs/StatusCheckJob.cs, GetIntoTeachingApi/Services/HangfireService.cs, GetIntoTeachingApiTests/Jobs/StatusCheckJobTests.cs, GetIntoTeachingApiTests/Services/HangfireServiceTests.cs
We are seeing a job failure every time the status check endpoint is hit because the `ILogger` that was called in the wider scope is not available. This PR moves the logger to be dependency injected into a new job class, which should resolve the issue.
> System.ArgumentNullException
Value cannot be null. (Parameter 'factory')
> System.ArgumentNullException: Value cannot be null. (Parameter 'factory')
at Microsoft.Extensions.Logging.Logger`1..ctor(ILoggerFactory factory)
at lambda_method(Closure , Object[] )
=> Fix status check job failure

GetIntoTeachingApi/Database/GetIntoTeachingDbContext.cs, GetIntoTeachingApi/Migrations/20200812092655_TeachingEventBuildingOnDeleteNullify.Designer.cs, GetIntoTeachingApi/Migrations/20200812092655_TeachingEventBuildingOnDeleteNullify.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Models/TeachingEventBuilding.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Currently when a building is deleted from the CRM the sync job fails as it tries to delete the building with the foreign key constraint in the TeachingEvent still present. This updates the cascade operation to nullify the foreign key when deleting a TeachingEventBuilding.
This should resolve the error:
> MessageText: update or delete on table "TeachingEventBuildings" violates foreign key constraint "FK_TeachingEvents_TeachingEventBuildings_BuildingId" on table "TeachingEvents"
Detail: Key (Id)=(02ae40ce-9b9d-e911-a95e-000d3ab6413d) is still referenced from table "TeachingEvents".
The issue with https://github.com/DFE-Digital/get-into-teaching-api/pull/199 was in using a `HasOne`/`WithOne` relationship, which enforces a unique foreign key - this should have been `HasOne`/`WithMany` as a …
=> Set TeachingEventBuilding OnDelete to nullify foreign key (take #2)

GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
As we weren't including the `Building` relationship explicitly it wasn't being returned in the response for requests to get a single teaching event.
=> Include building when returning TeachingEvent

terraform/statuscake/resources.tf, terraform/statuscake/test.env.tfvars
Status cake deployment added some tags to make it easier to find them in amongst all the other teams
The status cake deployment is manual and only for BETA at the moment. Merge will not effect the applications code base, but will allow the terraform to get into master.
=> StatusCake Tags added

GetIntoTeachingApi/GlobalSuppressions.cs
The auto-generated migrations are safe to exclude from StyleCop linting.
=> Supress StyleCop warning

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
If a Candidate already has a subscription of the same type that is active, then we shouldn't create another instance of the subscription. Previously, we were not taking into account the `statecode` of the Candidate's existing subscriptions and therefore a new Subscription was not being created when it should have been (if a user subscribed, opted-out and then re-subscribed).
=> Only de-duplicate on active subscriptions

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
On the Get into Teaching website we only want to display a subset of the events that are available in the CRM, namely:
- Application workshops
- Train to teach events
- Online events
- School or University events
- Early year events
- "other" types of events
=> Filter out inapplicable event types

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Models/Validators/TeachingEventRegistrationValidator.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventRegistrationValidatorTests.cs
- Add WebFeedId to TeachingEvent
- Only accept online registrations for applicable events
If an event does not have a `WebFeedId` it is not possible to register for this event via the GITIS CRM. This commit adds a relevant validation check to reject such payloads from the client apps.
=> Add WebFeedId to TeachingEvent and prevent sign ups if null

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
It has been decided that we do not want to show Early Year/Other event types in the Get into Teaching website, so this commit removes them.
Explicitly assert event types in the test to ensure accidentally removing an enum from `TeachingEvent` doesn't result in the events of that type from being excluded (the connection was not explicit previously).
=> Exclude early years/other event types

GetIntoTeachingApi/GlobalSuppressions.cs, GetIntoTeachingApi/Migrations/20200814063617_AddWebFeedIdToTeachingEvent.Designer.cs, GetIntoTeachingApi/Migrations/20200814063617_AddWebFeedIdToTeachingEvent.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Models/Validators/TeachingEventRegistrationValidator.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventRegistrationValidatorTests.cs
- Add WebFeedId to TeachingEvent
- Only accept online registrations for applicable events
If an event does not have a WebFeedId it is not possible to register for this event via the GITIS CRM. This commit adds a relevant validation check to reject such payloads from the client apps.
The original PR was rolled back as the migrations were missing.
=> Add WebFeedId to TeachingEvent and prevent sign ups if null (take #2)

GetIntoTeachingApi/Services/HangfireService.cs, GetIntoTeachingApiTests/Services/HangfireServiceTests.cs
Previously we were enqueuing a job that simply logged something out to ensure that Hangfire was operational. This caused noise in the job statistics and only checked half of the infrastructure - it ensured the database could be contacted but not that there were workers running.
Instead, this commit reads the list of active workers from the database and ensures that at least one of them is processing the expected queue.
=> Check Hangfire health without enqueuing a job

GetIntoTeachingApi/Migrations/20200814122533_RemoveExternalTitleFromTeachingEvent.Designer.cs, GetIntoTeachingApi/Migrations/20200814122533_RemoveExternalTitleFromTeachingEvent.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
An event has an internal and external event name; previously we were exposing both, but we don't actually need to display the internal event name anywhere on the website, so it makes more sense to just have one event name pointing to the external name attribute in Dynamics.
=> Use external TeachingEvent name

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/TeachingEventRegistrationTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Previously we saved the `TeachingEventRegistration` as part of saving a `Candidate`, but this was later changed so that the registration is saved independently (a deep insert on `Candidate` doesn't work for reasons unknown).
The de-duplication logic was left in the `Candidate` model - this moves it into the `TeachingEventRegistration` model, so if a registration already exists for the user against the event a call to `ToEntity` returns `null` and the `Save` operation on the `CrmService` just returns.
=> Move de-duplication logic into TeachingEventRegistration model

GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs
Since C# doesn't have the notion of a date without a time, we need to specify the swagger format as `date` so that when we generate a client in Ruby it uses the `Date` object instead of the `DateTime` object.
=> Clarify `DateTime` as a `date`

.github/workflows/cve.yml, .github/workflows/dockerbuild.yml, .github/workflows/monitoring.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml, .github/workflows/sonarcloud.yml
- Replaced all the pipeline calls to sentry.io with calls to slack, but only on failure.
- Also added in a wait before terraform to ensure no two pipelines try to run terraform at same time
=> Added calls to Slack

GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs
We are conducting a UX session on Wednesday and don't want to collect any personally identifiable information that then gets sent to the CRM. The easiest way to prevent this is to disable the API from writing any candidate information to the CRM.
=> Temporarily disable sending data to the CRM

GetIntoTeachingApi/Auth/SharedSecretHandler.cs, GetIntoTeachingApiTests/Auth/SharedSecretHandlerTests.cs
If the environment secrets are not defined it will allow a request to authenticate with an empty string (because it matches the secret). To protected against this we perform an empty/null string check on the token and reject it before matching it with a secret.
=> Do not allow an empty secret

.github/workflows/dockerbuild.yml
The secret PEN_TEST_SHARED_SECRET was not being used by any environment so it needs to be added to the deployment script for DEV
=> use PEN Test shared secret in DEV environment

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/ExistingCandidateRequestValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Controllers/CallbackBookingQuotasControllerTests.cs, GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs, GetIntoTeachingApiTests/Models/CandidatePrivacyPolicyTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/ExistingCandidateRequestValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/PhoneCallValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventSearchRequestValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
The API should be time zone agnostic; currently most of the date instantiations use `DateTime.Now`, which returns a date in the time zone of the system. Instead, this commit changes to use `DateTime.UtcNow`, which will return a UTC date that is consistent with what the CRM expects/uses.
=> Convert all DateTime instances to be UTC

GetIntoTeachingApi/Models/TeachingEventSearchRequest.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Models/TeachingEventSearchRequestTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
When a user searches for events that are a certain distance from a postcode we currently do not return events that have the `OnlineEvent` type. This PR updates the search query to return online events events for distance based searches.
It performs a second query to retrieve them (concatenating the results); whilst it would be possible to do it in a single query it would be more verbose (we would need to use LINQKit `PredicateBuilder`), and given the number of events we are expecting there shouldn't be a noticeable performance hit for doing two queries.
=> Return OnlineEvent type events in distance based searches

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/PhoneCall.cs
The Candidate/PhoneCall/CandidatePrivacyPolicy models are no longer directly exposed to the client (instead we return explicit response models) - we no longer need the `JsonIgnore` attributes to prevent fields from being serialized.
=> Remove unused JsonIgnore attributes

.github/workflows/dockerbuild.yml, .github/workflows/release.yml, .github/workflows/ur.yml
Cloud Foundry Team have renamed their terraform cloud foundry provider. This has cause the pipeline to fail.
=> Changed Location of CF Provider

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Models/Validators/MailingListAddMemberValidator.cs, GetIntoTeachingApi/Models/Validators/TeachingEventAddAttendeeValidator.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventAddAttendeeValidatorTests.cs
- Make PreferredTeachingSubjectId required
In the client this is no longer an optional field, so this will enforce the validation in the API.
- Add additional fields to event sign up
When signing up for an event, if a candidate opts-in to the mailing list we will be asking them the 3 additional questions from the mailing list sign up:
* What stage are you at with your degree?
* How close are you to applying for teacher training?
* What subject do you want to teach?
This commit adds the corresponding fields to the `TeachingEventAddAttendee` model and makes them required if the candidate has opted-in to the mailing list.
- Changes to opt-in to event information on mailing list sign up
We no longer have an 'opt in to event information' question on the client; instead we should opt-in the …
=> Changes to the event sign up when opting-in to the mailing list

GetIntoTeachingApi/Startup.cs
The SwaggerUI exposes the internal IP address of the host machine, so we only want this to be accessible on non-production environments to facilitate testing.
=> Only expose SwaggerUI on non-production environments

GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs
Reverts DFE-Digital/get-into-teaching-api#231 - the UR testing has concluded so this can be re-enabled.
=> Revert "Temporarily disable sending data to the CRM"

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs
The subscription attribute names for the new schema changes are incorrectly cased; this fixes the casing. It wasn't picked up when originally shipped due to the interface to the CRM being temporarily disabled for user research sessions.
=> Correct the subscription attribute names

GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Models/PhoneCallTests.cs
- Update PhoneCall channel
The CRM team have requested a new channel id for callbacks.
- Persist PhoneCall in separate transaction
For an unknown reason the CRM team require a `dfe_contactguid` attribute to be set on the `PhoneCall` entity in order for it to correctly link to a `contact` record in Dynamics; this means we need to save the `PhoneCall` in a separate transaction (after persisting the `Candidate` so that we have their `id`).
=> Updates to PhoneCall modelling

GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs
We need to be able to stop the user signing up for the mailing list or event emails if they already have a TTA; this exposes the necessary values as part of the responses.
=> Add AlreadySubscribedToTeacherTrainingAdviser to response models

GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Expose ChannelId for MailingListAddMember request
We want to be able to specify the channel from the front-end for on-campus events (via a QR code and unique URL containing the channel id). This updates the `MailingListAddMember` model to allow the `ChannelId` to be specified and uses it for the candidate/mailing list/event subscription channels.
Add validation to the `Candidate` model to ensure the channel ids are valid according to the CRM.
=> Expose ChannelId for MailingListAddMember request

GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs
When signing up for the mailing list we only want to opt the candidate into an event subscription if their postcode was provided.
=> Only create event subscription if postcode is provided

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs
If a candidate has already been assigned a teacher training adviser as part of the current/legacy system we don't want them to be able to sign up for a TTA again. We determine this by ensuring that their `contact.owningbusinessunit` is not `1A61F629-F502-E911-A972-000D3A23443B` (a TTA).
=> Add legacy support for HasTeacherTrainingAdviser check

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/PhoneCallTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs
Instead of doing it as a pre-map hook on the `Candidate` model we can move the logic into the request model and simplify things.
=> Simplify PhoneCall mapping

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
If all the available slots have been booked we shouldn't return the quota as available for booking.
=> Omit callback booking quotas that are full

GetIntoTeachingApi/Services/CrmService.cs
When querying callback booking quotas attempting to do the availability check as part of the Dynamics query throws an exception; I'm not sure why, but moving this to be performed in-memory resolves the issue.
=> Fix exception on retrieving callback booking quotas

GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
When we create a `PhoneCall` entity we need to find the applicable `CallbackBookingQuota` (if one exists) and increment the `NumberOfBookings` so that the quota will no longer be available once full.
=> Increment CallbackBookingQuota NumberOfBookings when creating PhoneCall

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/TypeEntity.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
TPUK do not currently have the provision to make outbound overseas telephone calls. The adviser service is being updated to remove the callback booking step from the wizard and this change will make sure the validation allows overseas candidates to register with an equivalent degree and no scheduled callback.
=> Prevent scheduled callbacks for overseas candidates

GetIntoTeachingApi/Attributes/CrmETagAttribute.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApiTests/Attributes/CrmETagAttributeTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
- Use LastExecutionTime to clear ETag cache
At the moment we use `NextExecutionTime`; the problem with this is that it doesn't change when we manually trigger a `CrmSyncJob` to run. If we use `LastExecutionTime` then the cache will be cleared after a manual trigger as well as the scheduled job runs.
- Disable ETag caching on Teaching Event search
There is odd behaviour in the hosted environments around search results not always returning correctly. The only difference I can think of with the development environment is that caching is disabled (although I've tested with it enabled in dev and it does seem to behave).
Disable caching in hosted environments to see if that clears up the unexpected results; if it does we can investigate further and then re-enable caching.
=> Disable caching on event search results

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
- Remove approximate distance filtering
The logic here isn't correct; it's not filtering accurately - removing for now so that the search will be accurate and we can investigate and re-introduce later (there aren't many events in the system in general so there shouldn't be a noticeable performance hit for doing this in-memory).
- Re-introduce etag cache on Teaching Event search
The cache wasn't the culprit of the buggy behaviour that was being investigated, so it should be safe to re-enable.
=> Remove approximate distance filtering

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Instead of using the built-in Dynamics event readable id, the CRM team are going to populate a new field with a readable id that matches the current GiT website.
If the new field is not populated we do not want to show the event.
=> Switch readable id to new field

terraform/statuscake/resources.tf, terraform/statuscake/test.env.tfvars
Statuscake is warning that the API is down, when it is more likely that the Healthcheck can take longer than the timeout, which is set to 40 seconds.
This can be overridden so moving it to 60 seconds
=> Setting Timeout on API Statuscake

GetIntoTeachingApi/Startup.cs
The events team want the Teaching Events to be synced more frequently; the job will run every 5th minute and the clients will be updated to retain a client-side HTTP cache for 5 minutes, giving a total of up to 10 minutes cache.
=> Run CrmSyncJob every 5th minute

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs
Some teaching events have a scribble document that is used for registration; this exposes the scribble id so that we can embed the scribble document in the client website.
=> Add ScribbleId to TeachingEvent

GetIntoTeachingApi/Adapters/GeocodeClientAdapter.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs
Add `postcode` and `result` labels to the geocoding metrics; this will enable us to track any teaching event search requests that fail because we are unable to geocode the postcode. It will also enable us to see which postcodes end up falling through the local database lookup and result in a call out to Google.
=> Add labels to geocode metrics

monitoring/grafana/dashboards/get_into_teaching_api.json
Add additional panels for external monitoring of:
- Notify Service API calls
- Google Geocoder API calls
- Geocode requests by postcode
- Error rates on external requests
Add requests in progress and req/s single stat panels.
=> Improve external monitoring

.github/workflows/dockerbuild.yml, .github/workflows/production.yml, .github/workflows/release.yml, GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs, README.md, terraform/paas/application.tf, terraform/paas/variables.tf
The Sentry C# client appears to recommend a different way of integrating it to what Sentry's wizard shows you initially; this updates to leverage `useSentry()` instead of `Sentry.Init` directly.
Also includes temporary operations endpoint to enable testing the integration in production.
=> Use recommended Sentry integration method

terraform/paas/variables.tf
There was an error on deployment:
```
Error: Reference to undeclared input variable
on application.tf line 42, in resource "cloudfoundry_app" "api_application":
42:          Sentry__Dsn            = var.SENTRY_DSN
An input variable with the name "SENTRY_DSN" has not been declared. This
variable can be declared with a variable "SENTRY_DSN" {} block.
```
It seems to indicate the variable name should have been `SENTRY_DSN` and not what we want the environment variable name to be (`Sentry__Dsn`).
=> Use secrets var name instead of env var name

.github/workflows/production.yml
When you release to production it will ask for a TAG, this tag should be the Tag for the Release you want to send to Production.
This will then send the version of the Docker Image and Terraform to Production rather than the current master.
=> Product Release Workflow to Permit TAG

GetIntoTeachingApi/Startup.cs
It appears to be fixed in a later version of .NET Core but the version we are using occasionally throws an `InvalidOperationException` due to performing a synchronous operation.
This updates Kestrel config to allow sync operations.
=> Workaround for exception in Prometheus.HttpMetrics.HttpRequestDurationMiddleware

GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs
We are likely always going to present these in alphabetical order to the user, so sorting it in the API makes sense. The other types will remain ordered by their `id`, which seems to make sense for most of the option sets in Dynamics.
=> Sort countries and teaching subjects alphabetically

GetIntoTeachingApi/Adapters/CdsServiceClientWrapper.cs
The `CdsServiceClient` timeout by default is 2 minutes, but the healthcheck endpoint depends on the CRM and we want it to complete in less time than that if there is a problem.
=> Set CdsServiceClient timeout to 30s

GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs
The candidate id is not PII but will enable us to look up a candidate in the CRM if something goes wrong/needs investigating.
=> Log out candidate id as part of UpsertCandidateJob

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
- Always opt in to bulk emails/mm on event sign up
When a candidate signs up for an event we want to be able to both send them bulk emails and marketing material.
- Prevent event subscription being downgraded
When a candidate signs up for an event and passes their post code when opting into the mailing list, we give them a 'local event' subscription type. If they then go on to sign up for another event and don't provide their postcode we currently downgrade their subscription to a 'single event' type.
Instead, if they have provided their postcode as part of an event sign up in the past then we want to keep their subscription type as 'local event'.
=> Changes to Subscription modelling

GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs
When signing up for an event subscription we should be setting the contact-level `DoNotBulkEmail` preference to `false`.
=> Opt-out of DoNotBulkEmail on event sign up

GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TypeEntity.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs
When a Candidate signs up with a `PreferredEducationPhaseId` of primary we do not ask them their preferred teaching subject (only secondary teachers will specialise in a particular teaching subject). The CRM, however, requires this field to be set and it should have the guid corresponding to `Primary`.
=> Default PreferredTeachingSubjectId to Primary

terraform/paas/production.env.tfvars
Increase the number of production instances to two, to try and prevent gliching down time when AWS does tricks
=> Increase Instances to 2

GetIntoTeachingApi/ModelBinders/TrimStringModelBinder.cs, GetIntoTeachingApi/ModelBinders/TrimStringModelBinderProvider.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/ModelBinders/TrimStringModelBinderProviderTests.cs, GetIntoTeachingApiTests/ModelBinders/TrimStringModelBinderTests.cs
When a HTTP request comes in to ASP.NET Web API the payload is bound to a request model; when this happens we hook into the operation and ensure any string attributes are trimmed.
When we read/write JSON string attributes there aren't any instances where having trailing/leading white space would be useful or intentional.
Accepting white space on the start/end of strings is currently causing issues with the postcode validator, as the regex is strict in this respect, yet it shouldn't matter if a user enters a postcode with white space around it.
Initially I attempted doing this with a custom `JsonConverter`, but that only applied to POST request body payloads and not GET query parameters. By using a model binder we should be covered for any content-type.
=> Trim white space from JSON string attributes

.github/workflows/monitoring_prod.yml
The Terraform for monitoring has previously been changed, now it is time to change the Workflow to use 13.4
This will not effect delivery or the application and is not urgent
=> Monitoring Production Workflow Upgraded

.github/workflows/sonarcloud.yml, GetIntoTeachingApi/OperationFilters/ClientIpOperationFilter.cs, GetIntoTeachingApi/Startup.cs
Update the Swagger configuration to accept an `X-Client-IP` header on all requests. The auto-generated library will allow this to be specified per-API request, for example:
```
result = api_instance.get_callback_booking_quotas(x_client_ip: "1.2.3.4")
```
Going forward this IP address will be used to rate limit requests to the API, in addition to the API key of the client (we can create custom IP/Client ID resolvers in the [ASPNetCoreRateLimit](https://github.com/stefanprodan/AspNetCoreRateLimit) package).
If the IP address is unspecified the requests will fall into the rate limiting bucket based solely on the client ID (API key in use).
Can be set to the end user IP address to allow per-user rate limiting in the API. This is how we will be rate limiting individual users when they request …
=> Accept X-Client-IP header on all requests

monitoring/grafana/dashboards/csp_violations.json
A dashboard to detail the app/tta CSP violations, including:
- Total violations by directive violated
- Total violations by document URI
- Total violations by blocked URI
- Recent CSP violation log messages
=> Add CSP violations dashboard

GetIntoTeachingApi/Jobs/LocationBatchJob.cs, GetIntoTeachingApi/Models/Location.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Models/LocationTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
When we can't find a postcode geolocation from our local cache we go off to the Google Geocoding API. We're finding that many teaching events share the same postcode, so we're requesting it multiple times from Google during a sync, which both slows the sync down and costs us money. Instead, this commit persists the location to our cache so that subsequent lookups don't  need to hit Google's API.
=> Cache responses from Google Geocoding API

monitoring/grafana/dashboards/get_into_teaching_api.json
Add a deployment annotation to the dashboard, useful for linking a change in the graphs to a particular deployment.
Remove 404's from 'error' panels, as 404s are expected in a number of scenarios (unsuccessful matchback).
=> Add deployment annotation to dashboard

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
- Add endpoint to get upcoming events by type
When a user lands on the events index page in the website we want to be able to show them the next 3 events that are upcoming for each type. This improves the user experience when we are approaching the end of the month and there are no
longer any events within the current month to display.
Adds a new endpoint `/api/teaching_events/upcoming_indexed_by_type` that will return the upcoming teaching events grouped by their type.
The return type is `Dictionary<string, IEnumerable<TeachingEvent>>` due to `System.Text.Json` not yet supporting non-string Dictionary keys (it would be preferable to use an `int` here).
Adds a `/api/teaching_events/search_indexed_by_type` for consistency, with a view to removing the current `/search` endpoint once …
=> Add endpoint to get upcoming events by type

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
This endpoint was replaced with `search_indexed_by_type`.
Updates the test for the ETag attribute to include the two new search endpoints (I had missed this in the original PR).
=> Remove deprecated search endpoint

monitoring/grafana/dashboards/get_into_teaching_apps.json
First pass at adding a dashboard for the apps; the app/source can be picked from a dropdown at the top.
=> Add dashboards for the GiT front-end apps

monitoring/prometheus/alert.rules
As a first attempt at getting some metric alerting in place, this should inform us when a client or end user receives a 429 response (too many requests) or if there are high numbers of 404s being triggered in the app/tta services.
=> Add alert rules for any 429s and high 404s

monitoring/prometheus/alert.rules
The new alert rules I added didn't propagate through to the alert manager interface; I'm removing them and attempting to rename the alert in the example group to see if that causes an update.
=> Test changing alert rule

monitoring/prometheus/alert.rules
Alert manager doesn't like it yet, trying to figure out why as the expressions work fine in Grafana.
=> Testing HighNotFound expression

monitoring/prometheus/alert.rules
Alert on high numbers of 404 requests (>15 in 10 minute period) and any 429 requests.
=> Introduce HighNotFound and TooManyRequests alerts

monitoring/prometheus/alert.rules
We often see the /csp_reports endpoint returning a 429 response; we don't want to treat these with the same severity as the other 429 responses.
=> Exclude csp_reports from 429 alerting

monitoring/prometheus/alert.rules
Add additional metric alerting for the API:
FailedJobs - Alert when any job fails.
HighGoogleApiCalls - Alert when a high number of Google API calls are made (>5 in a 10m period).
GoogleApiErrors - Alert when the Google API returns a non-success response.
ClientApproachingRateLimit - Alert when a client is approaching the rate limit threshold (15rpm out of an available 30rpm).
HighCpu - Alert when max CPU utilization is over 70%.
HighMemory - Alert when max memory utilization is over 256MB.
HighDatabaseConnections - Alert when max database connections exceeds 75 (out of an available 100).
=> Additional API metric alerts

GetIntoTeachingApi/Adapters/GeocodeClientAdapter.cs
We are seeing an error on dev and the API key has been checked, so it must be something else going on. This should give us the status text back from Google.
=> Log Google API response status text

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Integration/RateLimitingTests.cs, README.md, monitoring/grafana/dashboards/get_into_teaching_api.json
- Enforce rate limiting to vulnerable endpoints
Rate limits endpoints that could be exploited:
```
POST /candidates/access_tokens
POST /mailing_list/members
POST /teaching_events/attendees
POST /teacher_training_adviser/candidates
```
Set to 30 requests/min which is well above the current traffic (peaking at ~2rpm). This should have enough buffer in it for when we go up to 40% rollout.
The /operations endpoints are excluded from rate limiting.
- Add graph to monitor rate limited requests
Adds a graph to display the requests/minute for each of the rate limited endpoints. The panel also has thresholds for 15rpm (warning) and 30rpm (critical) so that we can see when traffic is approaching the rate limits and needs to be adjusted.
=> Rate limit vulnerable endpoints by client 

Dockerfile, GetIntoTeachingApi/Database/DbConfiguration.cs, entrypoint.sh
EF Core advise against running the migrations at runtime in case two instances attempt to execute them at the same time. They recommend exporting the migrations to SQL and running them manually, which is overkill for what we need so a happy medium is to run the via the CLI before the instance starts.
=> Run EF Core migrations from CLI

Dockerfile, entrypoint.sh
The `dotnet ef database update` command only works when we have access to the source code; in CI we only have access to the published app DLL. In order to run the migrations we have to use `dotnet exec` directly, which is what `dotnet ef` calls under the hood.
=> Attempt to run migrations from CLI

GetIntoTeachingApi/Models/ExistingCandidateRequest.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Models/ExistingCandidateRequestTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
The CRM contains some candidates that have leading/trailing white space around their first name, last name and email address.
Ignore white space when comparing first/last name and email address.
Match on emails containing the provided email string initially (to positively match even if the email in the CRM has white space) - we do another, exact match as part of the in-memory match-back.
=> Ignore leading/trailing whitespace in match-back

GetIntoTeachingApi/Startup.cs
The API uses the staging environment for all production-like environments; we don't want to enforce rate limiting in these environments so that the integration tests can successfully run.
=> Disable rate limiting in Staging environments

GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Integration/RateLimitingTests.cs, monitoring/grafana/dashboards/get_into_teaching_api.json
- Up rate limits from 30 to 60 requests/minute
We're seeing spikes up to around 15rpm so this should give us plenty of breathing room for when we increase the rollout distribution.
- Restrict infrastructure metrics by space
To avoid over requesting data this scopes the infrastructure metrics by space.
Increases the threshold indicators on the rate limiting indicators to 30 (warning) and 60 (critical) as we are seeing spikes up to ~15 requests/minute at busy periods, so the rate limiting will be altered in a follow up commit.
=> Increase rate limits from 30 to 60 rpm

GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Helpers/DatabaseTests.cs
We are getting permission errors occasionally on deployment due to migrations running on multiple instances. To reduce of the chance of this happening this commit will run migrations earlier (hopefully before the application has fully 'started' so before the second instance gets spun up) and also check to ensure pending migrations exist before attempting to run them.
=> Run migrations earlier

monitoring/prometheus/alert.rules
The rate limit threshold has been set at 60 in the API; this updates the ClientApproachingRateLimit warning threshold to be 30 rpm.
=> Lift ClientApproachingRateLimit threshold

GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Database/DbConfigurationTests.cs, GetIntoTeachingApiTests/Helpers/DatabaseTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
We are getting conflicts because two instances are trying to run the migrations at the same time.
Restrict to instance 0 running the migrations, which should be the first instance spun up in a deployment.
=> Only run migrations on first instance

monitoring/grafana/dashboards/get_into_teaching_api.json
The rate limits apply over 5 minute periods, so grouping to 5 minutes instead of 1 makes the graph better reflect the behaviour.
=> Group rate limiting data sets by 5m intervals

monitoring/prometheus/alert.rules
The rate limit was applying to the `sum` of all possible rate limited endpoints, so it would fire if we had 10 TTA sign ups and 20 mailing list sign ups, when it should only fire if any one of the rate limited endpoints exceeds 30rpm.
Change `sum` to `max` corrects the behaviour.
=> Correct API rate limit alert rule

GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
If we are running locally we always want to run the migrations. In the event that the env var is not set we would also be better off running the migrations than not, so defaulting to 0 makes sense.
=> Default CF_INSTANCE_INDEX to 0

GetIntoTeachingApi/Adapters/IPerformContextAdapter.cs, GetIntoTeachingApi/Adapters/PerformContextAdapter.cs, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs
Add a Histogram metric to track the job duration for `UpsertCandidateJob` so that we can get a feel for how long they are remaining in the queue for before being sent to the API or dropped.
=> Track how long UpsertCandidateJobs spend in the queue

monitoring/grafana/dashboards/get_into_teaching_api.json
Add a graph plotting the time jobs spend queued, grouped by 1h intervals and displaying 100, 99, 98, 95, 75 and 50th percentiles.
=> Add graph plotting the time jobs spend queued

GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Integration/RateLimitingTests.cs, monitoring/grafana/dashboards/get_into_teaching_api.json, monitoring/prometheus/alert.rules
- Increase rate limit thresholds
We saw a spike of match back requests nearing 60rpm, so upping it to 250rpm and increasing the other endpoints to 100rpm.
- Update thresholds to match new rate limits
- Split rate limit alert rules
We now have two rules, one to cover the majority of sign up requests and one for the match back endpoint, which receives more requests.
=> Increase rate limit thresholds

terraform/monitoring/modules.tf
The dependant modules in BAT Building blocks has been merged to master, so we can now use that branch
BAT building blocks is a GIT repository we use to keep common code in for various Becoming a teacher projects. The work we have carried out developing the Monitoring for GiT is being re-used on other projects.
=> Dependant changes merged into master

monitoring/prometheus/alert.rules
Link the App and TTA alert rules to the runbook in Confluence and the respective Grafana panels.
=> Link App/TTA alert rules to the runbook/Grafana

monitoring/prometheus/alert.rules
Link the API alert rules to the runbook in Confluence and the respective Grafana panels.
=> Link API alert rules to the runbook/Grafana panels

monitoring/grafana/dashboards/get_into_teaching_api.json
This had been set to the random walk metric for some reason.
Also shuffles some of the panels around, which is why the diff is so big.
=> Fix Google API calls panel

GetIntoTeachingApi/Jobs/CrmSyncJob.cs, GetIntoTeachingApiTests/Jobs/CrmSyncJobTests.cs
We're seeing errors on deployment but only when running multiple instances.
This commit places a distributed lock on the sync operation to try and diagnose if this method being ran in parallel by multiple instances results in the error (a sync is performed when the instance starts).
=> Place distributed lock on CRM sync operation

.github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml, GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Database/GetIntoTeachingDbContext.cs, GetIntoTeachingApi/Database/GetIntoTeachingDbContextFactory.cs, GetIntoTeachingApi/Fixtures/ukpostcodes.dev.csv, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Helpers/DatabaseCollection.cs, GetIntoTeachingApiTests/Helpers/DatabaseFixture.cs, GetIntoTeachingApiTests/Helpers/DatabaseTests.cs, GetIntoTeachingApiTests/Helpers/GetIntoTeachingWebApplicationFactory.cs, GetIntoTeachingApiTests/Integration/RateLimitingTests.cs, GetIntoTeachingApiTests/Jobs/LocationBatchJobTests.cs, GetIntoTeachingApiTests/Jobs/LocationSyncJobTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs, README.md, docker-compose.yml
- Run against Postgres DB in development/test
Updates the development and test environments to execute against a dockerized Postgres database instance instead of using the in-memory database.
The advantages to do this are:
- Migrations are ran in the test suite/development.
- We can load and persist all the geolocation data in development.
- Development/test more closely match production.
- It's easier to run the app on a non-Windows machine.
The test environment works by creating a new database for each test that requires one; we use the `gis_test` database that is created for us as a template (after migrations have been ran).
Whilst it would be quicker to wrap each test run in a transaction using the same database, this setup would be more complicated and using Postgres templates seems …
=> Switch to docker-compose for development

.gitignore, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Startup.cs, README.md
Previously we had to manually edit the `launchSettings.json` file with the development credentials for the CRM etc. This was susceptible to being accidentally committed into git (as we can't `gitignore` the `launchSettings.json` file completely).
Instead, this commit introduces `dotnet.env` for managing development secrets in an ignored `.env.development` file.
=> Use dotenv.net for development secrets

GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs
We don't ask returners for their preferred education phase as part of the TTA sign up, instead defaulting it in the client-side to secondary. This is not ideal in the scenario where the candidate goes down the returner path then backs out and goes down the new candidate path; we end up pre-selecting secondary for their education phase even though they didn't explicitly select it.
Defaulting it in the API avoids this issue (we no longer have to set it in the client).
=> Default education phase to secondary for returners

GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
If the candidate is returning to teaching we default the education phase so it doesn't need to be specified; this relaxes the validation rule.
=> Adjust validation to allow null preferred education phase

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
We are seeing an odd error in Sentry whereby we can't project between two coordinates:
https://sentry.io/organizations/dfe-bat/issues/2063757538/?project=5276954&referrer=slack
The only thing I can think of that's causing this is a postcode is getting geocoded to a latitude/longitude that falls outside the coordinate system we have defined in `GeometryExtension`. This _shouldn't_ be possible as it covers the whole of the United Kingdom, but perhaps there's a bad entry in the database somewhere against a postcode that results in this error.
Adding the logging should help diagnose the issue where it happens again.
The only other place that could the cause is a postcode against a teaching event; if this is the case it's going to be harder to diagnose so I'll cross that bridge if/when we come …
=> Log when searching around postcode

.github/labeler.yml, .github/workflows/labeler.yml
When A PR is created the labeler will attempt to assign it a label based upon what code has changed.  
This is useful in the DevOps environment as we are monitoring repositories as a team, identifying work the team could do if an individual is not available
=> Added labeller

GetIntoTeachingApi/Controllers/CallbackBookingQuotasController.cs, GetIntoTeachingApi/Services/CallbackBookingService.cs, GetIntoTeachingApi/Services/ICallbackBookingService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Controllers/CallbackBookingQuotasControllerTests.cs, GetIntoTeachingApiTests/Helpers/LoggerTestHelpers.cs, GetIntoTeachingApiTests/Services/CallbackBookingServiceTests.cs
We want candidates to be able to sign up for a TTA even when the CRM is offline. Currently, there is a hard dependency on the CRM for the callback booking quotas as we query these at the point of displaying them to the user (so as to have the most up-to-date information).
The issue with this is that if the CRM is offline we will display an error to the user. Instead, we want to let the user proceed and book from a pre-generated list of fallback quotas.
The fallback quotas should include the next 5 working days (not including the current day) and have times from 9am to 4:30pm available in 30 minute intervals.
If the CRM is unavailable or returns an empty set of quotas, then we want to instead display the generated list of fallback options.
=> Use fallback booking quotas when CRM is unavailable

GetIntoTeachingApi/Adapters/GeocodeClientAdapter.cs
When we were creating the coordinates in response to the Google location result we weren't specifying a coordinate system. This meant that the coordinates would use the default system (or no system, I'm not sure which) and when we came to compare them in the radius search with a coordinate in the Wgs84 coordinate system it would raise an exception.
Updates to use the `NtsGeometryServices` factory to create the coordinate in the correct system.
Fixes new occurrences of this Sentry issue:
https://sentry.io/organizations/dfe-bat/issues/2044744917/?project=5276954&query=is%3Aunresolved
We will still get a few errors like this in production from any postcodes that have been geocoded by Google already (there's only a small number, probably half a dozen). When this happens we can find out the …
=> Use correct coordinate system in GeocodeClientAdapter

GetIntoTeachingApi/Adapters/GeocodeClientAdapter.cs, GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApi/Jobs/LocationBatchJob.cs, GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApi/Models/Location.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Contants.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Jobs/LocationBatchJobTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
- Add endpoint to trigger location batch job.
- When a location batch job is run, replace locations where the source is unknown with CSV source. 
- Tags locations cached from Google Geocoding as "Google"
- Specifies "postcodes" in the Google Geocode request.
=> Correct postcodes with unknown sources

GetIntoTeachingApi/Attributes/PrivateShortTermResponseCacheAttribute.cs, GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Controllers/TypesController.cs, GetIntoTeachingApiTests/Attributes/PrivateShortTermResponseCacheAttributeTests.cs, GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs
At the moment we monkey-patch the Ruby API client library to cache GET request responses for 5 minutes. It was done this way originally as ASP.NET Core was preventing us from setting `Cache-Control` headers on authenticated requests.
This no longer seems to be the case and the core team appear to be actively working towards a less opinionated caching implementation.
Add a custom attribute for short term (5m), private response caching that is safe to use on most GET responses (essentially every action that has a `CrmETag` attribute). 
It is applied to:
- All /types endpoints
- All /privacy_policies endpoints
- GET /teaching_events endpoints (search and upcoming)
=> Allow GET requests to be cached privately for 5m

GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Some locations were being added to the database with incorrect coordinates, these have been tagged as having an unknown source. This PR adds and endpoint which removes them from the database.
=> Add endpoint to remove locations of unknown source

terraform/paas/production.env.tfvars, terraform/paas/test.env.tfvars
On the Test environment the memory allocation is set to 1GB. Recently the application has hit the limit on the Test environment, and as a precaution this PR will set the upper limit to 2GB. For both Test and Production.
=> Increase Memory Allocation

GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs
Some postcodes were being saved in postgres incorrectly (see PRs [390](https://github.com/DFE-Digital/get-into-teaching-api/pull/390) and [395](https://github.com/DFE-Digital/get-into-teaching-api/pull/395) for more details). As part of the fix, it was necessary to trigger a manual location sync. This is being removed as it is no longer needed.
=> Remove manual location sync endpoint

GetIntoTeachingApi/Models/Location.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventSearchRequestValidatorTests.cs
\A...\z matches the beginning and strict end of the string and is therefore less ambiguous than ^...$, which has the potential to match when there is extra text after a newline.
=> Update postcode regex to match app

GetIntoTeachingApi/Auth/SharedSecretHandler.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Auth/SharedSecretHandlerTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs, terraform/paas/application.tf, terraform/paas/variables.tf
We introduced this for the penetration test company to be able to access the app in the test environment; they no longer need access so we can remove it.
=> Remove PEN_TEST_SHARED_SECRET

GetIntoTeachingApi/Attributes/LogRequestsAttribute.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/LoggableMessageComposer.cs, GetIntoTeachingApiTests/Attributes/LogRequestsAttributeTests.cs, GetIntoTeachingApiTests/Utils/LoggableMessageComposerTests.cs
Currently when the API receives a request the appropriate request model validator is ran automatically before the controller action is called. The side effect of this is that the `LoggableAttribute` action filter is never ran for these requests, meaning we don't have meaningful logs around what was in the request payload.
This PR breaks out the logic to translate an `ActionExecutingContext` and `ControllerActionDescriptor` into formatted, sanitised log messages to a new utility class `LoggableMessageComposer`.
We then hook into the `PostConfigure` callback and override the `InvalidModelStateResponseFactory` to log out the request details before calling the built in factory that formats and returns a helpful 400 response..
=> Log request details on validation failure

.github/workflows/build.yml
The API workflow runs the full suit of cypress tests, these can take a while. Since it does not deliver to  production, we might as well allow cypress to trigger errors in slack if it fails, but not wait for it.
=> Fire and Forget Cypress Tests

GetIntoTeachingApi/Startup.cs
We used to run this every time the app booted as syncs were infrequent and it could have been helpful, but we now run the CrmSync every 5 minutes so its not really necessary any longer.
Also this may prevent the exception thats often raised when the app boots and tries to sync before the permissions to the DB have propagated.
=> Only run CrmSyncJob on first boot

GetIntoTeachingApi/Startup.cs
Temporarily enables rate limiting in the test environment so we can ensure its functioning correctly with the Redis DB.
=> Enable rate limiting in test environment

GetIntoTeachingApi/Startup.cs
Reverts DFE-Digital/get-into-teaching-api#412 - this was enabled temporarily in the test environment so that we can ensure the rate limiting counters work correctly when backed by the Redis store.
=> Revert "Enable rate limiting in test environment"

.github/workflows/build.yml
sometimes the message does not contain the regex used to find the PR. This causes a problem with no release tag.
So creating a date based tag until a solution can be found
=> Fix Duplicate Tagging Issue

GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApi/Models/Location.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Jobs/LocationSyncJobTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
I missed this in the original review, but the `Source` enum should be scoped to the `Location` model.
Rename to `SourceType` so that it doesn't clash with the `Source` attribute.
=> Scope Source enum to Location model

GetIntoTeachingApi/Jobs/CrmSyncJob.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Jobs/CrmSyncJobTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
- Inject ICrmService into the Store
We pass an instance of `ICrmService` into various methods of the `IStore`. This makes the implementation more verbose than it needs to be; injecting an instance directly into the `IStore` instead of specific methods simplifies things.
=> Inject ICrmService into the Store

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/Validators/CandidatePastTeachingPositionValidator.cs, GetIntoTeachingApi/Models/Validators/CandidateQualificationValidator.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/PhoneCallValidator.cs, GetIntoTeachingApi/Models/Validators/TeachingEventRegistrationValidator.cs, GetIntoTeachingApi/Models/Validators/TeachingEventSearchRequestValidator.cs, GetIntoTeachingApi/Validators/LookupItemIdValidator.cs, GetIntoTeachingApi/Validators/PickListItemIdValidator.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Validators/LookupItemIdValidatorTests.cs, GetIntoTeachingApiTests/Validators/PickListItemIdValidatorTests.cs
- Add custom property validators for pick list/lookup item ids
We often validate a foreign key against the available pick list/lookup items that are in the CRM. Until know we've been doing this in a fairly verbose way; instead this adds a custom property validator that will make the syntax more concise.
- Update validation rules to use PickList/LookupItemIdValidator
Updates the validation rules that were previously querying the store in private methods to now use a custom property validator that handles querying the store and matching an `Id`.
=> Dry up validation with custom property validator

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
[Trello-660](https://trello.com/c/npt5sr4O/660-add-functionality-within-the-api-to-show-non-postcode-tagged-virtual-ttt-events-in-all-postcode-searches)
At the moment we have a few different kinds of 'Online Event':
- Events with type 'Online Event'
- Events with `IsOnline` set to `true` and no `Buillding.AddressPostcode`
- Events with `IsOnline` set to `true` and a `Building.AddressPostcode` (virtual)
When a radius-based search is performed we currently return events with type 'Online Event' in the results.
Going forward there will be another kind of fully online event type (not virtual) that is a 'Train to Teach' type event where `IsOnline` is `true` and there is no `Building.AddressPostcode`.
Instead of only returning 'Online Event' type events in radius-based searches, we want to …
=> Return all 'Online Events' on distance-based search

GetIntoTeachingApi/Models/Validators/TeachingEventSearchRequestValidator.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventSearchRequestValidatorTests.cs
Currently if you try and do an event search for all events after a date it throws a validation error. Instead, we should allow this query and return all events after the given dates.
Whilst this should have been possible anyway the use case was not required in the app, but going forward we need to be able to do this exclude archived events (being introduced shortly) from the event search.
=> Allow event search with only start after date

terraform/paas/production.env.tfvars, terraform/paas/statuscake.tf, terraform/paas/test.env.tfvars
A comment on an another repository suggested removing the set list of status codes as they were just the default. Allowing the  upstream API to do the work.
This hadn't been picked up on the changes to this repository and therefore needed to be done.
=> Removed List of Default Status Codes

GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Geometry.Distance is translated to PostGIS [ST_Distance](https://postgis.net/docs/ST_Distance.html). Because teachingEvent.Building.Coordinate is attributed with column type geography, and because origin is implicitly converted to the geography type (it has an SRID), ST_Distance returns the distance between two points in meters.
This means that the events distance filtering can be performed in the database instead of in memory.
=> Change distance filter to work in database

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
[Trello-672](https://trello.com/c/Mx2EzMU4/672-development-create-an-archive-repository-for-online-events-which-are-3-4-months-old)
We are going to be adding a new page to the website that will allow users to browse 'archived' online events - these are events that are now in the past, up to 4 months old.
This commit updates the sync logic to query and cache events as far back as 4 months ago. The 4 month threshold isn't 'strict', so for ease I've treated it as 4 * 31 days.
The app needs to be updated first to ensure all requests are scoped to a date, so as not to inadvertently include archived events under 'all months'.
=> Sync archived teaching events

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/TeachingEventsByType.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/TeachingEventsByTypeTests.cs
Introduces a new response model for returning teaching events grouped by type. Previously we were using the format:
``` { "<typeid>": [<events>] } ```
This isn't a very RESTful response and also causes the type id to be returned in a string, where in actuality its an integer value.
This commit updates the response to be:
``` [{ "typeId": <typeid>, "teachingEvents": [<events>] }, { ... }] ```
In order to introduce the new response type an additional endpoint have been added:
``` 
teaching_events/search_grouped_by_type
```
These replace the existing methods, that will be removed once the clients have been updated (note the `upcoming_indexed_by_type` endpoint is going to be deprecated, which is why there is no equivalent `_grouped_` endpoint above for it):
``` …
```
=> Add TeachingEventsByType response model

terraform/paas/network.tf
Logic suggests use the blue/green id when using the network id, however that fails with an error. so using the natural id
=> Use ID rather than BLUE/GREEN ID

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
The `upcoming_teaching_events_indexed_by_type` endpoint is being removed completely (the clients have been updated to use the search endpoint to achieve the same thing). The `search_teaching_events_indexed_by_type` endpoint is being removed in favour of the newer `search_teaching_events_grouped_by_type`, which returns results in a more rest-ful structure.
This is safe to merge now that https://github.com/DFE-Digital/get-into-teaching-app/pull/742 has been deployed.
=> Remove x_teaching_events_indexed_by_type endpoints

README.md
Originally I expected to be able to run `dotnet ef` CLI commands after ssh'ing into the production docker container via cloud foundry. Upon checking this in development it turns out the `dotnet ef` CLI won't function without the application source code being available, which isn't the case (in prod we only have the compiled DLL).
Instead, the only way to manually apply/rollback migrations in production involves generating the SQL queries locally, then creating a conduit into the production database and manually executing the SQL.
=> Add manual migration/rollback instructions for production

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Services/CandidateAccessTokenService.cs, GetIntoTeachingApi/Services/ICandidateAccessTokenService.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Services/CandidateAccessTokenServiceTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs
- Add metrics for TOTP generation/verification
We want to be able to track how many TOTPs are generated and, out of those, which are successfully verified (and, similarly, which are generated but never verified).
The metrics collect the `candidate_id` and the token so that we can attribute metrics to specific users without storing PII. The outcome of the verification process is also stored as a label, so we can determine if the correct TOTP was provided.
- Increment TOTP generated/verified metrics
When a TOTP is generated or verified we want to increment the corresponding metric. In order to link OTPs to a candidate the TOTP interfaces have been expanded to include a `candidateId`.
We also store the TOTP itself in the metric label so that we can see when the candidate verified the TOTP …
=> Collect metrics for Timed One Time Passwords (TOTPs)

monitoring/grafana/dashboards/get_into_teaching_api.json
We are now sending metrics for generated/verified Timed One Time Passwords. This enables us to see how many we are generating vs how many are being verified, in addition to how many times a user is failing to enter a valid TOTP.
Add Grafana panels to visualize the new metrics.
=> Add TOTP metrics to engagement row

GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Services/SubscriptionManager.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Services/SubscriptionManagerTests.cs
- Extract subscription management logic from request models
Currently the request models handle configuring the various subscription attributes against a candidate. There is some duplication here between the mailing list and events sign up (as you sign up for events on mailing list sign up and vice-versa).
This extracts the subscription logic into a new `SubscriptionManager` service that is responsible for configuring the correct subscription consent, channels, etc based on the given `Candidate`.
- Extract candidate consent into SubscriptionManager
When a candidate signs up for a service they get a particular level of consent. To clean up the request models this logic has been extracted into the new `SubscriptionManager` class.
In addition, after talking to the CRM team we are also going …
=> Simplify the service request models

terraform/paas/variables.tf
[Rename GovPaaS Organisation](https://trello.com/c/T6s07KQ9/759-as-the-usage-of-paas-in-dfe-is-growing-and-we-need-to-scale-up-governance-and-tools-it-was-decided-to-move-to-a-simpler-model-wi)
As the usage of paas in DfE is growing and we need to scale up governance and tools, it was decided to move to a simpler model with a single organisation instead of the 3 we have today. To this effect, dfe-teacher-services will be renamed to dfe and become the single organisation.
=> Rename GovPaas Organisation

.github/workflows/build.yml
https://trello.com/c/Ueda1EDd/640-release-notes-are-only-first-line
The release is only created with the first line of the PR, I want to improve this to provide the full PR Body
Create a MD file and use that to create the release
This will not effect the product
This should not make any effect to the SLACK output, that will come later
=> Better Release Body

GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
The `DbConfiguration` shouldn't care about the instance index; instead this check can be encapsulated in `IEnv` and exposed as `IsMasterInstance` to de-clutter and better encapsulate `DbConfiguration`.
=> Abstract master index check from DbConfiguration

GetIntoTeachingApi/Models/Client.cs, GetIntoTeachingApi/Models/Validators/ClientValidator.cs, GetIntoTeachingApiTests/Models/ClientTests.cs, GetIntoTeachingApiTests/Models/Validators/ClientValidatorTests.cs
[Trello-789](https://trello.com/c/h8Dxra2B/789-implement-way-to-manage-multiple-client-keys-in-the-api-with-varying-permissions)
This PR is the first step towards supporting multiple, independent clients with their own API keys and roles:
----
- Introduce a `Client` model that will represent a consumer of the API. A `Client` consists of:
```
- Name
- Description
- Role
- ApiKeyPrefix
- ApiKey
```
The `ApiKeyPrefix` will be used to construct the name of the environment variable that will contain the client's `ApiKey`, in the format:
```
<api_key_prefix>_API_KEY_<environment>
```
For example, `GET_INTO_TEACHING_API_KEY_PRODUCTION`.
The `Role` attribute will be used to scope access to controllers/actions for this particular client. A `Role` could be applied to multiple clients.
=> Add Client model/validations

GetIntoTeachingApi/Fixtures/clients.yml, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Services/ClientManager.cs, GetIntoTeachingApi/Services/IClientManager.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Services/ClientManagerTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
[Trello-789](https://trello.com/c/h8Dxra2B/789-implement-way-to-manage-multiple-client-keys-in-the-api-with-varying-permissions)
This PR is the second step towards supporting multiple, independent clients with their own API keys and roles:
----
- Add ClientManager to load API clients from YAML
When a request comes in to the API we need to be able to match the API key against the associated client, so that we can authenticate and authorize the request.
Add `ClientManager` that is responsible for loading a static list of clients from YAML and provides a method to get a client associated with a given API key (which will be used in the authentication handler).
The `Env` class has also been updated to return `Test` as the environment name instead of `null`, which enables us to test matching a …
=> Load API client definitions from YAML

GetIntoTeachingApi/Services/SubscriptionManager.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Services/SubscriptionManagerTests.cs
Candidates signing up for TTA are currently opted into postal/bulk postal mail if returning to teaching. This is not longer wanted.
=> Update subscriptions to not opt TTA candidates into post/bulk post

GetIntoTeachingApi/Controllers/CallbackBookingQuotasController.cs, GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Fixtures/clients.yml, GetIntoTeachingApiTests/Controllers/CallbackBookingQuotasControllerTests.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
- Add GiT services as API clients
Adds the Get into Teaching services to the `clients.yml`. We can merge this and the two apps will continue to use the legacy secrets until we set up the new secrets in Azure and transition them over.
- Assign GiT API client roles
Assigns roles for the GiT API clients. This will limit access to only the controllers/actions required by the service.
=> Add GiT services as API clients

GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Services/ClientManager.cs, GetIntoTeachingApiTests/Services/ClientManagerTests.cs
I'm not sure why I had it in my head that the environment name had to be in to distinguish the keys 😕
=> Remove environment name from API key variable name

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/RateLimiting/ApiClientRateLimitConfiguration.cs, GetIntoTeachingApi/RateLimiting/ApiClientResolveContributor.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/appsettings.json
[Trello-789](https://trello.com/c/h8Dxra2B/789-implement-way-to-manage-multiple-client-keys-in-the-api-with-varying-permissions)
This PR is the sixth step (support rate limiting per client) towards supporting multiple, independent clients with their own API keys and roles:
----
- Enable per-client rate limit rules
Add a custom `ResolveContributor` that looks up the API client from their API key and sets the `clientId` to the `ApiKeyPrefix`.
Define custom rate limiting rules for `GIT` and `TTA` clients. 
Add development api keys for `GIT`/`TTA` in addition to `ADMIN`.
The `ADMIN` client has been white-listed and a set of default rate limits imposed on potentially exploitable endpoints.
Bumped the `AspNetCoreRateLimit` library.
This PR doesn't have test coverage as I've hit an issue with …
=> Enable rate limiting per API client service

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
[Trello-776](https://trello.com/c/HILK0xws/776-mailing-list-sign-up-process-for-crm-data-migration)
This PR deals with the first step of migrating existing candidates onto the new privacy policy via a mailing list sign up in the GiT app:
---
We currently only have one way of the API clients obtaining candidate data, which is by exchanging a user-generated access token for a resource (pre-filled mailing list/tta/event sign up):
```
POST /path/to/resource/{accessToken}
```
Going forward we are also going to support 'magic links' as a way of authenticating users. To that end, the endpoints are being refactored so we will ultimately be left with:
```
POST /path/to/resource/exchange_access_token/{accessToken}
POST /path/to/resource/exchange_magic_link_token/{magicLinkToken}
```
This PR adds in …
=> Refactor actions to exchange access tokens for candidate data

GetIntoTeachingApi/Auth/ApiClientHandler.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Auth/ApiClientHandlerTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
The two API clients now use the new authentication method and the legacy `SHARED_SECRET` environment variable is no longer used. This commit removes the associated authentication code.
=> Remove legacy shared secret authentication method

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
These access token endpoints have been replaced with new endpoints in the format `/path/to/resource/exchange_access_token/{accessToken}`. The API clients have been updated so they can safely be removed.
=> Remove deprecated access token endpoints

GetIntoTeachingApi/Attributes/EntityFieldAttribute.cs, GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Services/CandidateMagicLinkTokenService.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICandidateMagicLinkTokenService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Mocks/Models.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/MappingInfoTests.cs, GetIntoTeachingApiTests/Services/CandidateMagicLinkTokenServiceTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
[Trello-776](https://trello.com/c/HILK0xws/776-mailing-list-sign-up-process-for-crm-data-migration)
This PR deals with the second step of migrating existing candidates onto the new privacy policy via a mailing list sign up in the GiT app:
---
- Add magic link token fields to candidate
Add a field to store a magic link token against a candidate and the datetime that the token was created, so that we can enforce token expiry.
Only the token field itself is mapped to the CRM for now; the others will be mapped later on.
So that we can deploy this to production the `EntityFieldAttribute` has been updated with an `Transient` option. If set, the `BaseModel` will not map the fields to/from CRM `Entity` objects. This means we can safely deploy without the CRM having been updated to include the new …
=> Initial support for magic link tokens

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidateMagicLinkExchangeResult.cs, GetIntoTeachingApi/OperationFilters/AuthOperationFilter.cs, GetIntoTeachingApi/Services/CandidateMagicLinkTokenService.cs, GetIntoTeachingApi/Services/ICandidateMagicLinkTokenService.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Models/CandidateMagicLinkExchangeResultTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Services/CandidateMagicLinkTokenServiceTests.cs
[Trello-776](https://trello.com/c/HILK0xws/776-mailing-list-sign-up-process-for-crm-data-migration)
This PR deals with the third step of migrating existing candidates onto the new privacy policy via a mailing list sign up in the GiT app:
---
- Set expiry date on magic link tokens
Change the `createdAt` date to be `expiresAt` and set to 48 hours in the future when creating a magic link token.
Check that the token is valid before responding with a pre-filled `MailingListAddMember` model.
If the magic link could not be matched to a candidate (or if it matches to multiple candidates) we return `BadRequest` with a status of `Invalid`.
If a token was matched to a candidate but the expiry date has passed we return `BadRequest` with a status of `Expired`.
- Prevent multiple use of magic link …
=> Expire magic link tokens after 48hrs/first use

GetIntoTeachingApi/Startup.cs
Currently when an enum is returned the integer value is used. This seems to cause an issue with swagger-codegen spitting out invalid Ruby code, for example:
```
0 = 0.freeze
```
By serializing enums as string values I'm hoping it fixes the code generator.
We don't use enums in either of the client apps yet, so this change isn't breaking.
=> Serialize enums as strings

GetIntoTeachingApi/Attributes/EntityFieldAttribute.cs, GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApiTests/Mocks/Models.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs
We currently have a number of new fields that are available in the dev/test CRM environment but not production. In order to be able to deploy the code all the way to production before the attributes are available we need to ignore them from the mapping process.
Adds ability to exclude certain attributes from the mapping process depending on environment.
Excludes magic link attributes from being mapped in production (as they are not yet available).
=> Ignore model attribute mappings by environment

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
We are going to generate these in a background job that looks for all candidates with a `MagicLinkTokenStatusId` of `Pending` instead of having the CRM request candidates explicitly.
Also removes unused `GetCandidates` method on `ICrmService`.
=> Remove endpoint to create magic link tokens

GetIntoTeachingApi/Jobs/JobConfiguration.cs, GetIntoTeachingApi/Jobs/MagicLinkTokenGenerationJob.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Jobs/MagicLinkTokenGenerationJobTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs
[Trello-776](https://trello.com/c/HILK0xws/776-mailing-list-sign-up-process-for-crm-data-migration)
This PR deals with the fifth step of migrating existing candidates onto the new privacy policy via a mailing list sign up in the GiT app:
---
- Add metric to track MagicLinkTokenGenerationJob
The metric will enable us to track how long the metric link token generation is taken.
- Add method to retrieve candidates that require magic link tokens
When the CRM requires a magic link token to be generated for a candidate they will change the status to 'pending'. The API will then pick these up in a background job and assign tokens.
- Add job to generate magic link tokens
The job runs every minute and processes 1,000 candidates (we should be able to do a lot more than this if needed, but it's a …
=> Add job to generate magic link tokens

README.md
Details on how you can add a field that is only mapped in a subset of CRM environments. This is useful because the CRM team don't deploy to production all that often.
=> Add instructions on per-environment field mapping

monitoring/grafana/dashboards/get_into_teaching_api.json
The panels are empty at the moment as we haven't ran any generation jobs, but they are essentially the same format as the other two panels included in the screenshots.
=> Add panels for magic link generation/usage

.github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml
Two workflows that call .NET are no longer running, they fail to find the Notify NuGet provided by the UK Government, and they attempt to install some other old Notify NuGet
Replicated the fault in the workflows, but not on CLI or inside docker.
Some of the .NET steps in the workflow were using **sudo** and others were not. This until recently was not a problem, but something must have changed in the GitHub CI virtual environment and it became a problem. 
Remove the **sudo** command on all .NET functions
=> Fix build error in pipeline

GetIntoTeachingApi/Jobs/MagicLinkTokenGenerationJob.cs, GetIntoTeachingApiTests/Jobs/MagicLinkTokenGenerationJobTests.cs
On testing this in a hosted staging environment the job (and 1,000 spawned `UpsertCandidateJob` jobs) were completed in around 5 seconds. As we run this job periodically every minute we should be able to comfortably do 5,000 records/minute (we want to avoid the job overlapping itself by keeping the runtime < 1m - there is also a distributed lock on this job so if it does overlap the next run will wait/timeout).
=> Increase magic link token generation batch size

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs
I missed these originally as there was no test data in the CRM available, but we have it now so its highlighted theses issues.
- Share context when loading related entities
The candidate was being loaded in a different context to the related entities, which was causing an error (you can't relate entities across contexts).
- Persist candidate after exchanging magic link token
When the magic link token gets exchanged the candidate status is updated. We weren't persisting this back to the CRM, which meant tokens could be re-used until they expired (instead of being single use).
=> Minor bug fixes for magic link mechanism

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs
Updates the `Candidate` attribute mapping to map the magic link attributes in all environments, as they are now available in production.
Enables the magic link generation job in production.
=> Enable magic links in production

GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
If a candidate is already in the CRM the apps will now send existing data back with the sign up payload (which will mean we can ultimately write `nil` values to the CRM, as currently we have no way to differentiate between 'not set' and 'unset' fields).
A side-effect of this is that if an existing candidate is in the system with a degree type and then goes through the TTA as a returner a load of validation errors can occur due to the unexpected state (we don't ask new returners about their degree status). To avoid this we relax the validation around certain fields that trigger when the candidate has a degree - excluding  returners.
The validation is getting pretty complex now; it may be worth relaxing some of this in general in the API to avoid future problems, relying on the app-side …
=> Relex validation on returning teacher sign ups

GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/EmptyStringToNullJsonConverter.cs, GetIntoTeachingApiTests/Utils/EmptyStringToNullJsonConverterTests.cs
The CRM appears to have a number of existing candidates whereby the postcode is an empty string `""` instead of `null`. This means when we retrieve an existing record and pre-fill the store in the app we can hit a scenario where the user didn't specify a postcode but an invalid postcode (empty string) is sent back to the API.
By serialising/deserialising an empty string to `null` the behaviour will be correct and the postcode validation will not be applied.
=> Convert empty strings to null on serialize/deserialize operations

.github/workflows/manual.yml
[Release Notes are only first line](https://trello.com/c/Ueda1EDd/640-release-notes-are-only-first-line)
When SLACK outputs a Release Note, it only presents the first line of the text, this is not adequate
Change the github action to use Powershell and return a json string
No change to  application
=> Improve Release note

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Validators/PostcodeValidator.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Validators/PostcodeValidatorTests.cs
- Extract postcode validation into property validator
Initially I did this so that I could re-use it in the request models, but FluentValidation doesn't let you validate a single value (only an entire model).
It's a worthwhile refactoring anyway, so leaving it in.
- Sanitize invalid postcodes coming back from the CRM
We have a potential scenario where an candidate in the CRM has an invalid postcode against them; if we use their data when pre-filling one of the forms in the front-end apps this postcode will then be re-submitted to the API and it will fail validation (the data is only validated on the client-side if shown to the user and postcodes are often optional/skipped steps).
This commit updates the API to sanitize invalid postcodes coming back from the CRM.
=> Sanitize invalid CRM postcodes

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/JsonConverters/EmptyStringToNullJsonConverter.cs, GetIntoTeachingApi/JsonConverters/TrimStringJsonConverter.cs, GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/JsonConverters/EmptyStringToNullJsonConverterTests.cs, GetIntoTeachingApiTests/JsonConverters/TrimStringJsonConverterTests.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs
- Move existing json converter into subdir
We're going to have a couple of these and they aren't really utility classes anyway, so better off in their own folder.
- Add TrimStringJsonConverter
We have seen a few cases where the CRM has returned a postcode with a stray space at the start or end. If the candidate matches-back and the postcode is optional we will skip that step in the front-end and re-post the invalid postcode back to the API, at which point the submission fails validation.
This converter will ensure all string values are trimmed of white space when they exit/enter the API.
- Trim strings coming back from the CRM
Some string values in the CRM have leading/trailing white space; this can be an issue if they get ran through a strict validator (such as the postcode validator). …
=> Trim/nullify empty strings coming into/out of the API

GetIntoTeachingApi/Adapters/CdsServiceClientWrapper.cs, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Helpers/DatabaseFixture.cs, GetIntoTeachingApiTests/Helpers/GitWebApplicationFactory.cs, GetIntoTeachingApiTests/Integration/RateLimitTests.cs
- Update Startup to enable app to boot in test env
When trying to boot the application in the test environment there were a few things preventing the application from successfully starting (which we need to be able to do integration testing):
1. The `CdsServiceClient` is unable to connect (we now support running without the client, though it will crash if mocking is absent).
2. The database was not being configured for test (we can now connect to the test DB running in docker).
3. `Program` is not ran by `WebApplicationFactory` (code now shifted to be in the `Startup.Configure` instead, which gets run).
- Add WebApplicationFactory to run app in test env
The WebApplicationFactory allows us to boot an instance of the application running in the test environment and re-configure services that …
=> Add test coverage to client-level rate limits

GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs
This was added when we were integrating Sentry initially to sanity check that it was working in all environments. Removing it as it could leave us open to someone abusing the endpoint and eating up our quota (the operations endpoints aren't behind authentication).
=> Remove action to simulate an error

GetIntoTeachingApi/Startup.cs
In some environments we check the database state before queueing jobs; previously we were migrating the database _after_ this check, which throws an exception if the database is empty (in need of the first migration being ran).
Moving the call to migrate the database earlier ensures it is ready in time.
=> Run DB migration earlier in startup

GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs
Currently the `TypeId` of a `Candidate` is inferred based on if any past teaching positions are present. Instead, we can explicitly pass this from the client in response to the "Are you returning to teaching?" question. This will have two benefits:
- We can then pre-fill this question on matchback
- We can use `TypeId` going forward to determine if a candidate is  returning to   teaching
Initially this is being added as an optional field; once the TTA service has been updated we can add validation to ensure it is always present and remove the code to infer the type.
=> Support explicitly setting the type on the sign up request model

GetIntoTeachingApi/Auth/ApiClientHandler.cs, GetIntoTeachingApiTests/Auth/ApiClientHandlerTests.cs
Some actions in the API don't require authentication (such as the health-check). Currently, if a request doesn't contain an `Authorization` header we return `AuthenticateResult.Failure` which marks the request as unauthorized _and_ logs out an error.
Instead, we should be returning `Authenticate.NoResult` if the request can't be authenticated due to missing `Authorization` header, which still results in a 401 unauthorized but prevents logging an error (we return `AuthenticateResult.Failure` when the header is present but the API key is invalid, which is when the error logging is useful).
Removes manual logging as ASP.NET Core will log out the failure anyway, so we were seeing duplicate log lines.
=> Return NoResult instead of Failure when Authorization header missing

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs, GetIntoTeachingApiTests/Services/SubscriptionManagerTests.cs
Until recently determining if a candidate was returning to teaching (vs interested in teaching) involved checking the `Candidate` model for `PastTeachingPosition` or checking the `TeacherTrainingAdviserSignUp` model for a `SubjectTaughtId`. This isn't very intuitive and the CRM actually stores a `TypeId` that tells us if the candidate is a returner. Now that the TTA service explicitly sends the `TypeId` we can consolidate and simplify how we determine if a `Candidate` is a returner.
- Make TypeId required on TeacherTrainingAdviserSignUp
The TTA app has been updated to send a `type_id` with all requests now, so we can mark this as required and remove the inferred logic around candidate type.
- Stop inferring candidate type in TeacherTrainingAdviserSignUp
This is now passed explicitly from …
=> Stop inferring returning teacher status from other attributes

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
- Re-structure the TTA sign up validation
By nesting the rules it makes the validator easier to read.
Add `IsInterestedInTeaching` helper to `Candidate` for convenience.
Tests left largely unchanged.
- Clean up TeacherTrainingAdviserSignUpValidatorTests
Refactors the tests to be more readable and groups them into two main classes for returning to teacher training and interested in teacher training.
=> Clean up TeacherTrainingAdviserSignUpValidator/Tests

terraform/paas/data.tf, terraform/paas/monitoring.tf
Added Google-sheets as a data source, this allows the service account to
make spreadsheets available to grafana. allowing for data to be ingested
from static sources
=> Added Google-sheets Data Source

GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApi/Models/CallbackBookingQuota.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApi/Models/PrivacyPolicy.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Models/TeachingEventBuilding.cs, GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApi/Models/Validators/CandidatePastTeachingPositionValidator.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/PhoneCallValidator.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Mocks/Models.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidatePastTeachingPositionValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/PhoneCallValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, README.md
The CRM may contain invalid data as their validation is not as stringent/complete as the API's. If we map an invalid field to a model that is used for matching back a candidate and that model gets re-posted to the API on form submission it will fail the validation (this can happen as optional fields are skipped in the front-end clients so the data will not be sanitized/validated until the API receives it).
We manually check the candidate postcode to validate it, but it would be better to auto-load the validator for the model being mapped to and running validation after the mapping process has completed. If a property fails validation we should nullify it.
- Remove manually clearing of invalid candidate postcodes
We're going to start doing this automatically using the existing model …
=> Validate CRM responses when mapping to BaseModel subclasses

monitoring/grafana/dashboards/resources.json
Added a new Grafana Chart that compares CPU/MEMORY with User Activity.
This PR does not effect the operation or delivery of the API
=> New Chart to add resource display

GetIntoTeachingApi/Models/BaseModel.cs
We added change tracking to only write changed attributes back to the CRM. The issue with related objects is that the attribute is instantiated as a collection and the collection is mutated rather than the attribute itself changing. This was causing related models not being written back to the CRM.
Removing the check for if a value has changed will cause it to revert to the old behaviour of always writing the attributes back to the CRM. This should be fine for collections just now; if we get a use case in the future where we need to support only writing changed collection items back to the CRM we can tackle it then.
=> Ignore change tracking on relationships

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Jobs/MagicLinkTokenGenerationJob.cs, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Mocks/MockModel.cs, GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/JsonExtensions.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Jobs/MagicLinkTokenGenerationJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs
Hangfire uses Newtonsoft.Json by default and it turns out this wasn't deserializing payloads with change tracking information correctly - this PR swaps it out for System.Text.Json and makes some updates to ensure this is deserializing consistently.
Also marks properties defined with a value as changed on initialisation, as we do this for default values in models and they were being missed/skipped over.
- Remove custom Newtonsoft.Json deserialization logic
We're going to manually serialize/deserialize the Hangfire payloads using the default System.Text.Json serializer used in the rest of the app, instead of relying on Newtonsoft.Json that Hangfire uses by default (it appears to be buggy around deserializing the `ChangedPropertyNames` attribute of nested models).
- Mark properties defined …
=> Manually serialize Hangfire payloads

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs
[Trello-1352](https://trello.com/c/wAptzepa/1352-spike-review-the-radius-of-the-events-finder-to-10-miles-30-miles-50-miles)
We are thinking about tweaking the event search radius select options in the GiT app from the current options of 30/50/100 miles to see if users engage better with different search radii. Before we change it, we want to understand how users are interacting with the search in terms of which radius they select and how many results they receive in their search.
To enable this, we are adding a new histogram metric that observes event search results with labels for type and radius; this should give insight into how the different types of searches are performing.
=> Record metrics on event search results

GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Redis/RedisConfiguration.cs, GetIntoTeachingApi/Redis/RedisRateLimitCounterStore.cs, GetIntoTeachingApiTests/Helpers/DatabaseFixture.cs
We still use Newtonsoft.Json in a couple of places; ideally we want to use System.Text.Json everywhere so we only have the one Json serializer; this updates the remaining places.
Updates integers in JSON fixtures to be without quotes as System.Text.Json is stricter than Newtonsoft.Json (the VCAP_SERVICES has them without quotes in cloud foundry so this change shouldn't effect the environments).
=> Swap Newtonsoft.Json to System.Text.Json

monitoring/grafana/dashboards/get_into_teaching_api.json
Add single stat panels that group searches by the number of results returned and search radius used.
I’m only including results where the user didn’t search by a type (as I figured that could skew the number of results they get quite heavily). I think I need to tweak the histogram buckets as well to expand on >10 as the majority of searches fall into that bucket and I don't think we'll ever see 0 results (or even <6 very often) as we always include online events.
=> Add panel showing event search results by search radius

GetIntoTeachingApi/Adapters/GeocodeClientAdapter.cs, GetIntoTeachingApi/Services/CandidateAccessTokenService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApiTests/Services/CandidateAccessTokenServiceTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs, monitoring/grafana/dashboards/get_into_teaching_api.json
- Remove high cardinality metric labels
It turns out that using high cardinality labels against metrics is bad as each combination is recorded as its own time-series, which is expensive (lots of different label values == lots of different time series).
We do this in a couple of metrics and for the most part the labels aren't actually used when it comes to graphing or alerting on the metrics, so this commit removes them.
- Remove panel using high-cardinality label
The Google requests by postcode panel is operating on a metric with a high cardinality label (postcode, which has a lot of values). Removing it as this impacts performance; the data is still sent to the logs.
=> Optimise metrics by removing high-cardinality labels

GetIntoTeachingApi/Models/Location.cs, GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Utils/ApplicationExtensions.cs, GetIntoTeachingApi/Utils/StringExtensions.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Utils/StringExtensionsTests.cs
- Rename extension for clarity
- Add StringExtensions for formatting postcodes
The extension will take a valid postcode and ensure it is formatted correctly (upper case and with a space before the inward part of the postcode).
- Format postcodes from request models
When a postcode comes into the API we want to format it before it gets to the CRM; this adds formatting when mapping from the request models to a `Candidate`.
=> Format postcodes before sending to the API

monitoring/grafana/dashboards/get_into_teaching_api.json, monitoring/grafana/dashboards/get_into_teaching_api_event_search.json
Adds an event search dashboard (and removes the event search panels from the main API dashboard):
=> Add event search dashboard

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/JsonExtensions.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs, README.md
In an ideal world we would use `System.Text.Json` for all serialization in the API. Whilst we got to this state recently it has a few drawbacks:
1. Dahomey.Json extensions are required to pause change tracking during se/deserialization. This brings various oddities into `System.Text.Json` and it doesn't implement `System.Runtime.Serialization.OnDeserializing/OnDeserialized` according to the spec (it misses the `StreamingContext` argument, which can have knock on effects). It also brings in `AutoMapper` which is slow and in general it's difficult to follow code, making it iffy to rely on.
2. `System.Text.Json` doesn't support conditional serialization, meaning we can't omit the `ChangedPropertyNames` attribute from API responses and include them when serializing to Hangfire -- we have to …
=> Use Newtonsoft.Json for Hangfire payloads

GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberValidatorTests.cs
- Remove telephone from MailingListAddMember
We haven't collected the telephone in the mailing list sign up for a while now, but it's still available as an attribute in the mailing list sign up. This removes it to make it consistent.
=> Remove telephone from MailingListAddMember

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs, monitoring/grafana/dashboards/get_into_teaching_api_event_search.json
- Collect metric on in person event result counts
When a teaching event search is performed we want to know how many in-person events are returned (as well as total events, including online).
Add a second metric that observes how many in-person events are returned in a search result.
Add convenience method to `TeachingEvent` to determine if it is `InPerson`.
- Update event search dashboard to show in-person results
We are interested in how many in-person event results are returned on radius searches (as online events are always returned, skewing the data we're interested in).
=> Record in-person event search result metrics

GetIntoTeachingApi/Controllers/CallbackBookingQuotasController.cs, GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/LookupItemsController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApi/Controllers/PickListItemsController.cs, GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs
Use AspNetCore.Http.StatusCodes for action annotations to clean up/provide some context to the return types
=> Update action return types to use AspNetCore.Http.StatusCodes

GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Jobs/MagicLinkTokenGenerationJob.cs, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Utils/JsonExtensions.cs, GetIntoTeachingApiTests/Controllers/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Jobs/MagicLinkTokenGenerationJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs, GetIntoTeachingApiTests/Utils/JsonExtensionsTests.cs, README.md
By default `System.Text.Json` serializes attribute names to `camelCase` and `Newtonsoft.Json` will match the casing of the attribute being serialized (`PascalCase` for C# attributes).
Making these consistent will mean that we only have to check for property names in a single case when redacting sensitive data (otherwise we would have to check `firstName` and `FirstName`, for example).
`Newtonsoft.Json` will deserialize both camel and pascal case by default, so the existing jobs in the queue will still deserialize and process fine.
Fixes a typo in `Se/DeserializeChangeTracked` extension methods.
Extracts Json serialization tests out of `BaseModel` and into `JsonExtensionsTests`, which makes more sense.
=> Serialize attribute names to camelCase instead of PascalCase

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Middleware/RequestResponseLoggingMiddleware.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Redactor.cs, GetIntoTeachingApi/Utils/RequestResponseLoggingMiddlewareExtensions.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Middleware/RequestResponseLoggingMiddlewareTests.cs, GetIntoTeachingApiTests/Utils/RedactorTests.cs, README.md
- Add utilty class to redact sensitive data from JSON
We want to be able to log out the request/response bodies and Hangfire job paylaods to aid in debugging when something goes wrong. While doing this we need to ensure no personally identifiable information is sent to our logstash.
Add a `Redactor` utility class that redacts sensitive data (identified by payload keys) from JSON.
Update README to explain why we have to use Newtonsoft.Json for this.
- Log out request/response payloads
Add middleware that intercepts request/response payloads, redacts sensitive data and them logs the request information.
So as not to upset other middleware in the chain the request/response body streams are copied and rewound. `RecyclableMemoryStreamManager` is used for performance/to avoid memory leaks. …
=> Improved request/response and job payload logging

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Startup.cs
We want to be able to track a request from a client as it moves through the API and various log messages are created.
Add `CorrelationId` library that will automatically consume an incoming request ID (from the `X-Request-ID` header, which is the Rails default) and attach it to the scope of any log messages that the API writes.
If an `X-Request-Id` is not present then the library will generate a new one in the form of a GUID.
=> Attach correlation IDs to logs

GetIntoTeachingApi/Controllers/TeachingEventBuildingsController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/LookupItemsControllerTests.cs, GetIntoTeachingApiTests/Controllers/PickListItemsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventBuildingsControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
A new form will be added to the app to allow Abramis to add teaching events, part of this form needs to produce a list of teaching event buildings. Currently, the API only retrieves buildings that are associated with an event.
This PR:
- Adds a new endpoint to get all buildings from the CMS.
- Updates the CMS/postgres sync to:
- get events without their associated buildings from the CMS.
- get all buildings before associating them with events via BuildingId.
=> Teaching event buildings

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Startup.cs
Reverts DFE-Digital/get-into-teaching-api#545
It turns out asp.net core 3 has support for correlation ids built in (following the [W3C Trace Context](https://www.w3.org/TR/trace-context/) standard); if we set a request header `traceparent` or `Request-Id` with the request id from the Rails apps it will automagically be attached to the log scope of all the log messages from the API.
=> Revert "Attach correlation IDs to logs"

monitoring/grafana/dashboards/get_into_teaching_api_event_search.json
The search radius values have changed to no radius/15 miles/25 miles.
Update the panels to match the new radius values.
PR to tweak the radius options in the app: https://github.com/DFE-Digital/get-into-teaching-app/pull/991
=> Update search radius to match new values

GetIntoTeachingApi/Controllers/TeachingEventBuildingsController.cs
The ProducesResponseType annotation must be correct for Swagger Codegen to correctly generate the API library
=> Fix Swagger annotation

.github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml, Dockerfile, GetIntoTeachingApi/GetIntoTeachingApi.csproj, README.md
The library was previously hosted on bintray.com, but that will be deprecated on May 1st and the team have moved the latest version to nuget.org.
Update to use latest version on nuget.org.
I got a build warning due to GovUKNotify depending on JWT >= 7.0.0 and < 8.0.0, but v7.0.0 was not found (as there is no v7.0.0) - installing an applicable version manually resolves the warning.
=> Update Gov UK Notify library

GetIntoTeachingApi/Migrations/20210322100102_AddImageUrlAndProvidersListToTeachingEvent.Designer.cs, GetIntoTeachingApi/Migrations/20210322100102_AddImageUrlAndProvidersListToTeachingEvent.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Models/TeachingEventBuilding.cs, GetIntoTeachingApiTests/Models/TeachingEventBuildingTests.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs
[Trello-1440](https://trello.com/c/iydAl0Dm/1440-test-and-implement-ability-to-render-bullet-point-list-of-providers-for-ttt-events)
We want to display a list of providers on the TTT events and event buildings will optionally have an image URL that we can display as well.
=> Add new fields to event/building

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Models/Validators/TeachingEventValidator.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventValidatorTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
A new form will be added to the app to add teaching events. As part of this, teaching events should be able to be updated, so that their `status` can be changed.
This PR:
- Adds a new status to teaching event
- Updates the name and description of the teaching event add/update endpoint
- Update teaching event add/update endpoint to immediately cache building so that it can be retrieved straight away before sync
- Saves building in CRM separately so that it returns an ID.
- Caches event and building, so that they are immediately available
=> Update teaching event

GetIntoTeachingApi/Models/Validators/TeachingEventValidator.cs
Receiving a syntax error in the validator regex when generating the client gem. Updating the validator to prevent this.
=> Update email validator

GetIntoTeachingApi/Models/Validators/TeachingEventValidator.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventValidatorTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Add model error to the API response when the CRM has a validation error for non-unique partial URL
=> Handle non-unique partial URL

GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Helpers/DatabaseFixture.cs, GetIntoTeachingApiTests/Helpers/DatabaseTests.cs, GetIntoTeachingApiTests/Integration/RateLimitTests.cs
[Trello-1458](https://trello.com/c/CgUPWYjx/1458-contract-testing-spike)
To set up contract testing in the API we need to fix a couple of issues with the test environment when running integration tests:
- Don't run recurring jobs in test environment
We will be manually seeding the data in the test environment and not talking to the CRM, so halting the jobs makes sense.
- Point integration tests at per-test database
Previously the integration tests were pointing to `gis_test`, which is the template database we clone per-test.
Instead, we want the integration tests to point at the cloned database that is cleaned up once the test has finished.
- Fix flakey rate limit specs
Now the integration tests point at a per-test database it highlights a flakey spec. The rate limit tests were re-using …
=> Fix test environment for integration tests

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApi/Fixtures/clients.yml, GetIntoTeachingApi/Jobs/CrmSyncJob.cs, GetIntoTeachingApi/Jobs/MagicLinkTokenGenerationJob.cs, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Models/AppSettings.cs, GetIntoTeachingApi/Models/HealthCheckResponse.cs, GetIntoTeachingApi/Models/IAppSettings.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/IRedisService.cs, GetIntoTeachingApi/Services/RedisService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Jobs/CrmSyncJobTests.cs, GetIntoTeachingApiTests/Jobs/MagicLinkTokenGenerationJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Models/AppSettingsTests.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
[Trello-1426](https://trello.com/c/ByTdLhsq/1426-add-endpoint-for-crm-team-to-call-when-they-are-doing-an-update-with-downtime)
The CRM is often taken offline for a short time when the CRM team perform a production update. This results in a flurry of errors from the API that - whilst not effecting end users - is creating noise in our error monitoring for something we can do nothing about.
To avoid this we want to add a mechanism for the CRM team to inform the API that they are taking the CRM offline. The API can then avoid calling the CRM whilst its unavailable and the errors will stop.
- Add AppSettings model
We want to be able to flag the CRM as unavailable when it has been intentionally taken offline by the CRM team (for an update, for example).
Storing this in Postgres felt like …
=> Add mechanism to pause/resume the CRM integration

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Update events and buildings in cache, so that they are available immediately when updated.
=> Save teaching event/building independently

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs
When the CRM teaching event sync runs, it checks for a `buildingId`, if one isn't present, it does not attach a building to that event. 
This explicitly sets `buildingId` for posted events before adding them to the CRM.
=> Set buildingId before saving in CRM

GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs
Previously we were not establishing a link between an entity and an existing entity; this was to avoid the scenario whereby, for example, a candidate is created with a qualification and later updated. I was under the impression re-linking an existing entity (in this case the existing qualification) would result in a duplicate relationship. This is not the case and it turns out its safe to re-link existing entities.
It also has the benefit of being able to link new entities to existing entities. This is required for the work to create teaching events; some will be associated with existing buildings and with the code as it was before the link was not being established.
=> Establish link for existing entities

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs
The teaching events were not being linked to the correct building as the `TeachingEvent.BuildingId` field was not being mapped from the CRM entity (this is then used to establish the relationship before persisting the event).
Update to map the `BuildingId` so it gets populated correctly and the building gets linked.
=> Fix TeachingEvent not linking to Buildings

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs
The CRM reference for the `TeachingEvent.BuildingId` was incorrectly set, which was causing mapping errors when serialising to a Dynamics entity. This commit corrects the reference, fixing the error.
=> Correct TeachingEvent.BuildingId CRM reference

GetIntoTeachingApi/Jobs/CrmSyncJob.cs, GetIntoTeachingApi/Jobs/MagicLinkTokenGenerationJob.cs
We lock jobs that shouldn't run asynchronously; we've been using quite long lock timeouts and I believe this results in jobs (mainly the CrmSyncJob) taking forever to run locally after restarting your instance; the new job waits for the job that was killed to timeout. Reducing the timeout duration should speed things up locally and a 60s duration should be plenty for both jobs to complete (they both complete in under 10 seconds usually).
=> Reduce job lock durations

monitoring/prometheus/alert.rules
As we up the rollout % for public beta we're seeing a few more of these; its largely bots poking about, so upping the threshold to quieten them.
=> Increase HighNotFound threshold

GetIntoTeachingApi/Models/Validators/TeachingEventValidator.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventValidatorTests.cs
We want new events to be dated in the future, but existing/past events are still valid (as we show an archive of online events).
With this validation in place the event.StartAt was failing the validation criteria during mapping and being nullified, which results in the earliest `DateTime` value by default. We would be better checking that the type accepts a `null` value in the mapping operation to avoid this in the future.
=> Remove event start at greater than now validation criteria

monitoring/grafana/dashboards/app_page_insights.json
Add dashboard to display page insights for each category (performance, seo, accessibility). These are updated daily at 8am by a GitHub action.
Includes the avg/max/min by strategy as well as scores per page (for finding poor scoring pages easily) and the avg score over time.
=> Add dashboard for app page insights

monitoring/prometheus/alert.rules
I'm not sure why this has started firing but its not critical; removing until we can debug it on Monday.
=> Remove GoogleApiErrors alert

monitoring/prometheus/alert.rules
Reverts DFE-Digital/get-into-teaching-api#582 - the offending building has been removed from dev so we should be good to re-instate this. I'm also going to look at caching postcode lookup failures so we don't keep hitting Google.
=> Revert "Remove GoogleApiErrors alert"

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs
Teaching Events have an `Event name` in the CRM (See left column of image below), and an `External event title` (`TeachingEvent.Name` in the API)
When adding a Teaching Event, the `Event name` should be set to equal the `External event title`. This will allow the CRM team to work with the events more easily (e.g. searching events will be easier)
=> Add crm name teaching event

GetIntoTeachingApi/Models/Validators/TeachingEventValidator.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventValidatorTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
The `ReadableId` of a teaching event is validated to ensure that it is unique.
Currently, validation for the `ReadableId` of an existing event will be skipped because of the `When` check in the validator. This means that if the event is updated to have an existing `ReadableId` (in this situation the event will have a `Id` and non-unique `ReadableId`), then the event will try to save in the CRM and throw a `Microsoft.Xrm.Sdk.SaveChangesException`
This PR updates the validator to also validate events which do exist (have an `id`), but have a new `readableId`
=> Only validate readableId of existing event when it has changed

monitoring/grafana/dashboards/service_feedback.json
Add a simple dashboard to display the service rating and successful visit metrics.
=> Add TTA service feedback dashboard

monitoring/prometheus/alert.rules
Add the condition to prevent development and test alerts from being raised for memory and disk usage
=> Restrict Alerts to Production

GetIntoTeachingApi/Models/Validators/TeachingEventValidator.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventValidatorTests.cs
We're seeing errors in the rolling environment where we think the validator gets stuck in a loop and results in a stack overflow, causing the instance to run out of memory.
Reverting this validation check for now until we can debug it further offline.
=> Remove unique readable id validation

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/TeachingEventUpsertOperation.cs, GetIntoTeachingApi/Models/Validators/TeachingEventUpsertOperationValidator.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/TeachingEventUpsertOperationTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventUpsertOperationValidatorTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Validating the `ReadableId` during the sync is expensive (as we have to query the CRM for each event to ensure uniqueness). Instead, we can assume that the events coming back from the CRM have a unique `ReadableId` and we only need to perform the validation when we are adding or updating an event via the app/API.
=> Only validate ReadableId on upsert action

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs
Feedback from the CRM team is that all created teaching events should have a time zone property with the value 85 which represents GMT.
=> Add CRM time zone property

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
When we check for duplicate `ReadableId` values we end up returning a `BadRequest(ModelState)` if there is a duplicate, which results in a response in the format:
```
{
"ReadableId": "'Readable Id' must be unique."
}
```
This is because the validation is performed manually/explicitly. Instead, we want to use the default error response format (which is used for all our other, automated validators by default) defined in an `InvalidModelStateResponseFactory` as part of the `ApiBehaviorOptions`:
```
{
"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
"title": "One or more validation errors occurred.",
"status": 400,
"traceId": "|b0171620-4495860d4208836f.",
"errors": {
"ReadableId": [
"'Readable Id' must be unique."
]
}
}
```
=> Make error response format consistent on manual validation

GetIntoTeachingApi/Adapters/GeocodeClientAdapter.cs
When we receive a metric alert for Google API error responses its difficult to find the postcode thats been used. As postcodes are not personally identifiable we can log them out to make debugging easier.
=> Log postcode when we query Google Geocoding API

monitoring/prometheus/alert.rules
We're seeing an increase in bots crawling the website and hitting junk endpoints; increasing the HighNotFound threshold from 30 to 60 in a 10 minute period should reduce the noise.
=> Increase HighNotFound alert threshold

GetIntoTeachingApi/Services/Store.cs
Using non-tracking queries for read-only scenarios can result in significant performance improvements.
=> Update read-only queries to non-tracking

GetIntoTeachingApi/Middleware/IRequestResponseLoggingConfiguration.cs, GetIntoTeachingApi/Middleware/RequestResponseLoggingConfiguration.cs, GetIntoTeachingApi/Middleware/RequestResponseLoggingMiddleware.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Middleware/RequestResponseLoggingConfigurationTests.cs, GetIntoTeachingApiTests/Middleware/RequestResponseLoggingMiddlewareTests.cs
[Trello-1530](https://trello.com/c/m8LU4RBK/1530-logitio-stack)
Currently we enable request/response logging for all API endpoints, however some of these endpoints return quite a lot of not necessarily all that useful information when it comes to debugging issues. Its mainly the POST/PUT request/response payloads that we want to log out (but not exclusively - there are some GET request payloads like the health check that are useful).
Add support for configuring the `RequestResponseLoggingMiddleware` with a set of `CompactLoggingPattern`s - any request/response that matches a compact regex pattern will not have its payload included in the log.
=> Support compact logging of verbose requests/responses

GetIntoTeachingApi/Fixtures/clients.yml, GetIntoTeachingApi/Models/Validators/ClientValidator.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Integration/RateLimitTests.cs, GetIntoTeachingApiTests/Models/Validators/ClientValidatorTests.cs
We are going to transition the SE application to use the GiT API instead of interfacing with Dynamics directly. This will enable the SE Rails app to connect to the API using its own set of credentials.
=> Add Schools Experience API client

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Utils/Redactor.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs
We are integrating the Candidate modelling for Schools Experience into the API, which references 3 different telephone fields (address_telephone, telephone1, telephone2). To make the naming more consistent we are renaming `Candidate.Telephone` to `Candidate.AddressTelephone` and this will then allow `Candidate.Telephone` and `Candidate.SecondaryTelephone` to reference the telephone1/2 fields that are being introduced.
The request models are backwards-compatible, accepting both `Telephone` and `AddressTelephone`; once the API clients have been updated the `Telephone` attribute can be removed from the request models.
=> Rename Telephone to AddressTelephone

GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs
We are migrating to AddressTelephone from the original Telephone field, this updates the validator to accept both, which was missed in the original PR. I've not included tests as this code will be updated again as soon as the clients are up to date (accepting only AddressTelephone going forwards).
=> Accept Telephone or AddressTelephone

GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventAddAttendeeValidatorTests.cs
We have updated the clients to reference the new `AddressTelephone` field, so the original `Telephone` field can now be removed.
=> Remove the `Telephone` field from request models

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/ClassroomExperienceNote.cs, GetIntoTeachingApi/Models/MailingListAddMember.cs, GetIntoTeachingApi/Models/SchoolsExperienceSignUp.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/ClassroomExperienceNoteValidator.cs, GetIntoTeachingApi/Models/Validators/SchoolsExperienceSignUpValidator.cs, GetIntoTeachingApi/Utils/Redactor.cs, GetIntoTeachingApi/Utils/StringExtensions.cs, GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Integration/RateLimitTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/ClassroomExperienceNoteTests.cs, GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperienceSignUpTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/ClassroomExperienceNoteValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/SchoolsExperienceSignUpValidatorTests.cs, GetIntoTeachingApiTests/Utils/StringExtensionsTests.cs
[Trello-66](https://trello.com/c/ETWHyQJu/66-implement-api-endpoints-for-se)
This is the first pass at adding support for the Schools Experience service to the API; it will likely change as we start to integrate the API client into the service, but it should cover the main scenarios and data set used by SE. Best reviewed by-commit.
- Add Schools Experience fields to Candidate model
For the most part the Schools Experience application uses a subset of the fields already used by the Get into Teaching apps.
There are, however, a small number of new fields that needed adding:
```
- AddressLine3
- AddressStateOrProvince
- SecondaryEmail
- Telephone
- SecondaryTelephone
- MobileTelephone
- HasDbsCertificate
- DbsCertificateIssuedAt
- SecondaryPreferredTeachingSubjectId
```
- Support matchback …
=> Add initial support for Schools Experience service

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs
I missed this in the original PR that added the SE client to the API; we need to be able to issue verification codes from the service to perform a matchback.
=> Enable SchoolsExperience to issue verification codes

GetIntoTeachingApi/Models/SchoolsExperienceSignUp.cs, GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/Validators/SchoolsExperienceSignUpValidator.cs, GetIntoTeachingApiTests/Models/SchoolsExperienceSignUpTests.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/SchoolsExperienceSignUpValidatorTests.cs
- Default country to UK for SE sign up
We only appear to accept sign ups to the Schools Experience service from UK candidates. Currently the country is set as an environment variable in the Rails app, but its easier to default this in the API.
- Default secondary email/telephone on SE sign up
The Rails app has logic in it to default the secondary telephone/email when pre-filling for form; this replicates the logic in the API so we can remove it from the app.
- Remove validation on DBS certificate date
In the SE app the DBS certificate issued at date is cleared when the `HasDbsCertificate` field is changed; this means it could be `true` and not have a date of issue, so we should remove this validation check.
=> Minor tweaks for Schools Experience

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Services/CandidateUpserter.cs, GetIntoTeachingApi/Services/ICandidateUpserter.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Helpers/DatabaseFixture.cs, GetIntoTeachingApiTests/Helpers/DatabaseTests.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs, docker-compose.yml
- Update docker-compose ports
I often run the API along side another Rails app locally and the ports clash; changing this so I can keep both apps running locally at the same time.
- Extract upsert logic into CandidateUpserter service
We need to be able to call the upsert operation from outside a job for the Schools Experience service (as it requires an immediate response from the CRM with the candidate GUID in).
Extract the upsert logic into a new service that can be called independently.
- Update SE upsert operation to be synchronous
Instead of queueing the job to upsert a candidate we need to be able to return the newly created candidate (with an ID) to the Schools Experience service.
This means the service will be unavailable when the CRM is offline, but that is the case currently …
=> Change SchoolsExperience upsert to be synchronous

GetIntoTeachingApi/Models/Validators/SchoolsExperienceSignUpValidator.cs, GetIntoTeachingApiTests/Models/Validators/SchoolsExperienceSignUpValidatorTests.cs
The candidate does not have to provide this in the sign up form, so making it optional.
=> Make SecondaryPreferredTeachingSubjectId optional

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs
The return type needs to be specified for the Swagger client to generate correctly. It should also have been a `SchoolsExperienceSignUp` and not a `Candidate`.
=> Fix return type of SE upsert method

GetIntoTeachingApi/Controllers/TeachingEventsController.cs
When SwaggerGen is generating the client library, it is expecting a teaching event to be in a hash with a body key for upsert_teaching_event.
This is an attempt to fix that. The other post actions in the API are annotated SwaggerRequestBody.
=> Add SwaggerRequestBody annotation

GetIntoTeachingApi/Models/Validators/ClassroomExperienceNoteValidator.cs
The swagger-codegen is creating an invalid Regex in the client, so swapping this validator out to check an array of explicit strings instead.
=> Validate against array of strings instead of regex

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Part of the Schools Experience code appears to batch-update contacts, so we need to provide a method to retrieve details for multiple candidates at once.
=> Support retrieving multiple SE sign ups

GetIntoTeachingApi/Models/SchoolsExperienceSignUp.cs, GetIntoTeachingApiTests/Models/SchoolsExperienceSignUpTests.cs
The SE codebase references `contact.full_name` frequently; instead of adding a helper and replacing a bunch of occurrences its going to be a lighter-touch to expose the full name in the API model and that way the existing references will just work.
=> Add FullName property to SE sign up

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/SchoolsExperienceSignUp.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperienceSignUpTests.cs
The SE app uses the master id to traverse contacts until it finds the 'master' record. Ideally this logic would be deferred to the API, but to make the migration easier I'm exposing it so we can continue to do it in the Rails app for now.
=> Expose MasterId for SchoolsExperienceSignUp

GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/SchoolsExperienceSignUp.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperienceSignUpTests.cs
Indicates if the contact record has been merged and should have a `masterId`. I didn't think we'd need this as well as `masterId` but the client app references both, so putting it in to make the migration easier.
=> Add merged attribute to SchoolsExperienceSignUp

GetIntoTeachingApi/Models/ClassroomExperienceNote.cs, GetIntoTeachingApi/Models/Validators/ClassroomExperienceNoteValidator.cs, GetIntoTeachingApiTests/Models/ClassroomExperienceNoteTests.cs, GetIntoTeachingApiTests/Models/Validators/ClassroomExperienceNoteValidatorTests.cs
The `Date` attribute is not alwasy specified by the client.
Also updates the `SchoolUrn` to be nullable but required, which should prevent swagger-codegen from marking it as `[Optional]`.
=> Make date optional in ClassroomExperienceNote

GetIntoTeachingApi/Attributes/CommaSeparatedAttribute.cs, GetIntoTeachingApi/Attributes/CommaSeparatedQueryStringAttribute.cs, GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/CommaSeparatedQueryStringConvention.cs, GetIntoTeachingApi/Utils/CommaSeparatedQueryStringValueProvider.cs, GetIntoTeachingApi/Utils/CommaSeparatedQueryStringValueProviderFactory.cs, GetIntoTeachingApiTests/Utils/CommaSeparatedQueryStringValueProviderFactoryTests.cs, GetIntoTeachingApiTests/Utils/CommaSeparatedQueryStringValueProviderTests.cs
By default ASP.NET Core expects `FromQuery` parameters of a collection type to be expressed in the format:
```
GET /items?key=value1&key=value2
```
Swagger UI and SwaggerCodegen, however, create code that results in the query parameters in the format:
```
GET /items?key=value1,value2
```
As it doesn't appear possible to customise Swagger UI/SwaggerCodegen in this respect, this commit instead updates ASP.NET Core with a `CommaSeparated` attribute that can be applied to controller parameters in order to accept the
comma-separated value format.
It does this via a mixture of custom attributes, value providers and a convention - all of which are closed to mocking and difficult to test, so I've covered the bits of code that I can.
=> Add support for comma-separated query string values

GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs, GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs, GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Models/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Existing relationships between TeachingEvent and TeachingEventBuilding do not get removed when the related Building is deleted. Currently, the Event is persisted in the cache with a null Building, which will then be re-added when the CRM sync runs.
Call DeleteLink in this scenario to remove the relationship in the CRM as well.
=> Remove teaching event relationships

GetIntoTeachingApi/Adapters/CdsServiceClientWrapper.cs, GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs, GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/PickListItem.cs, GetIntoTeachingApi/Services/CandidateUpserter.cs, GetIntoTeachingApiTests/Models/CandidatePastTeachingPositionTests.cs, GetIntoTeachingApiTests/Models/CandidateQualificationTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/PickListItemTests.cs, GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
The CdsServiceClient has had a major version bump (we were a major version behind anyway) and the core classes have been renamed to fall inline with the Microsoft PowerPlatform "Dataverse" branding.
Functionality-wise the interfaces remain largely consistent, just a couple of minor updates to the configuration of the client and the method to retrieve the current user (performed in the health check).
I plan on pushing this to dev and doing some full end-to-end testing with each of the clients to ensure everything still works correctly.
The main breaking change (discovered when testing the previous PR to do this update) is that deep-updates of navigation properties no longer appears to be supported; this means the `CandidateUpserter` has been updated to persist related qualifications and …
=> Update CdsServiceClient (take 2)

GetIntoTeachingApi/Adapters/CdsServiceClientWrapper.cs, GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs, GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/PickListItem.cs, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Services/CandidateUpserter.cs, GetIntoTeachingApiTests/Models/CandidatePastTeachingPositionTests.cs, GetIntoTeachingApiTests/Models/CandidateQualificationTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/PickListItemTests.cs, GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
I'm having trouble replicating the issue I found with the last deploy and I'm wondering if it actually deployed correctly; going to retry it and re-test in dev/test environments.
The CdsServiceClient has had a major version bump (we were a major version behind anyway) and the core classes have been renamed to fall inline with the Microsoft PowerPlatform "Dataverse" branding.
Functionality-wise the interfaces remain largely consistent, just a couple of minor updates to the configuration of the client and the method to retrieve the current user (performed in the health check).
I plan on pushing this to dev and doing some full end-to-end testing with each of the clients to ensure everything still works correctly.
The main breaking change is that deep-updates of navigation properties no …
=> Update CdsServiceClient (take 3)

GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApiTests/Models/TeachingEventRegistrationTests.cs
The old `CdsServiceClient` was able to infer the entity logical name for relationships, however the updated `ServiceClient` doesn't appear to do this and requires the logical name to be explicitly provided. It was already provided in most cases, but a couple of inferred attributes on the `TeachingEventRegistration` was causing issues.
=> Make logical name explicit for all EntityReference attributes

GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs
If an error when processing the `UpsertCandidateJob` it will retry 24 times before failing. I would have expected the exception to raise to Sentry, however I think that Hangfire may be swallowing it and the failed jobs are resulting in duplicate records being created in the CRM.
In order to determine if this is the case, we manually catch the exception from the upserter and log it out - re-raising to keep the Hangfire behaviour consistent.
I originally expected these jobs failing to be very edge-casey and so the jobs haven't been made atomic; if it turns out that they fail more often than expected we will need to look into making the jobs atomic, which will be difficult given the number of transactions with the API being made. We will probably need to split each transaction out into a …
=> Add logging for when UpsertCandidateJob throws

GetIntoTeachingApi/Models/Validators/CandidateValidator.cs, GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs
The API formats international numbers to prefix them with `00`, so we require the API validation to be slightly looser than the app validation for telephone numbers; increasing the max length from 20 to 25 should cover it.
=> Tweak telephone validation length

GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs
I've not got to the root cause of this bug, but if you sign up for a teaching event then perform a matchback and sign up for another teaching event without opting into the mailing list the API fails to send the sign up through to the CRM. The underlying exception is obscured by another exception raised by the ServiceClient library, so its not clear whats gone wrong.
The cause appears to be sending a `null` option set value for two of the optional properties; as these are optional we can instead not set them at all if they are passed to the API as null, which gets around the error for now. I'll look into raising an issue for the bug in the ServiceClient repo.
=> Conditionally set teaching event sign up attributes

GetIntoTeachingApi/Models/SchoolsExperienceSignUp.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeachingEventAddAttendee.cs, GetIntoTeachingApi/Utils/StringExtensions.cs, GetIntoTeachingApiTests/Models/SchoolsExperienceSignUpTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Utils/StringExtensionsTests.cs
- Support malformed UK numbers
If a candidate enters a UK phone number with a dial-in code and leading 0 it currently fails to dial; we can instead account for this and remove the leading 0 if present with a UK dialing code.
- Strip exit code before serving existing sign ups
If a candidate already exists in the system its likely that we will have transformed their telephone number into a format that is dialable by TPUK's telephone system. This means it will be prefixed with a `00` exit code. As we don't want the user to have to put in the exit code manually we expect their country dial-in code at the start of the telephone instead. We need to
therefore strip the `00` exit code from any responses that are subsequently used to pre-fill a form.
Reworks the telephone sanitisation to pull it …
=> Updates to international dialing logic

GetIntoTeachingApi/Controllers/TeachingEventsController.cs
We were getting the following error when upserting events and buildings due to the recent update of the Dataverse client: 
`The resource reference navigation property 'msevtmgt_building' has both the 'odata.bind' property annotation as well as a value`
As a quick fix, set the building to null before saving the event in the CRM.
=> Link event to building by ID only when saving in the CRM

GetIntoTeachingApi/Models/SchoolsExperienceSignUp.cs, GetIntoTeachingApiTests/Models/SchoolsExperienceSignUpTests.cs
There is a bug in the updated `CdsServiceClient` that results in an error if you try and set a `null` `OptionSet` attribute against an existing record; instead, we can just not set the value and it will remain unchanged in the CRM, which is a more desirable outcome anyway.
=> Don't set null option set values on SE sign up

GetIntoTeachingApi/Jobs/ClaimCallbackBookingSlotJob.cs, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Jobs/UpsertModelJob.cs, GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/IHasCandidateId.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApi/Services/CandidateUpserter.cs, GetIntoTeachingApi/Services/NotifyService.cs, GetIntoTeachingApiTests/Jobs/ClaimCallbackBookingSlotJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertModelJobTests.cs, GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs
[Trello-1627](https://trello.com/c/3B2nts1i/1627-split-upsertcandidatejob)
- Add job to claim a callback booking quota slot
When someone books a callback we need to ensure the callback booking slot they select has its available slots decremented. Currently we do this in the `UpsertCandidateJob`, but this commit adds a new job to perform this function.
- Add generic UpsertModelJob
As we are splitting the `UpsertCandidateJob` into multiple independent jobs we need to be able to upsert a variety of records that have a `CandidateId` (are related to a candidate). This commit adds an `UpsertModelJob` that can take any `BaseModel` implementing `IHasCandidateId` and upsert it to the CRM.
Update applicable models to implement the new interface.
- Have CandidateUpserter queue jobs for sub-tasks
The …
=> Split CandidateUpserter into multiple, atomic jobs

GetIntoTeachingApi/Controllers/CandidatesController.cs
If the CRM is down/throws any kind of exception we currently swallow it and return 404, so the user can continue as a new candidate. Instead, we want to raise the error to Sentry so we don't loose sight of it (if there is a bug in the matchback query, for example).
=> On match back failure log error to Sentry

GetIntoTeachingApi/Controllers/CallbackBookingQuotasController.cs, GetIntoTeachingApiTests/Controllers/CallbackBookingQuotasControllerTests.cs
The GiT website is going to start offering callback booking after mailing list sign up; this gives the app permission to call the quotas endpoint.
=> Enable GetIntoTeaching role on callback quotas

GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Integration/RateLimitTests.cs
The CRM team requested that rate limiting is applied to the upsert endpoint for additional security. It is unlikely that more than 100 events will be created in 1 day.
=> Apply rate limiting to event upsert endpoint

GetIntoTeachingApi/Controllers/GetIntoTeaching/CallbacksController.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/GetIntoTeachingCallback.cs, GetIntoTeachingApi/Models/Validators/GetIntoTeachingCallbackValidator.cs, GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/CallbacksControllerTests.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Integration/RateLimitTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeachingCallbackTests.cs, GetIntoTeachingApiTests/Models/Validators/GetIntoTeachingCallbackValidatorTests.cs
[Trello-1567](https://trello.com/c/lk6tXkkt/1567-product-book-a-call-functionality-on-ml-completion-page)
- Add model for GetIntoTeachingCallback
We want to add a new transaction in the Get into Teaching website that allows users to book a callback; this adds the request model with appropriate fields we want to collect.
- Add validator for request model
Add a validator for the new GetIntoTeachingCallback request model. Every field is required and callbacks can only be scheduled for future dates.
- Add controller for scheduling callbacks
Add a controller to enable the `GetIntoTeaching` role to schedule callbacks for candidates and exchange an access token for a pre-filled callback request model.
- Rate limit callback bookings
Add rate limiting for callback booking requests; intentionally …
=> Enable the GiT app to book callbacks

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Currently, the `UpsertTeachingEvent` endpoint is a bit slow.
`UpsertTeachingEvent` calls `CrmService.GetTeachingEvent` two times, once for validation and once to determine whether the attached building needs to be removed. 
Update `GetTeachingEvent` to use `QueryExpression` as it is quicker than LINQ.
=> Attempt to speed up `UpsertTeachingEvent`

GetIntoTeachingApi/Startup.cs
We run this minutely at present, but the feature is not in use - to avoid it polluting the logs and to make debugging other jobs easier I'm switching it to run hourly; if we need it in the future we can shorten the interval again. I don't want to turn it off completely as having it ticking over would surface any bugs/errors in the code.
=> Run MagicLinkTokenGenerationJob hourly

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Jobs/FindApplySyncJob.cs, GetIntoTeachingApi/Jobs/JobConfiguration.cs, GetIntoTeachingApi/Models/AppSettings.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/FindApply/Candidate.cs, GetIntoTeachingApi/Models/FindApply/CandidateAttributes.cs, GetIntoTeachingApi/Models/FindApply/Response.cs, GetIntoTeachingApi/Models/IAppSettings.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/Services/IMetricService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Jobs/FindApplySyncJobTests.cs, GetIntoTeachingApiTests/Models/AppSettingsTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/FindApply/CandidateAttributesTests.cs, GetIntoTeachingApiTests/Models/FindApply/CandidateTests.cs, GetIntoTeachingApiTests/Models/FindApply/ResponseTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
### Trello card
[Trello-1641](https://trello.com/c/LwotLDGF/1641-dev-find-apply-integration-work-with-the-api-crm)
The Find & Apply team are providing a candidates API that exposes candidate information updated since a given date/time. We want to query this API for the GiT API and sync up the `id` of their candidates with those matched in the CRM.
Initially we will only be matching back on email address and updating existing candidates (creating new candidates in the CRM that exist in Find & Apply but don't match back will come later).
We want to run the sync operation hourly and only in non-production environments. We will only be concerned with records updated _after_ the first sync run (past records will be bulk-imported by another process/job). 
- Store find/apply last sync date in …
=> Integrate with the Find & Apply candidates API

GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Services/IStore.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
Minor refactoring to add an overload of the `SaveAsync` method to the store that accepts a single model and tidy up the logic in the `Upsert` action of the `TeachingEventsController`.
=> Tidy upsert teaching event action

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs
Previously we were retrieving a matching `Candidate`, populating the `FindApplyId` and writing that back to the CRM. The issue with this is that the `Candidate` returned from the match query will be fully populated, so we end up writing back attributes needlessly.
Instead, we instantiate a new `Candidate` with the relevant `id` and populate the `FindApplyId`, ensuring that is the only attribute that will be written back to the CRM.
=> Only write FindApplyId attribute on sync job

GetIntoTeachingApi/Jobs/MagicLinkTokenGenerationJob.cs, GetIntoTeachingApiTests/Jobs/MagicLinkTokenGenerationJobTests.cs
The magic link generation job was failing due to writing back the entire `Candidate` object which contained `null` `OptionSet` values (these aren't supported by the Dynamics `ServiceClient`).
Instead, we create a new `Candidate` and only populate the fields that have changed.
=> Fix MagicLinkTokenGenerationJob

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Startup.cs
We don't directly use the `DataProtection` features of ASP.NET, but they are on by default and Hangfire appears to use them. We are seeing a number of anti-forgery check failures in the test environment, which appears to be due to running multiple instances and the `DataProtection` library persisting the tokens to disk by default. This means if a request goes to one  instance then the other it will fail the forgery check as the signatures wont match.
It doesn't appear to effect production as I believe its only the Hangfire dashboard that utilises the library (which is not enabled in prod).
Update to persist the keys in Redis, so that they are consistent across multiple instances.
=> Configure DataProtection to persist in Redis

GetIntoTeachingApi/Jobs/MagicLinkTokenGenerationJob.cs, GetIntoTeachingApiTests/Jobs/MagicLinkTokenGenerationJobTests.cs
We have 20k records getting magic links in the CRM and the request for the first 5k is timing out; reducing to 500 to see if that works.
=> Reduce magic link batch size

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
We are querying a lot of candidates and its timing out in the hosted dev instance; optimising the query to see if that fixes it.
=> Optimize magic link candidate query

GetIntoTeachingApi/Auth/HangfireDashboardEnvironmentAuthorizationFilter.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Auth/HangfireDashboardEnvironmentAuthorizationFilterTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
- Rename HangfireDashboardAuthorizationFilter
It wasn't clear from the name of the class that this is responsible for making the Hangfire dashboard only available in certain environments.
- Add basic auth to Hangfire dashboard
The Hangfire dashboard is only available in the dev/test environment, however there is no authentication in front of it at the moment. Whilst its not particularly exploitable, someone could re-queue a bunch of jobs and potentially clog up our workers.
Add basic authentication in front of the Hangfire dashboard.
=> Add basic auth to Hangfire dashboard

GetIntoTeachingApi/Auth/HangfireDashboardAuthorizationFilter.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Auth/HangfireDashboardAuthorizationFilterTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
Reverts DFE-Digital/get-into-teaching-api#685
For some reason this works locally but not in the hosted environment. There is another basic auth library I can try but it requires .NET Core 5 (we are on 3) so I will revert this until we can update .NET Core.
=> Revert "Add basic auth to Hangfire dashboard"

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Originally the subscription modelling was all in a separate `Subscription` class that pulled in from a different Dynamics entity. That was abandoned due to limitations in the CRM and the fields were all rolled into the `Candidate` model.
Remove the unnecessary loading of related subscription entities.
=> Remove un-necessary load of subscription relation

GetIntoTeachingApi/Auth/HangfireDashboardEnvironmentAuthorizationFilter.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Startup.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Auth/HangfireDashboardEnvironmentAuthorizationFilterTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
- Rename HangfireDashboardAuthorizationFilter
It wasn't clear from the name of the class that this is responsible for making the Hangfire dashboard only available in certain environments.
- Add Hangfire credentials to Env
Add the Hangfire username/password to Env for basic auth.
- Add basic auth to Hangfire in staging
Add a basic auth prompt to the Hangfire dashboard when in the staging environment (hosted dev and test).
=> Add basic auth to Hangfire dashboard (take 2)

.github/workflows/build.yml
[Trello-1685](https://trello.com/c/WXcNsFl0/1685-run-the-dev-test-deployments-in-parallel)
At the moment we deploy to the dev environment, then the test environment; it will save about 2.5 minutes off the 10 min deploy time if we deploy both in parallel.
I can't think of any downside to this? other than we get two failures on a bad deploy, but any failure is pretty rare now so probably not a big deal?
=> Run dev/test deployments in parallel

GetIntoTeachingApi/Services/Store.cs
We were finding that the app was serving 404s for some past teaching events; users likely bookmark the page and revisit it once the 4 month TTL of the events cache has expired. As the event sync was optimised a while back we should be fine to increase this to retrieve events further into the past.
Sync events going back 9 months instead of 4.
=> Sync teaching events up to 9 months old

GetIntoTeachingApi/Models/TeachingEvent.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
We have an immediate need to display Question Time events on the GiT website, bundled in with Train to Teach events. Doing this on the front-end is a substantial change that may not be doable by the deadline of tomorrow, so for now we are going to re-type these events during the API sync so that the website will automatically pull them through and display them correctly.
Once this is in we will look to correctly handle QT events on the website directly.
=> Sync Question Time events as Train to Teach

GetIntoTeachingApiTests/Helpers/ContractTestOrganizationServiceAdapter.cs
I think the contract tests are occasionally flakey depending on the order of the job runs; the `ClaimCallbackBookingSlot` job queries the API, which we weren't mocking so if it was not ran last (even though its queued last) the exception could result in the contract being incomplete.
=> Fix flakey contract tests

GetIntoTeachingApi/AppStart/ServiceCollectionExtensions.cs, GetIntoTeachingApi/AppStart/SwaggerDefinitionsFilter.cs, GetIntoTeachingApi/Attributes/SwaggerIgnoreAttribute.cs, GetIntoTeachingApi/Models/Candidate.cs, GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/CandidateQualification.cs, GetIntoTeachingApi/Models/PhoneCall.cs, GetIntoTeachingApiTests/Models/CandidatePastTeachingPositionTests.cs, GetIntoTeachingApiTests/Models/CandidatePrivacyPolicyTests.cs, GetIntoTeachingApiTests/Models/CandidateQualificationTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, GetIntoTeachingApiTests/Models/PhoneCallTests.cs
Since the update to .NET 5.0, Swashbuckle has being including models that should be hidden in the generated Swagger doc. This has gone unnoticed because the API client hasn't been regenerated in a while.
I think this is because of the update to FluentValidation, now that validators must be generic (but I'm not 100% sure)
To prevent this: 
- add a new SwaggerIgnore attribute that can be used to decorate any types that should not be included in the Swagger docs 
- hook into the generation process to inspect the schema for matching types.
=> Add Swagger definitions filter

GetIntoTeachingApi/Models/BaseModel.cs, GetIntoTeachingApiTests/Models/BaseModelTests.cs, GetIntoTeachingApiTests/Models/CandidateTests.cs, README.md
- Remove relationship entity mapping from `BaseModel`
We no longer use the MapRelationshipAttributesToEntity method of the BaseModel. This broke after the recent update to the CdsServiceClient, where we now are unable to deep insert entities (create related entities in a single request). We now persist entities independently instead.
=> Remove relationship entity mapping from `BaseModel`

GetIntoTeachingApi/Models/TeachingEventRegistration.cs, GetIntoTeachingApiTests/Models/TeachingEventRegistrationTests.cs
Missed a model in the previous [PR](https://github.com/DFE-Digital/get-into-teaching-api/pull/717). The Ruby client looks as it should now except this model 👍 
- `TeachingEventRegistration` should not be included in the generated Swagger doc. Decorate with `SwaggerIgnore` filter.
=> Swagger ignore TeachingEventRegistration

GetIntoTeachingApi/Controllers/GetIntoTeaching/CallbacksController.cs, GetIntoTeachingApi/Controllers/MailingListController.cs, GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeachingEventsController.cs, GetIntoTeachingApi/Models/Validators/GetIntoTeachingCallbackValidator.cs, GetIntoTeachingApi/Models/Validators/MailingListAddMemberValidator.cs, GetIntoTeachingApi/Models/Validators/SchoolsExperienceSignUpValidator.cs, GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApi/Models/Validators/TeachingEventAddAttendeeValidator.cs, GetIntoTeachingApi/Utils/ValidationResultExtensions.cs, GetIntoTeachingApiTests/Utils/ValidationResultExtensionsTests.cs, README.md
Validation errors on related models will appear in the format `RelatedModel.PropertyName`. It will be easier for clients to handle errors if they are mapped back to the request model property.
- Add an extension to `ValidationResult`. Intercept validation errors and map keys that are duplicated in any related model to the request model. Validation errors will now have the key `PropertyName`.
- Apply the interceptor to any request model validators with a hidden `Candidate` model. Update Swagger controller descriptions to remove warnings about hidden errors.
- Update validation error mapping advise in README
=> Map related model validation errors to request model

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs
This was accidently removed as part of an earlier refactoring; re-introducing as the swagger-codegen bases its method name from this.
=> Re-introduce OperationId

GetIntoTeachingApi/Models/Crm/PhoneCall.cs, GetIntoTeachingApi/Models/GetIntoTeaching/GetIntoTeachingCallback.cs, GetIntoTeachingApi/Models/GetIntoTeaching/Validators/GetIntoTeachingCallbackValidator.cs, GetIntoTeachingApiTests/Models/Crm/PhoneCallTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/GetIntoTeachingCallbackTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/GetIntoTeachingCallbackValidatorTests.cs
- Update PhoneCall Channel for GiT callback
We need to differentiate between the TTA callback and the GiT callback, which means providing different channels on the PhoneCall entity.
- Add talking points to callback request
When we create a callback from the GiT website we want to collect the talking points/reason for the phone call from the candidate to give the an adviser an indication of what the call will be about.
=> Updates to GetIntoTeachingCallbackBooking modelling

GetIntoTeachingApi/Fixtures/clients.yml, GetIntoTeachingApi/Properties/launchSettings.json
We are using external pen testers to test the API for vulnerabilities. To give access to all the endpoints they will be granted the `Admin` role, however we will only be providing keys for the dev and test environments (not prod).
=> Add API client for external pen testers

GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs
[Trello-1698](https://trello.com/c/yG3hzAuh/1698-development-unblock-get-an-adviser-applicants-who-have-previously-had-an-adviser)
Up until now if a candidate has already been assigned an adviser we prevent them from re-signing up to the TTA service.
It turns out some candidates that have been assigned an adviser will have their `contact` record set to have a 'closed' adviser status. In this scenario, we want to let them re-subscribe for an adviser.
Adds a new `CanSubscribeToTeacherTrainingAdviser` attribute as `AlreadySubscribedToTeacherTrainingAdviser` would not be completely accurate for the new use case. Once the TTA service has been updated this field can be removed.
=> Check if candidate can re-subcsribe based on adviser status

GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs
[Trello-1698](https://trello.com/c/yG3hzAuh/1698-development-unblock-get-an-adviser-applicants-who-have-previously-had-an-adviser)
- Rename AdviserStatus to AdviserStatusId
To match the other option set fields.
- Expose AdviserStatusId on TeacherTrainingAdviserSignUp
We need to expose this so that the client can post it back to us for matchback scenarios (otherwise we would have to query the CRM to retrieve it, which would complicate the logic for when the CRM is offline etc).
- Handle candidates with closed adviser status
When a candidate re-subscribes and has a closed adviser status we want to:
```
- Set the `AssignmentStatusId` to `WaitingToBeAssigned`
- Set the `RegistrationStatusId` to `ReRegistered`
- Update the `StatusIsWaitingToBeAssignedAt` to the current date/time
```
- Post …
=> Handle candidates re-signing up with a closed adviser status

GetIntoTeachingApi/Models/GetIntoTeaching/TeachingEventAddAttendee.cs
[Trello-1767](https://trello.com/c/0pE9y92j/1767-create-a-ml-sign-up-form-for-events-walk-ins)
We are going to start accepting 'walk in' sign ups to events that are otherwise closed to new registrations.
Add `IsWalkIn` attribute to the `TeachingEventAddAttendee` model so we can capture this and submit it with the rest of the event sign up form in the GiT app.
When the new channel creation has been added to the CRM we will be able to mark the candidate as a 'walk in' sign up.
=> Add IsWalkIn attribute to TeachingEventAddAttendee

monitoring/grafana/dashboards/get_into_teaching_api.json
Add a new panel to the Grafana dashboard to track the number of callbacks booked.
Shifts some of the other panels around, hence the big diff.
=> Add total callbacks booked Grafana panel

GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs
We were not mapping the `AdviserStatusId` to the request model from the `Candidate`, so when used to pre-fill the TTA sign up the field was missing and the behaviour was not correct on the subsequent form submission.
=> Map AdviserStatusId from Candidate

GetIntoTeachingApi/Fixtures/clients.yml, GetIntoTeachingApi/Properties/launchSettings.json
The pen testers have finished and no longer need API access.
=> Remove pen test client

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
The Dynamics `QueryExpression` interpreter doesn't support an empty value for an `In` conditional, so we need to return early in this instance and not call the CRM.
=> Bug fix to support empty array in GetCandidates method

GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs
This has been replaced with the `CanSubscribeToTeacherTrainingAdviser` attribute.
=> Remove redundant AlreadySubscribedToTeacherTrainingAdviser attribute

GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Integration/RateLimitTests.cs
[Trello-1801](https://trello.com/c/iv8XI7tS/1801-api-pen-test-revoke-admin-role-from-rate-limiting-whitelist)
The admin role was whitelisted from any rate limiting; this was flagged by the pen test, so we're going to let the default rate limits apply to that role.
Also adds a default rate limit for the POST /api/teaching_events endpoint.
=> Rate limit admin role

GetIntoTeachingApi/AppStart/ResponseHeaders.cs, GetIntoTeachingApi/AppStart/Startup.cs, GetIntoTeachingApi/Program.cs
- Remove Server header from response
The server header revealed that we use Kestrel and it was deemed 'verbose' by the pen test report so we are removing it.
- Add security headers
Adds the following security headers:
```
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'
```
Most of these are just box-ticking given access to the API is restricted by a secret and we don't serve any HTML in production.
=> Secure HTTP response headers

GetIntoTeachingApi/Properties/launchSettings.json
A HTTP to HTTPS redirection is potentially insecure; on a browser-facing website its often the lesser of two evils and forces users to connect via HTTPS if they input the HTTP address. On an API this isn't necessary and we can be more secure by disabling HTTP access completely, only accepting direct HTTPS connections (preventing a potential man in the middle attack).
To do this we ensure the application only accepts requests that are over HTTPS, as recommended by:
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio
I've updated dev/test with the appropriate `ASPNETCORE_URLS` env var and, assuming they work as expected, I'll update prod before shipping this.
=> Disable HTTP -> HTTPS redirection

GetIntoTeachingApi/Properties/launchSettings.json
Reverts DFE-Digital/get-into-teaching-api#746
This isn't deploying for some reason; even after I've reverted the env var changes in dev/test. The code change here _shouldn't_ have any bearing on dev/test, but in case it has I'm going to try and revert to see if it unblocks the deployments.
It looks like `ASPNETCORE_URLS` is also set in the Dockerfile, though when I ssh onto dev/test it doesn't appear explicitly set at all 🤷
=> Revert "Disable HTTP -> HTTPS redirection"

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/CallbacksControllerTests.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/ModelBinders/TrimStringModelBinderTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/GetIntoTeachingCallbackTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperience/SchoolsExperienceSignUpTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Services/CandidateMagicLinkTokenServiceTests.cs, GetIntoTeachingApiTests/Services/DateTimeProviderTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
- Update dependencies
Update most of the dependencies to their latest version; omits `FluentValidation` as this has a major change that will require some refactoring to support.
- Update to use latest FluentAssertion methods
Some of our methods had been deprecated and required updating.
=> Update dependencies to latest versions

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApiTests/Models/Crm/Validators/CandidatePastTeachingPositionValidatorTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/CandidatePrivacyPolicyValidatorTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/CandidateQualificationValidatorTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/PhoneCallValidatorTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/TeachingEventRegistrationValidatorTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/TeachingEventValidatorTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/GetIntoTeachingCallbackValidatorTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/MailingListAddMemberValidatorTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/TeachingEventAddAttendeeValidatorTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/TeachingEventSearchRequestValidatorTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperience/Validators/ClassroomExperienceNoteValidatorTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperience/Validators/SchoolsExperienceSignUpValidatorTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/ClientValidatorTests.cs, GetIntoTeachingApiTests/Models/Validators/ExistingCandidateRequestValidatorTests.cs
- Update FluentValidation
- Address deprecation warnings for FluentValidation
The `validator.ShouldHaveValidationErrorFor(attr, value)` has been deprecated in favour of using `TestValidate`. This updates all references, consolidates some of the separate tests into single tests to make them easier to read and removes some of the assertions for the inverse of rules (checking `null` is allowed, for example) as these don't add much value and bloat the test  suite quite a bit.
=> Update FluentValidation dependency

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Models/Crm/ApplicationForm.cs, GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/Crm/Validators/ApplicationFormValidator.cs, GetIntoTeachingApi/Models/Crm/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/FindApply/ApplicationForm.cs, GetIntoTeachingApi/Models/FindApply/CandidateAttributes.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApi/Utils/StringExtensions.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Models/Crm/ApplicationFormTests.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/ApplicationFormValidatorTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/FindApply/ApplicationFormTests.cs, GetIntoTeachingApiTests/Models/FindApply/CandidateAttributesTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs, GetIntoTeachingApiTests/Utils/StringExtensionsTests.cs
- Map additional attributes on Find/Apply models
New attributes are exposed on the Apply API; we are mapping these to the Find/Apply models so that we can later persist them to the CRM.
- Map Find/Apply modelling to CRM entities
The new data coming back from the Apply API will map to some new fields on the existing `Candidate` model and a new `ApplicationForm` model.
- Add extension to convert to PascalCase
We need this to be able to transform the incoming application status keys, such as `never_signed_in` to the respective C# enum key (i.e. `NeverSignedIn`).
- Sync additional Find/Apply data to CRM
We now have additional attributes on the apply `Candidate` model and a new `ApplicationForm` model that we can sync with the corresponding CRM models.
It is assumed for now that …
=> Sync additional data to the CRM from the Apply API

GetIntoTeachingApiTests/Models/Crm/Validators/ApplicationFormValidatorTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/CandidateValidatorTests.cs
These were missed in the original PR as they were in a separate branch that was subsequently merged in after the FluentValidation upgrade PR.
=> Fix deprecation warnings for FluentValidation

GetIntoTeachingApi/AppStart/Startup.cs, GetIntoTeachingApi/Attributes/EntityFieldAttribute.cs, GetIntoTeachingApi/Mocks/MockModel.cs, GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApi/Utils/StringExtensions.cs, GetIntoTeachingApiTests/Models/Crm/BaseModelTests.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs, GetIntoTeachingApiTests/Utils/StringExtensionsTests.cs
- Support environment-based feature switches
As we class both hosted dev and test environments as 'Staging' We currently have no way to toggle something on/off independently for each environment.
Add basic support for feature switching based on environment variables.
- Switch EntityFieldAttribute Ignored attribute to use features
We had a `Ignored` attribute that worked off the environment name. This works for most scenarios, but has the limitation of not being able to differentiate between our hosted dev and test environments, as they both run with the ASP.NET Core 'Staging' environment.
By switching it over to feature flags we can control which of these map to the CRM more granularly, so if the CRM team have only deployed a schema change to dev and not test, we can still deploy all the …
=> Support feature switching for Apply API sync

GetIntoTeachingApi/Models/Crm/ApplicationForm.cs, GetIntoTeachingApiTests/Models/Crm/ApplicationFormTests.cs
The CRM team have requested a `Name` attribute (mapped to `dfe_name`) on the `ApplicationForm` entity that is computed by the API in the format `Application Form <apply id>`.
=> Add Name attribute to ApplicationForm

README.md
Not sure what went on here but replacing the space between the `###` and the heading fixes it 🤷
Just a typo so merging it straight down 🔥
=> Fix heading markdown

GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApiTests/Jobs/LocationSyncJobTests.cs
The FreeMapTools service we use to geocode the bulk of our postcodes have changed the path to their CSV file. This updates it; the format appears unchanged.
=> Update FreeMapToolsUrl with new CSV path

.github/workflows/restart_prometheus.yml
Prometheus gets memory bound and hangs after a few days of running.
We cannot allocate much more memory, so for a quick fix,
use a GitHub action to restart the service.
=> Prometheus Restart

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/appsettings.Development.json, GetIntoTeachingApi/appsettings.json
[Trello](https://trello.com/c/rIFDcBnt)
ASP.NET log messages aren't interpreted properly by Logit.
- Set Serilog as the logging provider, so that all ILoggers now use it and log messages in JSON.
- Remove default logger configuration.
=> Format logging in JSON with Serilog

GetIntoTeachingApi/Controllers/GetIntoTeaching/TeachingEventsController.cs, GetIntoTeachingApi/Models/Crm/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/GetIntoTeaching/TeachingEventSearchRequest.cs, GetIntoTeachingApi/Models/GetIntoTeaching/Validators/TeachingEventSearchRequestValidator.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApi/Validators/PickListItemIdValidator.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/TeachingEventSearchRequestTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/TeachingEventSearchRequestValidatorTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
[Trello](https://trello.com/c/qbuoFw8L)
Sometimes we want to search by multiple event types so that we don't have to filter events in the client. 
For now we are keeping the `TypeId` property for backwards compatibility. It will be removed when the clients have been updated. 
- Add a `TypeIds` property that accepts an array of type IDs.
- Update any use of `TypeId` to `TypeIds` throughout the project, and temporarily set `TypeIds` to the value of `TypeId` if it is present.
- Update the `TeachingEventSearchRequestValidator` to a non-nullable `int`. This only broke one test, so I think it should be okay.
=> Allow multiple event types in event search

monitoring/prometheus/alert.rules
We are seeing the occasional `ZERO_RESULTS` response from Google when someone inputs an unknown postcode that is in a valid format. Instead, we want this to alert us if there is a flurry of bad requests to Google (most likely caused by an event that is given an invalid postcode or our Google API key being revoked).
=> Increase GoogleApiErrors alert threshold

GetIntoTeachingApi/Attributes/CommaSeparatedAttribute.cs, GetIntoTeachingApi/Attributes/CommaSeparatedQueryStringAttribute.cs, GetIntoTeachingApi/Controllers/GetIntoTeaching/TeachingEventsController.cs, GetIntoTeachingApi/Utils/CommaSeparatedQueryStringConvention.cs, GetIntoTeachingApi/Utils/CommaSeparatedQueryStringValueProvider.cs, GetIntoTeachingApi/Utils/CommaSeparatedQueryStringValueProviderFactory.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Utils/CommaSeparatedQueryStringValueProviderFactoryTests.cs, GetIntoTeachingApiTests/Utils/CommaSeparatedQueryStringValueProviderTests.cs
[Trello](https://trello.com/c/qbuoFw8L)
We want to search events by multiple TypeIds. To do this we have added a new collection type parameter. Unfortunately, ASP.NET expects the request in the following format:
```
?TypeIds=101&TypeIds=202
```
whereas the Swagger Codegen API client library produces incompatible queries that look like this:
```
?TypeIds=101,202
``` 
There is already a `CommaSeparatedAttribute` which handles this, but it only works for simple types because the `CommaSeparatedQueryStringConvention` passes the name of the parameter itself to the `CommaSeparatedQueryStringValueProvider`.
Extend the attribute so that we can specify which properties of complex types should be comma separated.
=> Extend comma separated attribute so that it can handle complex types

GetIntoTeachingApi/AppStart/ApplicationBuilderExtensions.cs, GetIntoTeachingApi/AppStart/ServiceCollectionExtensions.cs, GetIntoTeachingApi/AppStart/Startup.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
- Bulk update dependencies
Updates all dependencies that are outdated.
Closes #771, #770, #769, #764, #760
- Switch to AddHangfireServer
The `UseHangfireServer` method has become deprecated and they now recommend using `AddHangfireServer` in `ConfigureServices` instead.
=> Bulk update dependencies

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Models/Crm/ApplicationForm.cs, GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/Crm/Validators/ApplicationFormValidator.cs, GetIntoTeachingApi/Models/Crm/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/FindApply/ApplicationForm.cs, GetIntoTeachingApi/Models/FindApply/CandidateAttributes.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Models/Crm/ApplicationFormTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/ApplicationFormValidatorTests.cs, GetIntoTeachingApiTests/Models/FindApply/ApplicationFormTests.cs, GetIntoTeachingApiTests/Models/FindApply/CandidateAttributesTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
[Trello-1908](https://trello.com/c/soONwBZQ/1908-update-apply-api-integration-with-recent-changes)
Previously we were mapping the phase/status at the candidate-level. Instead, the Apply team have updated their API to provide the phase/status for each application form and will be deprecating the fields at the candidate-level.
The CRM team want to retain the candidate-level phase/status, having it contain the latest applicable application forms details; this is inferred from the first application form in the list we get back.
This commit maps the additional fields on `ApplicationForm` from the apply and CRM models, infers the candidate-level values and updates the store to sync the additional option sets.
All changes are only running in the dev environment for now.
=> Map phase/status to FindApply application forms

GetIntoTeachingApi/AppStart/ApplicationBuilderExtensions.cs, GetIntoTeachingApi/AppStart/ServiceCollectionExtensions.cs, GetIntoTeachingApi/AppStart/Startup.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
Reverts DFE-Digital/get-into-teaching-api#780
This was reverted originally due to seeing an error in the CrmSync job, which turned out to be caused by an option set getting deleted prematurely in the dev CRM and not this PR.
=> Bulk update dependencies take #2

README.md
[Trello-1805](https://trello.com/c/vOtypff0/1805-api-pen-test-insecure-redirection)
A penetration test highlighted our insecure http redirect as a possible point of exploitation. Looking into disabling http traffic it turned out that given the current infrastructure its not currently possible without a substantial change of how the API is hosted (as the redirect happens at the infrastructure level).
Instead, the readme is being updated with client configuration recommendations to ensure all clients point directly at the `http` version of the API.
=> Update with client configuration recommendations

GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
The front-end has been updated to natively support QT events by displaying them as though they are TTT events. We should now be fine to remove the remapping that occurs in the API.
This will need to be merged down and checked on dev/test before shipping to prod.
=> Undo remapping of QT events to TTT

GetIntoTeachingApi/Models/GetIntoTeaching/TeachingEventSearchRequest.cs, GetIntoTeachingApi/Models/GetIntoTeaching/Validators/TeachingEventSearchRequestValidator.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/TeachingEventSearchRequestTests.cs
This was kept for backwards compatibility and is no longer needed now that we have the `TypeIds` parameter.
=> Remove TypeId parameter from events search

GetIntoTeachingApi/Models/Crm/Validators/CandidateValidator.cs, GetIntoTeachingApiTests/Models/Crm/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/TeachingEventAddAttendeeValidatorTests.cs
[Trello-1930](https://trello.com/c/kcWhKB9W/1930-support-syncing-apply-only-candidates-in-the-api)
The candidates that come through from the Apply API will not always have a `FirstName` or `LastName`. We need to be able to accept records where a name has not been set, but still enforce first/last name on sign ups. As the request models already have validation in place to ensure first/last name is present, we can simply remove the `NotEmpty` check from the base `Candidate` model.
The existing validation on `Candidate` that was checking for required fields included some that are not required but were failing because an empty string is not valid; this is covered elsewhere so the test has been reduced to only include the required `Email` field.
=> Make first/last name optional on Candidate

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/ExistingCandidateRequest.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Models/Crm/BaseModelTests.cs, GetIntoTeachingApiTests/Models/ExistingCandidateRequestTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
[Trello-1930](https://trello.com/c/kcWhKB9W/1930-support-syncing-apply-only-candidates-in-the-api)
- Sync new Apply candidates to the CRM
Now that first/last name is not required in the base `Candidate` model we can map new Apply API candidates and persist them back to the CRM.
- Set channel for new Apply candidates
When we create a candidate through the Apply API integration we need to ensure the correct channel is set so that it can be attributed to that source.
- Fallback to matching on email only
We are now accepting candidates from Apply that only have an email address and no first/last name, however we need to be able to match back on these candidate records. In order to do this, we first attempt a 'full' match back on first/last/email and, if that fails, we perform a second match …
=> Sync new Apply candidates to the CRM

GetIntoTeachingApiTests/Contracts/TeacherTrainingAdviserTests.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
- Use FluentAssertions.Json in contract test assertion
The contract tests are flakey and can fail on occasion in CI. I'm not sure how this is happening yet, but in an effort to debug it (and maybe even resolve it) we're switching to use `FluentAssertions.Json` in order to check equivalency of of the request JSON with that of our snapshot JSON. If it fails again this should hopefully give us a more detailed diff of where it's is matched.
- Sort entities and attributes prior to comparison
Looking at the diff when the contract test fails in CI it appears to be because the ordering of the entity attributes has changed. As the attributes are not a collection the ordering is probably undefined and we can't sort it prior to serialising. Instead, we deserialise the snapshot and then sort it …
=> Use FluentAssertions.Json in contract test assertion

monitoring/prometheus/alert.rules
We are going to remove a large CSP whitelist of Google domains in the app because the headers are too large. Therefore, we will want to be alerted when there are any CSP violations that include `Google` so that the list can be built back up.
=> Add Prometheus alert for any CSP violations that include `Google`

monitoring/prometheus/alert.rules
Reverts DFE-Digital/get-into-teaching-api#795
The alerts are a bit too frequent, reverting until the violations that keep popping up are gone.
=> Revert "Add Prometheus alert for any CSP violations that include `Google`"

monitoring/alertmanager/alertmanager.yml, monitoring/grafana/dashboards/csp_violations.json, monitoring/prometheus/alert.rules, terraform/paas/variables.tf
- Fix existing Grafana CSP panels - There are two repeating rows of Grafana panels for CSP violations for the GiT app and TTA app. At some point these have broken, possibly due to an update.
- Add a Grafana table of Google CSP violations - We want to build up a CSP whitelist of Google domains in the GiT app. Adding a table showing the last 24 hours of violations so that we can have an alert posted to Slack.
- Add daily alert if /there are Google CSP violations - This alert will fire at 10am daily if there are any Google violations in the last 24 hours, and will contain a link to a table displaying them.
- Add Prometheus config - We can declare rules for certain alerts in Prometheus groups. Ensure that the Google CSP alert only fires once rather than continuously during the time specified …
=> Add google csp table grafana

GetIntoTeachingApi/Models/GetIntoTeaching/Validators/TeachingEventUpsertOperationValidator.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/TeachingEventUpsertOperationValidatorTests.cs
- Add stricter validation to teaching event readable ID (partial URL) - Currently there is only minimal validation on the event readable ID (partial URL), so we have seen partial URLs with non-alphanumeric characters such as brackets, colons, and question marks. Update the partial URL validation so that only alphanumeric, hyphens, and underscores are allowed.
- Use FluentValidation test helpers - Minor clean-up to ensure unique readable ID validations are coming through on the correct property.
=> Stricter partial URL validation

GetIntoTeachingApi/Controllers/PickListItemsController.cs, GetIntoTeachingApi/Models/Crm/Validators/CandidateValidator.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApi/Services/SubscriptionManager.cs, GetIntoTeachingApiTests/Contracts/Data/pick_list_items/candidate/teacher_training_adviser_subscription_channels.json, GetIntoTeachingApiTests/Controllers/PickListItemsControllerTests.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Models/Crm/Validators/CandidateValidatorTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs, GetIntoTeachingApiTests/Services/SubscriptionManagerTests.cs
The events team are pushing the TTA sign up at face-to-face events and want to be able to attribute sign ups back to the event.
Expose the `ChannelId` in the request model and map it to the `Candidate` (if a new candidate) and `TeacherTrainingAdviserSignUp` on sign up.
The field is optional so that existing sign ups still work as expected and the field is validated by the nested `CandidateValidator`.
=> Allow ChannelId to be specified on TeacherTrainingAdviserSignUp

GetIntoTeachingApi/Services/Store.cs
When a user searches for a postcode that isn't in the cache, the API will look it up via Google Geocoding then persist it.
If the API gets multiple requests in quick succession, the requests will be processed concurrently, resulting in a duplicate key exception as the API tries to persist the same postcode multiple times (the key for the Locations table is the postcode).
- Swallow the error in this very specific scenario.
=> Swallow errors when there are concurrent requests to add a postcode

terraform/paas/monitoring.tf
Accidentally left monitoring pointing at local copy.
=> Bug fix - Left in debug code

terraform/paas/monitoring.tf
[Change Monitoring Cloud Foundry credentials to a read only set.](https://trello.com/c/OUV8BiJu/2639-change-monitoring-cloud-foundry-credentials-to-a-read-only-set)
Use a specific set of credentials that are read only, to reduce the risk of them being hijacked.
=> Change Monitoring Cloud Foundry credentials to a read only set.

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Services/CandidateUpserter.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs
[Trello-2601](https://trello.com/c/VfWHN46B/2601-make-the-apply-candidate-sync-job-atomic)
Currently, the `FindApplyCandidateSyncJob` could persist a candidate then subsequently fail when trying to persist application forms. This would result in the whole job retrying and the candidate being re-created as a duplicate.
To prevent this from happening we are going to update the existing `CandidateUpserter` to also persist application forms and queue another job to use this service off the back of the `FindApplyCandidateSyncJob`. This will mean that the related application forms wont be persisted until the candidate has synced successfully (and it also queues the forms in individual jobs so retries are no longer a problem).
- Add relationship to application forms
Currently we persist …
=> Ensure FindApplyCandidateSyncJob is atomic

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs
The CRM can't accept any new data during releases. The solution to this in Get into Teaching is to queue the request until the CRM is back up.
However, in School Experience, candidate information is needed immediately by the Schools Experience app. So, we must provide a GUID up-front to the Candidate before queuing the request. This way, the School Experience app can persist the CRM GUID when it receives a response (as it usually does when the CRM is operational).
Usually, it is best practice to allow the CRM to generate sequential GUIDs which provide better SQL performance. However, in this scenario we have agreed it is beneficial to provide the GUID up-front because the School Experience app needs the Candidate ID immediately.
We want to test this before enabling it in production.
=> Cache candidate while CRM is down

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Jobs/AddClassroomExperienceNoteJob.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Helpers/BackgroundJobMock.cs, GetIntoTeachingApiTests/Helpers/PerformContextMock.cs, GetIntoTeachingApiTests/Jobs/AddClassroomExperienceNoteJobTests.cs
Part of the School Experience candidate sign up (in the app) attempts to add a `ClassroomExperienceNote`. This firstly fetches the candidate from the CRM. 
When the CRM integration is paused, this is not possible and we were therefore seeing 404 not found.
To fix this, add an `AddClassroomExperienceNoteJob` so that the API can queue the request until the CRM is operational again. 
The `AddClassroomExperienceNoteJob` must complete after the `UpsertCandidateJob` of the `SignUp` action. However, the Hangfire jobs run concurrently, so we silently retry the `AddClassroomExperienceNoteJob` three times to allow some time for the `UpsertCandidateJob` to complete.
=> Add an `AddClassroomExperienceNoteJob` so that request can be queued

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Models/Crm/ApplicationForm.cs, GetIntoTeachingApi/Models/Crm/Validators/ApplicationFormValidator.cs, GetIntoTeachingApi/Models/FindApply/ApplicationForm.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Models/Crm/ApplicationFormTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/ApplicationFormValidatorTests.cs, GetIntoTeachingApiTests/Models/FindApply/ApplicationFormTests.cs
[Trello-2651](https://trello.com/c/OaNTdS9Y/2651-add-additional-fields-to-apply-sync-job)
The Apply team have added two additional fields to their application forms; `submitted_at` and `recruitment_cycle_year`. We want to sync these through to the CRM so that we can make the reporting consistent between Apply and the CRM.
- Add new fields to the `ApplicationForm` models. 
- Sync the new `dfe_recruitmentyear` option set. 
- Map fields as part of the `FindApplyCandidateSyncJob`. 
These fields are available in the test/prod CRM and Apply environments, so we should be good to push this all the way out to production.
=> Sync new Apply API fields

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Jobs/AddClassroomExperienceNoteJob.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs
I hadn't updated the candidate sent to the `UpsertCandidateJob`. The candidate was being sent to the CRM with a `null` ID and the CRM was generating one.
Also fix SonarCloud code smell that was left in from refactoring.
=> Fix candidate Id not being set before being sent to job

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Models/Crm/ApplicationForm.cs
Apply are sending through recruitment cycle years that are outwith the initial option set values the CRM team created. The CRM team have since updated their option set values, but we need to account for those in the API.
To make it easier to maintain going forward I'm mapping the recruitment cycle year dynamically; there should never be a year before 2020 and the option set values are guaranteed to be sequential.
=> Dynamically map recruitment cycle year

GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/GetIntoTeaching/MailingListAddMember.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/MailingListAddMemberTests.cs
[Trello-2661](https://trello.com/c/catUOcuk/2661-update-api-to-include-welcome-guide-query-parameters)
If we serve a welcome guide to the user we want to be able to track which version was served to them at the time of sign up (the fields to determine this can change over time on the candidate record).
The field is not required and is left as plain text for the client to define.
=> Add field to track which welcome guide variant was served

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Models/Crm/BaseModel.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Models/Crm/BaseModelTests.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/Crm/TeachingEventRegistrationTests.cs, GetIntoTeachingApiTests/Models/Crm/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Currently, the `CrmService` chooses the which `OrganisationService` method to call based on whether the model has an existing ID.
However, in certain circumstances, we need to allow to API to generate an ID up-front. 
Add a `GeneratedUpfrontId` method to the `BaseModel`, which sets a flag of `HasUpfrontId` on the model to true. The `BaseModel` can then choose which `OrganisationService` method to call based on the value of the flag.
=> Ensure correct method is called when the ID is API generated

GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs
This was available in dev and has since been shipped to test/prod CRM instances, so we can enable it there too.
=> Enable welcome guide variant field in test/prod

GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs, GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs, GetIntoTeachingApi/Models/Crm/BaseModel.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Helpers/ContractTestOrganizationServiceAdapter.cs, GetIntoTeachingApiTests/Models/Crm/BaseModelTests.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/Crm/TeachingEventRegistrationTests.cs, GetIntoTeachingApiTests/Models/Crm/TeachingEventTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Currently, when an upfront ID is generated for a model, and it is saved in the CRM, it is returned with a different ID.
We may need to create the `Entity` object with an ID in the first place before adding it to the context. :anguished:
Add an optional ID parameter that is passed down to the `OrganizationServiceAdapter`, we can pass this to the new `Entity` object.
=> Update `NewEntity` to handle when the model has an upfront ID

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
[Trello-2649](https://trello.com/c/gckG3orM/2649-update-to-aspnet-core-6)
Update all dependencies that we can ahead of the ASP.NET Core v6 bump. A couple fail to update, I think because they require ASP.NET Core 6.
=> Update dependencies ahead of .NET Core 6

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs
This has been tested by performing an end-to-end sign up in the test environment. The flag can now be removed.
=> Remove feature flag for candidate sign up when CRM integration paused

GetIntoTeachingApi/Services/Store.cs
[Trello-2675](https://trello.com/c/d6dk89B4/2675-address-why-so-many-historic-events-are-still-on-site-and-appear-in-serps)
Currently, if someone directly visits a past event on the website we allow them to view it; whilst we want to retain this for the previous 4 months of events that have an archive (Online Q&As) we don't want to let users view events that are older than that. This change makes the API consistent with the website.
=> Reduce event archive size to 4 months

GetIntoTeachingApi/Models/Crm/BaseModel.cs
The `HasUpfrontId` property was being exposed via Swagger, adding the `JsonIgnore` attribute will prevent this.
Using the `internal` modifier seems to do the same thing, is it worth going through the project replacing all of the `JsonIgnore`s with `internal`?
=> Add JsonIgnore attribute to `HasUpfrontId` property

GetIntoTeachingApi/Auth/ApiClientHandler.cs, GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/GetIntoTeaching/CallbacksController.cs, GetIntoTeachingApi/Controllers/GetIntoTeaching/MailingListController.cs, GetIntoTeachingApi/Controllers/GetIntoTeaching/TeachingEventsController.cs, GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Models/ExistingCandidateRequest.cs, GetIntoTeachingApi/Services/CandidateAccessTokenService.cs, GetIntoTeachingApi/Services/MetricService.cs, GetIntoTeachingApiTests/Auth/ApiClientHandlerTests.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/CallbacksControllerTests.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/TeachingEventsControllerTests.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Helpers/ControllerBaseExtensions.cs, GetIntoTeachingApiTests/Services/CandidateAccessTokenServiceTests.cs, GetIntoTeachingApiTests/Services/MetricServiceTests.cs
[Trello-2692](https://trello.com/c/HYJoDiVp/2692-investigate-if-authentication-is-causing-significant-drop-off-on-event-sign-ups)
We want to be able to attribute TOTP-related metrics to individual services (and perhaps later to individual transactions within a service).
- Add Reference attribute to ExistingCandidateRequest
We want to be able to attribute authentication actions (generate TOTP/verify TOTP) to specific transactions; in order to do this we will get the clients to pass a reference (e.g. "Mailing List", "Event", etc).
- Add reference label to TOTP metrics
We currently track the generated/verified TOTPs; we now want to break this down by service transaction.
Add a label that can store a reference for the TOTP action and populate it in the token generation service.
- Add a new …
=> Label TOTP metrics with service reference

monitoring/grafana/dashboards/get_into_teaching_api.json
We want to know how often generated TOTPs are successfully verified for each service.
=> Add new panels for TOTP success rates

.github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml, Dockerfile, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApi/Services/CandidateMagicLinkTokenService.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
> :warning: This will need some thorough manual testing, specifically around the matchback/verification code.
[Trello-2649](https://trello.com/c/gckG3orM/2649-update-to-aspnet-core-6)
- Bump ASP.NET Core version to 6
Update to the latest ASP.NET Core version that offers long-term support.
- Replace deprecated crypto service
It is recommended to use the new `RandomNumberGenerator` static methods for crypto-related tasks.
- Update to use HttpClient
`System.Net.WebClient` has been deprecated in favour of `HttpClient`.
- Upgrade to latest Docker image
The Docker image needs to match the build config.
=> Upgrade to ASP.NET Core 6

monitoring/grafana/dashboards/get_into_teaching_api.json
We currently graph the per-service verification code success rates, however we can now distinguish them at the transaction-level for GiT.
It looks a little light at the minute as we have hardly any data with the new references:
=> Add panels for per-transaction verification code success rates

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs
[Trello-2729](https://trello.com/c/XaOYBfWz/2729-apply-candidate-sync-job-bug-fix)
The Apply API should be returning application forms in order of most recently updated first, however this doesn't appear to be the case. Instead, we're going to order the application forms explicitly in the API, taking the latest phase/status for the contact-level attributes.
=> Take latest application form for contact-level

terraform/paas/monitoring.tf
CVE-2021-43798 - Update Grafana to 8.3.2
Grafana versions 8.0.0-beta1 through 8.3.0 (except for patched versions) iss vulnerable to directory traversal, allowing access to local files. The vulnerable URL path is: `<grafana_host_url>/public/plugins//`, where is the plugin ID for any installed plugin.  Users are advised to upgrade to patched versions 8.0.7, 8.1.8, 8.2.7, or 8.3.1. 
This is a low risk to us as we are containerised and there is no secure data available.However, it has been decided to bring Grafana into line with the latest version.
=> Grafana directory traversal

monitoring/grafana/dashboards/get_into_teaching_apps.json
[Trello-2640](https://trello.com/c/PMZfAK9g/2640-create-grafana-dashboard-for-reliable-user-count)
Add a cookie opt-in panel to show the success rate by category. Currently only implemented in the app, so the TTA version of the dashboard will return no data.
Its all or nothing so far; people either opt in to everything or out of everything it seems, but I manually opted-in to non-functional and out of marketing to check it gets reflected in the metrics:
This looks [as expected](https://www.teads.com/gdpr-only-5-of-european-users-refuse-cookies-used-for-personalised-advertising/) as well...
=> Add cookie opt-in panel to apps dashboard

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs
We have seen some failed UpsertCandidateJobs in Prometheus while testing this new endpoint where the Guid is set to the default value of `00000000-0000-0000-0000-000000000000`.
I was accidentally setting candidate ID from the CandidateSchoolExperience model instead of the 'Id' request parameter.
=> Add candidate ID parameter to add school experience action

GetIntoTeachingApi/Models/SchoolsExperience/SchoolsExperienceSignUp.cs, GetIntoTeachingApi/Models/SchoolsExperience/Validators/SchoolsExperienceSignUpValidator.cs, GetIntoTeachingApiTests/Models/SchoolsExperience/SchoolsExperienceSignUpTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperience/Validators/SchoolsExperienceSignUpValidatorTests.cs
We only collect primary email address and phone number in School Experience as part of the sign up. Remove the following unused fields: AddressTelephone, MobileTelephone, SecondaryTelephone, SecondaryEmail,
=> Remove unused fields from the SchoolExperienceSignUp

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Currently, we use secondary phone number in School Experience if primary number already has a value.  Going forward we have agreed to use primary phone number only. 
This endpoint will be used to retrieve all School Experience candidates with primary and secondary phone numbers that are different, because these will be negatively impacted by the change (we will be assuming that their primary phone number is the most up to date, but it will actually be their secondary phone number).
This endpoint will be removed once we have retrieved the candidates from production and passed them on to the CRM team.
=> Get candidates with different primary and secondary phone numbers

GetIntoTeachingApi/Models/SchoolsExperience/SchoolsExperienceSignUp.cs, GetIntoTeachingApiTests/Models/SchoolsExperience/SchoolsExperienceSignUpTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperience/Validators/SchoolsExperienceSignUpValidatorTests.cs
It is `address1_telephone1` that is used by the call centres, so this is the field that should be used as primary phone number (not `telephone1`).
=> Use address telephone instead of telephone as primary number

monitoring/prometheus/alert.rules
We appear to get a lot of traffic from bots/crawlers that hit non-hashed versions of the assets and get a 404. As we check all of our internal assets in our unit tests I think we should be safe to exclude them here; 404s are likely only to come from external websites that have linked to an image we have since removed, which we can do nothing about.
Exclude `*.txt` files as we don't host any and its another source of bot traffic (i.e. `passwords.txt` 🤦).
=> Ignore assets in HighNotFound app alert

GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/appsettings.Production.json, GetIntoTeachingApi/appsettings.json
If we serialise our logs using JSON we get better configuration options and search-ability in Kibana.
Move Serilog configuration into `appsettings.json` and use compact JSON logger in production.
=> Use compact JSON in production logs

GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/appsettings.Production.json, GetIntoTeachingApi/appsettings.Staging.json, GetIntoTeachingApi/appsettings.json
If we serialise our logs using JSON we get better configuration options and search-ability in Kibana.
Move Serilog configuration into `appsettings.json` and use compact JSON logger in production/staging environments.
I think this didn't work last time because we have an `ASPNETCORE_ENVIRONMENT` of `Staging` for dev/test and only included appsettings for `Production`.
=> Use compact JSON in production logs (Take 2)

terraform/paas/monitoring.tf
When connecting to docker hub use a service account to prevent rate limits when getting monitoring images
=> Connect to Docker with username to prevent rate limits

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Fixtures/clients.yml, GetIntoTeachingApi/Services/NotifyService.cs, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs
- Use new email template on create access token
The new email template has updated copy and uses the candidate's first name to make it more personalised.
=> New email template verification code

.github/workflows/actions/deploy/action.yml, .github/workflows/build.yml, .github/workflows/check_alert_rules.yml, .github/workflows/manual.yml, .github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml, GetIntoTeachingApi/Database/GetIntoTeachingDbContext.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Program.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Models/GetIntoTeaching/GetIntoTeachingCallbackTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/TeachingEventAddAttendeeTests.cs, GetIntoTeachingApiTests/Models/SchoolsExperience/SchoolsExperienceSignUpTests.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs
Closes #935 #931 #925 #923 #922 #933 #934
- Update various dependencies
- Update GitHub action dependencies
- Update tests for FluentAssertion changes
- Update to latest Pgsql packages
The Hangfire Postgresql adapter we were using was not compatible with v6.0 of Pgsql so we've had to swap from a fork back to the main repository (which previously had an issue with database connection leaks, which is why we swapped it out - hopefully it no longer has this issue).
=> Update various dependencies

.github/workflows/build.yml
These have been migrated into the individual apps; at the moment there's no way of running them independently, but if we feel they are useful we can expose them from the app/tta and call them from the API build pipeline.
I think the contract tests are probably enough coverage, but we may want to create contracts for the mailing list/event sign ups in addition to the TTA.
=> Remove Cypress tests on deploy

GetIntoTeachingApi/Models/Crm/CandidateSchoolExperience.cs
I accidentally used the `withdrawn` status for candidates who did not attend their placement when migrating the app to use the CandidateSchoolExperience entity. Withdrawing is a separate action.
To fix this, we have updated the `withdrawn` status name to `did not attend` (which will fix the existing requests), and added a new status for `withdrawn` (so that this can be used in the correct place).
=> Update school experience statuses

monitoring/prometheus/alert.rules
Add alerts to flag if we get an unusually high number of CSP violations (>20 in a 5 minute period). This should weed out CSP violations caused by ad-blockers for individual clients and (hopefully) only alert if multiple users are receiving the same CSP violation.
Suffix alert names with the app to make it easier to distinguish where the alert originated from (this is mainly useful for the app/tta alerts as they have the same names in most cases).
=> Add alerts for a high number of CSP violations

GetIntoTeachingApi/Models/FindApply/ApplicationChoice.cs, GetIntoTeachingApi/Models/FindApply/ApplicationForm.cs, GetIntoTeachingApi/Models/FindApply/ApplicationResponse.cs, GetIntoTeachingApi/Models/FindApply/Candidate.cs, GetIntoTeachingApi/Models/FindApply/Course.cs, GetIntoTeachingApi/Models/FindApply/Interview.cs, GetIntoTeachingApi/Models/FindApply/Provider.cs, GetIntoTeachingApi/Models/FindApply/Reference.cs, GetIntoTeachingApiTests/Models/FindApply/ApplicationChoiceTests.cs, GetIntoTeachingApiTests/Models/FindApply/ApplicationFormTests.cs, GetIntoTeachingApiTests/Models/FindApply/ApplicationResponseTests.cs, GetIntoTeachingApiTests/Models/FindApply/CandidateTests.cs, GetIntoTeachingApiTests/Models/FindApply/CourseTests.cs, GetIntoTeachingApiTests/Models/FindApply/InterviewTests.cs, GetIntoTeachingApiTests/Models/FindApply/ProviderTests.cs, GetIntoTeachingApiTests/Models/FindApply/ReferenceTests.cs
[Trello-3085](https://trello.com/c/2HSIv6Bq/3085-update-api-for-v12-of-apply-git-datasharing)
- Updated Apply models for API v1.2
The updated Apply API (v1.2) contains additional models related to the `ApplicationForm`; this commit adds them and maps the attributes to the JSON response payload from the API.
Add convenience methods on each model to map from the Apply models to the CRM models.
=> Updated Apply models for API v1.2 

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Jobs/UpsertApplicationFormJob.cs, GetIntoTeachingApi/Jobs/UpsertModelWithCandidateIdJob.cs, GetIntoTeachingApi/Services/CandidateUpserter.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Helpers/ContractCrmService.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertApplicationFormJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertModelWithCandidateIdJobTests.cs, GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
[Trello-3085](https://trello.com/c/2HSIv6Bq/3085-update-api-for-v12-of-apply-git-datasharing)
- Add generic Find/Apply CRM query
We are going to need to query application forms/choices/references/interviews from the CRM in order to reconcile the Apply API response with existing records based on the Find/Apply ID. Instead of having multiple CRM methods for each model we can leverage the `IHasFindApply` interface to make a generic method to query the models.
- Add job to upsert an ApplicationForm and related models
The `ApplicationForm` requires its own upserter job to match records to existing CRM models before persisting (as we used the `FindApplyId` rathern than the CRM `Id`).
Unlike the `Candidate` model it doesn't matter if an `ApplicationForm` gets part way through upserting and then …
=> Add ApplicationFormUpsert job

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
[Trello-3085](https://trello.com/c/2HSIv6Bq/3085-update-api-for-v12-of-apply-git-datasharing)
- Ensure Apply API url is correct depending on features
If the new `APPLY_API_V2_1` feature is enabled we need to append `/v1.2` to the URL to ensure the correct response payload is returned from the Apply API.
- Use UpsertApplicationForm job when syncing Apply API
We have a new `UpsertApplicationFormJob` that deals with upserting either a v1.1 or v1.2 `ApplicationForm` and associated entities. Switching to use this in the `FindApplyCandidateSyncJob` simplifies the logic for updating (otherwise we would have a job per API version).
=> Support v1.2 of the Apply candidate API

GetIntoTeachingApiTests/Contracts/ApplyCandidateApiTests.cs, GetIntoTeachingApiTests/Contracts/BaseTests.cs, GetIntoTeachingApiTests/Contracts/Data/application_choices.json, GetIntoTeachingApiTests/Contracts/Data/application_forms.json, GetIntoTeachingApiTests/Contracts/Data/application_interviews.json, GetIntoTeachingApiTests/Contracts/Data/application_references.json, GetIntoTeachingApiTests/Contracts/Input/ApplyCandidateApi/sync_with_a_new_candidaite_and_application_form.json, GetIntoTeachingApiTests/Contracts/Input/ApplyCandidateApi/sync_with_a_new_candidate_and_fully_populated_application_form.json, GetIntoTeachingApiTests/Contracts/Input/ApplyCandidateApi/sync_with_an_existing_candidate_and_fully_populated_application_form.json, GetIntoTeachingApiTests/Contracts/Output/ApplyCandidateApi/sync_with_a_new_candidaite_and_application_form.json, GetIntoTeachingApiTests/Contracts/Output/ApplyCandidateApi/sync_with_a_new_candidate_and_fully_populated_application_form.json, GetIntoTeachingApiTests/Contracts/Output/ApplyCandidateApi/sync_with_an_existing_candidate_and_application_form.json, GetIntoTeachingApiTests/Contracts/Output/ApplyCandidateApi/sync_with_an_existing_candidate_and_fully_populated_application_form.json, GetIntoTeachingApiTests/Contracts/TeacherTrainingAdviserTests.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Helpers/ContractCrmService.cs
- Add contract tests for v1.2 of Apply API integration
Add additional contract tests to cover the new attributes/related models in the v1.2 Apply API integration.
- Clean up contract tests
Encapsulates more of the logic into the `BaseTests` superclass so that the contract tests are easier to understand.
=> Add contract tests for v1.2 of the Apply API integration

.github/workflows/build-no-cache.yml, Dockerfile
Docker build layers are cached to optimise build performance but sometimes the base image is updated so we need to rebuild it.  Implementing snyk in this workflow highlights a high severity vulnerability in the base image.
- Add a build-no-cache workflow that is scheduled once a week on Sunday and can be run manually as required.
- Change the base image tag from the default to the alpine version.  This addresses the vulnerability, simplifies the dockerfile and aligns the OS with other projects which will simplify future maintenance. 
- Check the new workflow runs as expected, example [here](https://github.com/DFE-Digital/get-into-teaching-api/actions/runs/2232025759)
- Test the application to identify any issues with the OS change
=> Workflow to rebuild master docker image

.github/workflows/build.yml, .github/workflows/manual.yml
The ACTIONS-API-ACCESS-TOKEN token requires manually configuration and renewal.
The GitHub Actions secret and workflow permissions can be used to manage API access.
Check that modified workflows continue to work as expected.
=> Remove references to ACTIONS-API-ACCESS-TOKEN

.gitignore, GetIntoTeachingApi/.env.dev, GetIntoTeachingApi/.env.production, GetIntoTeachingApi/.env.staging, GetIntoTeachingApi/AppStart/Startup.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApi/Utils/IEnv.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs, Makefile, README.md
[Trello-3177](https://trello.com/c/fr6To0cP/3177-remove-unused-secrets)
We have a number of environment variables in keyvault that are not secrets; they are better placed in the application.
Adds additional .env files for hosted dev/test/prod environments and migrates the non-secret environment variables from Azure keyvault.
Rename the local .env file to `.env.local` to differentiate from the hosted development environment (which is configured with `.env.development`).
=> Migrate non-secret environment variables into .env files

monitoring/prometheus/alert.rules
It looks like we periodically get a burst of enqueued jobs in SE; upping the limit to avoid false-positives.
=> Increase HighJobsWaiting threshold

GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs, GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Models/PickListItem.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Helpers/ContractTestOrganizationServiceAdapter.cs, GetIntoTeachingApiTests/Models/PickListItemTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
The main update is to the `Dataverse.ServiceClient` which re-namepsaces the `PickListItem` model into `Extensions`. As we have our own `PickListItem` model we have to reference them explicitly via their namespace to avoid a conflict.
Closes #988, #987, #984, #968, #957
=> Various dependency updates

GetIntoTeachingApi/Models/Crm/ApplicationReference.cs, GetIntoTeachingApi/Models/FindApply/Reference.cs, GetIntoTeachingApiTests/Contracts/Input/ApplyCandidateApi/sync_with_a_new_candidate_and_fully_populated_application_form.json, GetIntoTeachingApiTests/Contracts/Input/ApplyCandidateApi/sync_with_an_existing_candidate_and_fully_populated_application_form.json, GetIntoTeachingApiTests/Contracts/Output/ApplyCandidateApi/sync_with_a_new_candidate_and_fully_populated_application_form.json, GetIntoTeachingApiTests/Contracts/Output/ApplyCandidateApi/sync_with_an_existing_candidate_and_fully_populated_application_form.json, GetIntoTeachingApiTests/Models/Crm/ApplicationReferenceTests.cs, GetIntoTeachingApiTests/Models/FindApply/ReferenceTests.cs
We want to be able to track the created/updated on dates for `ApplicationReference` entities; the Apply API has been updated to include these and this commit maps them into the respective CRM entity fields.
=> Add new date fields to ApplicationReference

Makefile, README.md
We don't have the preceding dot in the env file, but the Makefile generates one with it (which means it gets missed by the gitignore and may be accidentally committed).
=> Fix Makefile naming of env file

monitoring/grafana/dashboards/git_services_traffic.json, terraform/paas/monitoring.tf
Create a simple dashboard showing user traffic to the 4 main GiT services so we can display it on a TV screen in the office
Enable readonly anonymous access to Grafana
Dashboard: https://grafana-prod-get-into-teaching.london.cloudapps.digital/d/85ArdlD7k/git-services-traffic
=> [592] Grafana GiT services traffic dashboard

monitoring/prometheus/alert.rules
Add a `WorkerFailure` alert that checks to ensure the heart beat metric is being incremented (an indication that jobs are running).
Update `HighJobsWaiting` and `HighJobFailures` to hopefully alert more correctly; when more than 3 jobs have been pending (not picked up) over the last 10 minutes and if we see multiple job failures in a 15 minute period.
I've also updated the runbooks to match.
=> Update GSE delayed job alerting rules

monitoring/prometheus/alert.rules
We want to alert when there haven't been any heart beat counts within a 3 minute period; I had the conditional wrong here.
=> Fix alert rule conditional

GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/Crm/Validators/CandidateValidator.cs, GetIntoTeachingApi/Utils/Redactor.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/CandidateValidatorTests.cs
[Trello-3515](https://trello.com/c/FF6qiIdL/3515-remove-emailaddress2-field-from-the-api)
We no longer collect a `SecondaryEmail` (we used to from the School Experience service). The CRM team have flagged that they are re-purposing that field and so we should remove it to make sure its not accidentally used in the future.
=> Remove unused SecondaryEmail attribute from Candidate

GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApiTests/Jobs/LocationSyncJobTests.cs
[Trello-3554](https://trello.com/c/mZeYYqN7/3554-fix-location-sync-job-in-api)
The service we use to sync UK postcode data from has changed the location of their CSV file (now on a `data` subdomain).
Update to fix the URL.
=> Update postcode CSV URL

terraform/paas/provider.tf, terraform/paas/statuscake.tf, terraform/paas/variables.tf
Update the StatusCake provider to ensure it is not using a preview version.
There are no configured StatusCake alerts for the GiT API however the changes are the same as those recently implemented across SE, GiT App and GTTA.
=> Update Terraform StatusCake provider to 2.0.3

.github/workflows/actions/deploy/action.yml, terraform/paas/.gitignore, terraform/paas/.terraform.lock.hcl, terraform/paas/dev.bk.vars, terraform/paas/production.bk.vars, terraform/paas/provider.tf, terraform/paas/test.bk.vars, terraform/paas/variables.tf
Ensure the Terraform version contains the latest fixes and supports Apple processors
- Add various Azure credential defaults to support running locally
- Add resource group to environment files to support running locally
=> Upgrade Terraform to version 1.2.8

terraform/paas/production.env.tfvars
This will allow scraping internal metrics
=> Fix prometheus reference to SE staging

terraform/paas/dev.env.tfvars, terraform/paas/production.env.tfvars
We are running Sidekiq instances in dev/staging now; this will make Prometheus scrape them.
=> Add Prometheus targets for dev/staging Sidekiq instances

monitoring/prometheus/alert.rules
[Trello-641](https://trello.com/c/W6usHTny/641-switch-our-job-processor-to-sidekiq)
We need to update our job alerts to use the Sidekiq metrics as we now run this in production.
=> Update job alerts for Sidekiq

GetIntoTeachingApi/Models/Crm/TeachingEvent.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
Add support for Get into Teaching events; adding to this enum will result in the new evet types being synced from the CRM. There are currently only Get into Teaching events in the development CRM environment.
=> Support Get into Teaching events

GetIntoTeachingApi/Controllers/PickListItemsController.cs, GetIntoTeachingApi/Migrations/20220915115624_AddRegionIdToTeachingEvent.Designer.cs, GetIntoTeachingApi/Migrations/20220915115624_AddRegionIdToTeachingEvent.cs, GetIntoTeachingApi/Models/Crm/TeachingEvent.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApi/env.dev, GetIntoTeachingApi/env.prod, GetIntoTeachingApi/env.test, GetIntoTeachingApiTests/Controllers/PickListItemsControllerTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
[Trello-3649](https://trello.com/c/543WVKAS/3649-update-api-to-support-get-into-teaching-events)
The new Get into Teaching events will have a specific region assigned to them, so we can show 'all events in the North West', for example.
Add support for `RegionId` on `TeachingEvent`. The CRM attribute is currently only enabled in the `development` CRM environment.
=> Add RegionId to TeachingEvent

GetIntoTeachingApi/env.prod, GetIntoTeachingApi/env.test
The schema changes are now in the CRM production instance.
Enable in production will cause Get into Teaching events to sync and the `RegionId` to be exposed on `TeachingEvent`.
=> Enable Get into Teaching events in test/production

GetIntoTeachingApi/Adapters/CdsServiceClientWrapper.cs, GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
[Trello-656](https://trello.com/c/LivMzbVO/656-investigate-timeout-exception)
We are seeing errors on the School Experience service where the health check times out on calling the API health check endpoint.
I'm not sure what is causing this, but I expect that the CRM is being slow to respond as we've seen this happen in the past. To work around this we are only going to call out to the CRM once every minute (caching the health check responses in-between). 
I have also changed the CRM method we call to a generic entity name lookup for the `contact` entity; I suspect the other method we were using (`GetMyUserId`) may end up hitting Microsoft Authentication Library (MSAL) which could be a reason it takes longer than expected.
=> Attempt to make the health check more robust

.github/workflows/actions/deploy/action.yml, .github/workflows/build-no-cache.yml, .github/workflows/build.yml
Pin github actions to major version and let it pick the latest minor version automatically. This is to avoid creating many distracting dependabot PRs
=> [701] Pin github actions to major version

monitoring/prometheus/alert.rules
We want to be alerted if we experience a high number of CSRF token errors in a short period of time (indicating an underlying issue somewhere).
=> Add a GSE alert for CSRF token errors

GetIntoTeachingApi/Models/GetIntoTeaching/Validators/TeachingEventSearchRequestValidator.cs, GetIntoTeachingApi/Services/Store.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/TeachingEventSearchRequestValidatorTests.cs, GetIntoTeachingApiTests/Services/StoreTests.cs
[Trello-3784](https://trello.com/c/pzop8GSN/3784-address-500-errors-served-on-event-search)
The validation is a bit strict at the moment; if you provide a radius but no postcode we throw an error. The front-end currently allows this scenario and it makes sense to allow it from a users perspective as well.
Relax validation to return all results if filtering by radius without specifying a postcode (so treating it as if they haven't filtered by distance in this use case).
=> Allow event search with radius but without postcode

GetIntoTeachingApi/AppStart/Startup.cs, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApi/Mocks/MockModel.cs, GetIntoTeachingApi/Mocks/MockRelatedModel.cs, GetIntoTeachingApi/Models/Crm/ApplicationChoice.cs, GetIntoTeachingApi/Models/Crm/ApplicationForm.cs, GetIntoTeachingApi/Models/Crm/ApplicationInterview.cs, GetIntoTeachingApi/Models/Crm/ApplicationReference.cs, GetIntoTeachingApi/Models/Crm/BaseModel.cs, GetIntoTeachingApi/Models/Crm/CallbackBookingQuota.cs, GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/Crm/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/Crm/CandidatePrivacyPolicy.cs, GetIntoTeachingApi/Models/Crm/CandidateQualification.cs, GetIntoTeachingApi/Models/Crm/CandidateSchoolExperience.cs, GetIntoTeachingApi/Models/Crm/PhoneCall.cs, GetIntoTeachingApi/Models/Crm/PrivacyPolicy.cs, GetIntoTeachingApi/Models/Crm/TeachingEvent.cs, GetIntoTeachingApi/Models/Crm/TeachingEventBuilding.cs, GetIntoTeachingApi/Models/Crm/TeachingEventRegistration.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj, GetIntoTeachingApiTests/Helpers/ContractTestOrganizationServiceAdapter.cs, GetIntoTeachingApiTests/Helpers/GitWebApplicationFactory.cs, GetIntoTeachingApiTests/Helpers/MockOrganizationServiceAdapter.cs, GetIntoTeachingApiTests/Models/Crm/BaseModelTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
WIP
[Trello-3790](https://trello.com/c/hlRw9nZ7/3790-update-property-changed-fluent-validation)
Various dependency updates
```
- CsvHelper 28.0.1 -> 29.0.0
- Microsoft.EntityFrameworkCore 6.0.9 -> 6.0.10
- Microsoft.EntityFrameworkCore.Design 6.0.8 -> 6.0.10
- Microsoft.EntityFrameworkCore.Tools 6.0.8 -> 6.0.10
- Microsoft.VisualStudio.Web.CodeGeneration.Design 6.0.8 -> 6.0.10
- Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite 6.0.6 -> 6.0.7
- Sentry.AspNetCore 3.21.0 -> 3.22.0
- Serilog.Settings.Configuration 3.3.0 -> 3.4.0
- Microsoft.Extensions.Caching.StackExchangeRedis 6.0.9 -> 6.0.10
- YamlDotNet 12.0.1 -> 12.0.2
- GovukNotify 6.0.0 -> 6.1.0
- Microsoft.AspNetCore.DataProtection.StackExchangeRedis 6.0.8 -> 6.0.10
- Microsoft.Extensions.DependencyInjection 6.0.0 -> 6.0.1
- …
```
=> Various dependency updates (inc major version bumps)

monitoring/prometheus/alert.rules
We can't avoid CSP errors entirely and it is currently triggering due to a bad plugin/extension in Edge. Increasing the threshold to silence the error whilst still hopefully being low enough to be useful.
=> Increase CSP violation threshold in app

.github/workflows/actions/deploy/action.yml, .github/workflows/build-no-cache.yml, .github/workflows/build.yml
https://trello.com/c/3s3iC7UV
The set-output command is being deprecated soon.
Resolution is to use $GITHUB_OUTPUT as per the workflow commands docs.
Confirm updated workflows tested where possible:
=> Stop using set-output in workflows

.github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml, Dockerfile, GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
[Trello-3958](https://trello.com/c/H470nG27/3958-upgrade-api-to-net-core-7)
- Various dependency updates
```
- CsvHelper 30.0.0 -> 30.0.1
- Hangfire.AspNetCore 1.7.31 -> 1.7.32
- Hangfire.Core 1.7.31 -> 1.7.32
- Sentry.AspNetCore 3.23.1 -> 3.24.0
- PropertyChanged.Fody 4.0.5 -> 4.1.0
- Newtonsoft.Json 13.0.1 -> 13.0.2
- Microsoft.PowerPlatform.Dataverse.Client 1.0.23 -> 1.0.26
- Microsoft.NET.Test.Sdk 17.3.2 -> 17.4.0
- WireMock.Net 1.5.0 -> 1.5.10
```
- Upgrade to .NET Core 7
Updates to the latest version of .NET Core. The only pre-release package we are using is for static code analysis and it looks like they're close to releasing the version with v7 support.
=> Upgrade to .NET Core 7

GetIntoTeachingApi/Adapters/CdsServiceClientWrapper.cs
We're seeing the current timeout of 15s being reached occasionally in production; increasing to 30s to see if it reduces the number of errors we get.
=> Increase CdsSeviceClient timeout

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Helpers/ContractCrmService.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
[Trello-3971](https://trello.com/c/7VSR35YO/3971-update-apply-api-matchback-to-use-apply-id-as-first-match-parameter)
When we sync candidates from the Apply service into the CRM we currently only matchback on email address. We need to do this initially, but once the candidate is in the CRM we could also matchback on the Apply candidate ID.
Going forward we want to matchback on the Apply candidate ID with precedence over the email address.
I've raised a separate ticket to clean up/automate some of our manual mock object creation. Testing interactions with the CRM is difficult enough as it is (we have to assert on the query expressions as we can't mock a Dynamics instance) and automating the mock creation should simplify the test cases a bit.
I'm not sure why the code coverage is reporting …
=> Matchback on apply ID if available

GetIntoTeachingApi/Jobs/FindApplyCandidateSyncJob.cs, GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApi/env.dev, GetIntoTeachingApi/env.prod, GetIntoTeachingApi/env.test, GetIntoTeachingApiTests/Contracts/ApplyCandidateApiTests.cs, GetIntoTeachingApiTests/Jobs/FindApplyCandidateSyncJobTests.cs
We don't want to matchback on Apply ID in production yet as there are still some open questions around which email we should take.
Wrap functionality in a feature switch and disable in production.
I noticed we're still using `launchSettings.json` to manage some local environment variables (such as feature switches). I've created a ticket to migrate these into the local dotenv, which is what we should be using going forward.
=> Feature switch matchback on Apply ID

GetIntoTeachingApi/Properties/launchSettings.json, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
[Trello-4008](https://trello.com/c/Lq1T6CgW/4008-migrate-local-env-vars-from-launchsettingsjson-to-envlocal)
Historically we used `launchSettings.json` to store non-sensitive, local environment variables. We have since introduced dotenv.net to manage our environment variables in `.env` files.
Migrate all local environment variables into `env.local`. Update the `Env` class to default the `CloudFoundryEnvironmentName` to `local` if the `VCAP_APPLICATION` environment variable is not set (this is a bit of a chicken/egg problem as the environment name is determined by the `VCAP_APPLICATION` environment variable, which isn't available until dotenv loads it).
The `ASPNETCORE_ENVIRONMENT` will remain in `launchSettings.json` as it needs to be set prior to the application booting.
=> Clean up local environment variables

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Database/DbConfiguration.cs, GetIntoTeachingApi/Redis/RedisConfiguration.cs, GetIntoTeachingApi/Services/HangfirePrometheusExporter.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs
[Trello-643](https://trello.com/c/jl71Wn2O/643-implement-a-fallback-for-when-the-crm-is-sending-errors-when-gse-tries-to-write-a-record)
By default we create GSE candidates in-band as the service needs the created `contact.id` from the CRM in order to match up the GSE candidate with the CRM contact.
When the CRM integration is paused (this happens for maintenance occasionally) we don't want to prevent GSE sign ups, so we fallback to generating a `contact.id` ahead of persisting it in the CRM and we queue the upsert operation.
We had an incident a number of weeks ago where the CRM was offline unexpectedly for a period of time without being 'paused' (which the CRM team do manually prior to scheduled maintenance). During this time GSE sign ups were failing as the CRM could not be reached. …
=> Queue GSE sign up when CRM is offline

GetIntoTeachingApi/env.dev
We are experiencing issues on the dev environment (its overloading the dev Apply candidate API). Disabling until we can fix it.
=> Disable Apply API integration

Dockerfile, GetIntoTeachingApi/Models/TeacherTrainingAdviser/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
[Trello-4062](https://trello.com/c/n5iRbaIL/4062-review-callback-quota-fallback-functionality-in-light-of-increased-demand)
Currently, if a candidate has an equivalent degree we require them to schedule a callback with an adviser. Going forward, we are allowing these candidates to sign up without a callback in the event that there are no available callback booking slots available.
Trying to enforce the validation rules for when there are no callback slots available would be error prone, given that the availability dynamically updates. Instead, we are going to relax the validation in the API and ensure its enforced in the client services.
=> Make phone call/telephone optional for equivalent degrees

GetIntoTeachingApi/Services/CallbackBookingService.cs, GetIntoTeachingApiTests/Services/CallbackBookingServiceTests.cs
[Trello-4062](https://trello.com/c/n5iRbaIL/4062-review-callback-quota-fallback-functionality-in-light-of-increased-demand)
Currently we have fallback logic so that if the CRM is offline or 0 callback slots are available we are still going to return a default set of slots that will allow candidates to continue their sign up.
We recently had an unexpected influx of TTA sign ups that were being offered callback booking slots and found we had no way to stem the flow of bookings (if we mark all slots as available the default slots would then be offered). We currently offer 14 days in advance, so the likelihood of all slots being booked are slim, but we want to account for the scenario in case it does happen in the future.
Update the callback service to only return fallback slots when the CRM …
=> Allow zero callback booking quotas to be returned

.github/workflows/build.yml
New buildx generates a new OCI format with support for provenance. It doesn't work with Cloud foundry.
=> Pin buildx to 0.9.1

GetIntoTeachingApi/Fixtures/clients.yml
The Apply service will be calling out to the API in order to sign up an Apply candidate for an adviser.
Add a client to the API configuration to support the Apply service. The relevant keys have already been added to the Azure keyvault for this client.
=> Add API client for Apply service

GetIntoTeachingApi/Controllers/CandidatesController.cs, GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/Models/CandidateMatchbackResponse.cs, GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Integration/RateLimitTests.cs, GetIntoTeachingApiTests/Models/CandidateMatchbackResponseTests.cs
[Trello-gOZOyWn1/4041](https://trello.com/c/gOZOyWn1/4041-spike-submitting-tta-applications-from-the-apply-service?filter=member:rossoliver15)
- Grant Apply access to adviser sign up
We are going to be accepting TTA sign ups from the Apply service going forward.
Grant access to the Apply service for TTA sign ups and candidate information.
- Add endpoint to retrieve existing candidate id
When a candidate signs up for a TTA via the Apply service they will already be 'authenticated' against the candidate email so we will not need to issue them a TOTP. Instead, we want to obtain a candidate id by providing matchback information.
- Setup rate limits for Apply service
Add rate limits for the adviser sign up from Apply service and also the new matchback endpoint as we're hitting the CRM.
=> Updates to support adviser sign up from apply

GetIntoTeachingApi/Models/TeacherTrainingAdviser/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
The Apply service will allow candidates to sign up with Maths/English GCSEs (and no Science GCSE) regardless of their preferred education stage, so we can relax this validation rule.
=> Relax GCSE science validation

GetIntoTeachingApi/GetIntoTeachingApi.csproj, terraform/paas/monitoring.tf
We are getting high memory warnings on the monitoring instance; increasing the available memory to give it some headroom.
=> Increase memory capacity for monitoring

GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs
We aren't getting an object back from the API client as the swagger definition didn't specify the response type.
=> Fix response type of matchback endpoint

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs, GetIntoTeachingApi/Program.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs
- Set global Regex timeout to 500ms to prevent potential DoS attack
- Swap `ToList` for `AsEnumerable`
- Remove redundant code
=> Address code climate warnings

GetIntoTeachingApi/Jobs/ClaimCallbackBookingSlotJob.cs, GetIntoTeachingApi/Jobs/LocationSyncJob.cs, GetIntoTeachingApi/Jobs/UpsertApplicationFormJob.cs, GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Jobs/UpsertModelWithCandidateIdJob.cs, GetIntoTeachingApiTests/Jobs/ClaimCallbackBookingSlotJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertApplicationFormJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertCandidateJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertModelWithCandidateIdJobTests.cs
Flagged by CodeClimate; the array here is redundant and we can just pass the labels directly.
=> Remove redundant array

GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_a_new_candidate_not_returning_equivalent_degree_primary_has_retaking_gcses_overseas.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_a_new_candidate_not_returning_equivalent_degree_secondary_has_gcses_is_in_uk.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_a_new_candidate_not_returning_has_degree_primary_has_gcses_in_the_uk_and_telephone.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_a_new_candidate_not_returning_has_degree_secodary_retaking_gcses_overseas_and_no_telephone.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_a_new_candidate_not_returning_studying_for_degree_final_year_overseas_and_telephone.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_a_new_candidate_not_returning_studying_for_degree_not_final_year_overseas_and_telephone.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_a_new_candidate_returning_no_teacher_reference_number_overseas_and_no_telephone.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_a_new_candidate_returning_teacher_reference_number_in_the_uk_and_telephone.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_an_existing_candidate_returning_existing_data_change_address.json, GetIntoTeachingApiTests/Contracts/Output/TeacherTrainingAdviser/sign_up_with_an_existing_candidate_when_in_a_closed_state_not_returning_existing_data_change_country.json, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs
[Trello-4151](https://trello.com/c/cYOL1Few/4151-clean-up-adviser-funnel-address-postcode-fields)
We no longer ask for the address line 1/2 and city as part of the adviser sign up; these fields can be removed.
=> Remove unused address fields from adviser sign up

GetIntoTeachingApi/Jobs/ApplyCandidateSyncJob.cs, GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/Crm/Validators/CandidateValidator.cs, GetIntoTeachingApi/Utils/Redactor.cs, GetIntoTeachingApiTests/Jobs/ApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/Crm/Validators/CandidateValidatorTests.cs
[Trello-4007](https://trello.com/c/U0JoQPO0/4007-dont-overwrite-contact-email-when-matching-on-apply-id)
When we matchback a candidate from the Apply service we use the Apply ID to ensure we get the correct CRM contact even if the email is different. Currently, we would overwrite the contact email address with the value from the Apply candidate, however going forward we want to give the CRM contact email precedence and retain it.
If the Apply candidate has a different email and there is no `SecondaryEmail` on the candidate we will write the Apply email to the `SecondaryEmail` field.
=> Ensure CRM email takes precedence over Apply

GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApiTests/Services/CrmServiceTests.cs
I'm not sure why but Dynamics doesn't like `IEnumerable` to be used as a condition value even though the method accepts it; it appears to need a concrete type so we call `ToList()` to avoid it throwing an error.
=> Fix error on email query from Dynamics

GetIntoTeachingApi/Models/Crm/BaseModel.cs, GetIntoTeachingApi/Models/Crm/Candidate.cs, GetIntoTeachingApi/Models/Crm/TeachingEventRegistration.cs, GetIntoTeachingApi/Services/CandidateUpserter.cs, GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs, GetIntoTeachingApiTests/Models/Crm/TeachingEventRegistrationTests.cs, GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs, README.md
[Trello-4304](https://trello.com/c/gjjriiec/4304-clean-up-basemodel-hooks-shift-into-candidateupserter)
- Remove ShouldMapRelationship hook
The `BaseModel` is complex and more so due to the available hooks. We have since centralised the candidate updating to the `CandidateUpserter` which makes the hooks redundant. Port the privacy policy hook over to the candidate upserter.
- Remove ShouldMap hook from BaseModel
The logic currently in the `ShouldMap` hooks can be moved into the `CandidateUpserter` to avoid overcomplicating an already complex class.
The only hook remaining in `BaseModel` is the `FinaliseEntity` hook, which can't be removed as it operates on the encapsulated CRM entity.
=> Clean up BaseModel hooks

GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs
We want to show a different UI to candidates in Apply based on their adviser assignment status; in order to do that we need to expose it from the API.
=> Expose adviser assignment status

GetIntoTeachingApi/Models/Validators/ExistingCandidateRequestValidator.cs, GetIntoTeachingApiTests/Models/Validators/ExistingCandidateRequestValidatorTests.cs
[Trello-4360](https://trello.com/c/IfbKWsDm/4360-investigate-400-error-on-adviser-sign-up-from-apply) 
Historically the matchback was more stringent and required a first/last name or DOB to match as well as email. It has since been updated to fallback to only matching on email address, although all existing services will also send a first/last name.
Now that Apply offers an adviser sign up the matchback can happen without a first/last name and the API raises an error. Relaxing this validation will prevent the error and not change the underlying functionality (as we fallback to an email only matchback anyway).
=> Relax ExistingCandidateRequest validation

GetIntoTeachingApi/Services/CandidateUpserter.cs
We are checking the `IsNewRegistrant` field before it is set and so we occasionally see an error where the `candidate.Id` is `null` and we try and cast it to a `Guid`.
=> Fix bug in CandidateUpserter

GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs
[Trello-4363](https://trello.com/c/Tg9tgd58/4363-investigate-apply-adviser-sign-up-issues)
Currently, if a candidate has a degree or is returning to teaching we will put them in the queue to be assigned to an adviser. Other candidates (with an equivalent degree) are taken on a journey to schedule a callback on the main TTA service.
If an international candidate signs up from Apply we do not offer the callback service and they aren't put in the queue for an adviser, so they will fall between the cracks. Going forward we want to queue these candidates for an adviser. To that end, the logic around this can be simplified to 'if a candidate has not booked a callback, put them in the queue for an adviser'.
=> Update adviser assignment logic

GetIntoTeachingApi/AppStart/Startup.cs, GetIntoTeachingApi/Auth/HangfireDashboardEnvironmentAuthorizationFilter.cs, GetIntoTeachingApiTests/Auth/HangfireDashboardEnvironmentAuthorizationFilterTests.cs
We need to cancel a job in-progress; doing this in code is not straight forward so enabling the dashboard (behind authentication) in production to allow us to cancel it.
I've updated the production keyvault with secure credentials. This can be disabled again once we have successfully ran the backfill job.
=> Enable Hangfire dashboard in production

GetIntoTeachingApi/Jobs/ApplyBackfillJob.cs, GetIntoTeachingApi/Jobs/ApplyCandidateSyncJob.cs, GetIntoTeachingApi/Jobs/UpsertApplicationFormJob.cs, GetIntoTeachingApiTests/Contracts/ApplyCandidateApiTests.cs, GetIntoTeachingApiTests/Jobs/ApplyBackfillJobTests.cs, GetIntoTeachingApiTests/Jobs/ApplyCandidateSyncJobTests.cs, GetIntoTeachingApiTests/Jobs/UpsertApplicationFormJobTests.cs
There is an issue in production where the Apply jobs are getting re-queued continuously by a failing bulk job; making the apply jobs empty will let the runners clear them down.
=> Clear down all apply jobs

GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApi/Jobs/ApplyBackfillJob.cs, GetIntoTeachingApi/Jobs/BaseJob.cs, GetIntoTeachingApi/Services/IPaginatorClient.cs, GetIntoTeachingApi/Services/PaginatorClient.cs, GetIntoTeachingApiTests/Jobs/ApplyBackfillJobTests.cs, GetIntoTeachingApiTests/Services/PaginatorClientTests.cs
When we ran the `ApplyBackfillJob` in production it took longer than 30 minutes to complete and resulted in the job timing out and retrying (which reqeueud a high number of duplicate jobs).
As the Apply candidate API does not let us query a date range we are instead going to chain the backfill jobs so that each one processes a subset of pages and re-queues for the next set. Whilst we could do this concurrently we want to avoid putting too much load on the Apply candidate API, so sequentially is a better fit.
The delay in processing the queued `ApplyCandidateSyncJob` has also been increased to two hours, which should let us more easily monitor the backfill job progress.
=> Daisy-chain ApplyBackfillJob

GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
[Trello-4378](https://trello.com/c/v7zsQVLT/4378-fix-slow-production-db-issues)
We recently performed an Apply backfill in production which has resulted in many more records being in the database than usual. The logs indicate the Hangfire exporter is perhaps running an inefficient query and flooding the database with requests it can't keep up with.
Disable Hangfire Prometheus exporter in all environments.
=> Disable Hanfire Prometheus metrics exporter

GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs
We can't currently differentiate between TTA sign ups from the get an adviser service and apply; adding this log line for a quick way to track the sign ups on rolling out the feature.
=> Add logging to track TTA sign ups

GetIntoTeachingApi/Auth/HangfireDashboardEnvironmentAuthorizationFilter.cs, GetIntoTeachingApiTests/Auth/HangfireDashboardEnvironmentAuthorizationFilterTests.cs
[Trello-4412](https://trello.com/c/MxAmntgn/4412-disable-hangfire-dashboard-in-production)
We enabled this (behind basic auth) to more easily monitor the Apply backfill job. Re-disabling it now that's finished.
=> Disable Hangfire dashboard in production

GetIntoTeachingApi/Models/Validators/ExistingCandidateRequestValidator.cs, GetIntoTeachingApiTests/Models/Validators/ExistingCandidateRequestValidatorTests.cs
[Trello-4372](https://trello.com/c/iDqBrbp4/4372-clean-up-existingcandidaterequest-model)
We only use the email address in the matchback logic itself, but we reference the candidate by their first name in the email that we send out with their access code; we need to retain this field/ensure make it mandatory.
=> Require first name on matchback

GetIntoTeachingApi/Utils/Env.cs, GetIntoTeachingApiTests/Utils/EnvTests.cs
Reverts DFE-Digital/get-into-teaching-api#1209
I think this was just an issue due to the unusually high volumes of jobs we queued up during the recent Apply backfill operation; reverting it so we get job metrics back in production.
=> Revert "Disable Hanfire Prometheus metrics exporter"

GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs, GetIntoTeachingApi/appsettings.json, GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs, GetIntoTeachingApiTests/Integration/RateLimitTests.cs
[Trello-4444](https://trello.com/c/0PFn0Tb7/4444-spike-investigate-moving-the-adviser-funnel-to-git)
We are planning on migrating the TTA service into the GiT website. For the spike the GiT app needs to be able to submit to the TTA endpoints; once we're happy with the solution the API namespaces will be updated to reflect the TTA service migration into GiT.
=> Grant GetIntoTeaching role access to adviser sign up

GetIntoTeachingApi/Services/Store.cs
[Trello-4471](https://trello.com/c/6EQ4yqig/4471-consider-increasing-period-for-which-api-syncs-events)
We currently only sync events going back 4 months and we are finding that users are coming across old links to past events from external sources, resulting in a 404 not found error. Instead, if the event did exist but has since passed we would be better to serve a 410 gone with a better error message for the user. The GiT website does this already, but only as far back as the API is syncing; increasing this to 12 months to avoid 404s on recently(ish) past events.
I've tested the sync job locally and it doesn't make it significantly longer.
=> Sync events over the last 12 months

GetIntoTeachingApi/Models/Validators/TeachingEventBuildingValidator.cs, GetIntoTeachingApiTests/Models/Validators/TeachingEventBuildingValidatorTests.cs
Teaching Event Buildings should always have a Venue name and a Postcode.
=> Add Teaching Event Building validator

GetIntoTeachingApi/GetIntoTeachingApi.csproj, GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
[Trello-4739](https://trello.com/c/9hjifceg/4739-carry-out-dependency-updates)
Updates
Bump Microsoft.NET.Test.Sdk from 17.6.0 to 17.6.3
Bump Hangfire.AspNetCore from 1.8.1 to 1.8.3
Bump Serilog from 2.12.0 to 3.0.1
Bump Microsoft.VisualStudio.Web.CodeGeneration.Design from 7.0.6 to 7.0.7
Bump Microsoft.PowerPlatform.Dataverse.Client from 1.0.39 to 1.1.9
=> Bump up versions of the libraries

terraform/aks/databases.tf
Update the azure redis max memory policy to allkeys-lfu to match PAAS redis
Updated the azure_maxmemory_policy var to "allkeys-lfu" as existing in PAAS in terraform/aks/databases.tf
See the updated azure max memory policy for s189t01-gitapi-development-redis 
NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml
=> Update Azure Redis Max Memory policy

.github/workflows/build-and-deploy.yml
It was pinned to 0.9.1 for compatibility with GOV.UK PaaS. Now that we run on AKS, this limitations does not apply and we can use the default version.
=> [669] Update the buildx action

GetIntoTeachingApi/Adapters/NotificationClientAdapter.cs, GetIntoTeachingApi/Controllers/GetIntoTeaching/TeachingEventsController.cs, GetIntoTeachingApi/Models/Crm/CandidatePastTeachingPosition.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs, GetIntoTeachingApi/Models/TeacherTrainingAdviser/Validators/TeacherTrainingAdviserSignUpValidator.cs, GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
New (optional) StageTaughtId parameter + updated tests
This adds support for an improved RTTA process to capture interest in primary stage teaching
Requires changes to be pulled through into https://github.com/DFE-Digital/get-into-teaching-api-ruby-client and https://github.com/DFE-Digital/get-into-teaching-api-csharp-client
=> Add support for Primary education phase

terraform/aks/config/production_aks.tfvars.json
The database was maxing out CPU and ran out of credits. It was upgraded manually which is looking good since CPU credits are now slowly increasing.
Run terraform plan, it should show no change
=> [853] Upgrade postgres to B_Standard_B2s

terraform/aks/config/production_aks.tfvars.json
**Context**
The database was stuck at 100% CPU which created outages in school experience. We should enable monitoring to know before it breaks.
**Change**
Set 'enable_monitoring' to 'true' in the configuration for production
=> Enable DB monitoring

.github/workflows/actions/deploy_v2/action.yml, Makefile, terraform/aks/.terraform.lock.hcl, terraform/aks/provider.tf
Trello card
https://trello.com/c/3m8PNLG6/937-enable-azure-rbac-deployment-on-all-services
Context
Enable azure rbac on deployment (for when it is enabled in the cluster)
Changes proposed in this pull request
Update Makefile, terraform and workflows to use rbac if configured for the cluster
Guidance to review
make env terraform-plan
=> Added  RBAC to project

Dockerfile
Revert "Bump dotnet/aspnet from 7.0-alpine to 8.0-alpine (#1322)"
This reverts commit af9e32213116f100375f8624489cd872f534fa64.
Revert "Bump dotnet/sdk from 7.0-alpine to 8.0-alpine (#1323)"
This reverts commit 2bef8d8fad01e5ea9ed835f217ad3da006dfde89.
=> Reverts alpine:8.0 upgrade

docs/index.md
This adds a link to the Swagger docs detailing the API methods and parameters
=> Add link to swagger docs

.github/common_environment.yml
This adds a blank `SENTRY__DSN=""` env var for use during github build and test steps.
A forthcoming update to the Sentry library requires to DSN to be set to an empty string, rather than remaining undefined.
The Sentry DSN is set to real values on production and staging.
=> Add a blank Sentry DSN for github build steps

.github/common_environment.yml
=> Rename SENTRY__DSN to Sentry__Dsn

terraform/aks/provider.tf
Hardcode Azurerm version to 3.104.2 as later versions cause "Public Network Access is not supported along with Virtual Network feature." errord
=> Hardcode azurerm version to 3.104.2

.github/workflows/trello.yml
This adds a missing `trello-key` to the github action, allowing for trello tickets to be linked to github PRs
=> Add trello key to workflow action

GetIntoTeachingApi/Properties/launchSettings.json, README.md
Small update to the docs about running the API locally with local app
Trello ticket: https://trello.com/c/dFV0X4SU/5841-update-technical-documentation-for-api
=> update docs + sentry_dsn for dev

terraform/aks/application.tf, terraform/aks/config/development_aks.tfvars.json, terraform/aks/config/test_aks.tfvars.json, terraform/aks/variables.tf
Ship web and worker application logs to Logit.io. Enabled for non-prod environments first
make development_aks terraform-plan
=> Onboard test envs to logit

terraform/aks/application.tf, terraform/aks/config/development_aks.tfvars.json, terraform/aks/config/production_aks.tfvars.json, terraform/aks/config/test_aks.tfvars.json, terraform/aks/variables.tf
Scrape custom metrics that are exported for gitapi,
which can then be used in dashboards and alerting
https://trello.com/c/Zlih3dRZ/1889-scrape-custom-metrics 
Add enable_prometheus_monitoring to application deployments and set for each env
make development_aks terraform-plan IMAGE_TAG=x
This has been deployed manually to dev & test envs and metrics are available in test prometheus (look for metrics starting with api)
Some metrics (e.g. hangfire) are possibly not being exported, and that may need follow up with the dev team.
=> Scrape custom metrics

terraform/aks/config/production_aks.tfvars.json
Terraform Plan : 
` Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
~ update in-place
<= read (data resources)
Terraform will perform the following actions:
~ resource "kubernetes_deployment" "main" {
id               = "git-production/getintoteachingapi-production"
~ spec {
~ template {
~ metadata {
~ annotations = {
+ "prometheus.io/path"   = "/metrics"
+ "prometheus.io/port"   = "8080"
+ "prometheus.io/scrape" = "true"
}
}
}
}
}
<= data "azurerm_monitor_diagnostic_categories" "main" {
+ id                  = (known after apply)
+ log_category_groups = (known after apply)
+ log_category_types  = (known after apply)
+ logs                = (known after apply)
+ metrics             = (known after …
=> Added maintenance window for prod postgress

.github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml, README.md
Fix issue with build pipeline - [see this discussion](https://github.com/orgs/community/discussions/116610)
=> Update docker-compose to docker compose

GetIntoTeachingApi/Controllers/OperationsController.cs, GetIntoTeachingApi/Jobs/ApplyBackfillJob.cs, GetIntoTeachingApi/Models/CandidateIdsRequest.cs, GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs, GetIntoTeachingApiTests/Jobs/ApplyBackfillJobTests.cs, GetIntoTeachingApiTests/Models/CandidateIdsRequestTests.cs
Adds a new endpoint, `/api/operations/backfill_apply_candidates_from_ids` for triggering a synchronise with the Apply system for a specific Candidate ID.
See trello ticket: https://trello.com/c/xcork9SB/6409-backfill-missing-data-from-apply-into-the-crm
=> New endpoint for synchronising by candidate ID

GetIntoTeachingApi/Jobs/UpsertCandidateJob.cs, GetIntoTeachingApi/Models/SchoolsExperience/SchoolsExperienceSignUp.cs, GetIntoTeachingApi/Services/CandidateUpserter.cs, GetIntoTeachingApi/Services/CrmService.cs, GetIntoTeachingApi/Services/ICrmService.cs, GetIntoTeachingApiTests/Helpers/ContractCrmService.cs, GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs
This change improves the synchronisation of qualification records:
* adds checks to ensure a qualification record is not re-created if it already exists
* creates qualification records immediately, rather than via a queued job
=> Prevent duplicate degree subject

GetIntoTeachingApi/Models/Crm/ApplicationChoice.cs
This new status is required by the Apply system to synchronise correctly.
It is currently being added to the CRM system too.
=> Add `inactive` status to ApplicationChoice.cs

GetIntoTeachingApi/Middleware/RequestResponseLoggingMiddleware.cs, GetIntoTeachingApiTests/Middleware/RequestResponseLoggingMiddlewareTests.cs
Remove request logging from the API - requested by infra team to reduce logging volumes.
=> Remove request logging from API

GetIntoTeachingApi/Models/GetIntoTeaching/MailingListAddMember.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/MailingListAddMemberTests.cs, GetIntoTeachingApiTests/Models/GetIntoTeaching/Validators/MailingListAddMemberValidatorTests.cs
Adds Creation Channel to the mailing list end point
https://trello.com/c/iVQSw2yD/7071-update-git-api-to-support-new-creation-channel-structure-for-subscription-data-e11-gc3
=> Add mailing list creation channel

.github/workflows/build-and-deploy.yml, .github/workflows/build-no-cache.yml, .github/workflows/pull_request.yml, .github/workflows/sonarcloud.yml, .github/workflows/trello.yml
https://trello.com/c/CAZOMOph/2294-remove-kv-secrets-from-build-and-test-workflow
Move workflow only secrets from azure keyvault to github secrets.
This removes the github environment from non deploy steps, and makes more sense for a workflow secret.
Updates to workflows
Check workflows all run correctly for this PR
manual build-no-cache: https://github.com/DFE-Digital/get-into-teaching-api/actions/runs/13942519391
=> Move workflow secrets to github

GetIntoTeachingApi/Controllers/GetIntoTeaching/MailingListController.cs, GetIntoTeachingApi/Models/Crm/DegreeStatusInference/IInferDegreeStatus.cs, GetIntoTeachingApi/Models/Crm/DegreeStatusInference/Readme.txt, GetIntoTeachingApi/Models/GetIntoTeaching/MailingListAddMember.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/MailingListControllerTests.cs, GetIntoTeachingApiTests/Controllers/GetIntoTeaching/PartialIntegration/MailingListControllerTests.cs
Some small changes to allow the degree status Id to be returned by the **MailingList** Service, **AddMember** endpoint. This change is required to support third-party service requirements which use degree status to drive marketing etc.
=> Changes to allow degree status (inferred or otherwise) to be returned by the service endpoint.
