DFE-Digital/get-into-teaching-api

terraform/paas/test.env.tfvars

Corrected the test names, to reduce conflicts

corrected names

---

.github/workflows/dockerbuild.yml
terraform/paas/backend.tf
terraform/paas/variables.tf

Forgot that you cannot use variables in terraforms backend.

Forgot you cannot use a variable

---

GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs
GetIntoTeachingApi/Database/GetIntoTeachingDbContext.cs
GetIntoTeachingApi/Models/PrivacyPolicy.cs
GetIntoTeachingApi/Models/Validators/CandidatePrivacyPolicyValidator.cs
GetIntoTeachingApi/Models/Validators/CandidateValidator.cs
GetIntoTeachingApi/Services/CrmService.cs
GetIntoTeachingApi/Services/ICrmService.cs
GetIntoTeachingApi/Services/IStore.cs
GetIntoTeachingApi/Services/Store.cs
GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs
GetIntoTeachingApiTests/Models/PrivacyPolicyTests.cs
GetIntoTeachingApiTests/Models/Validators/CandidatePrivacyPolicyValidatorTests.cs
GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs
GetIntoTeachingApiTests/Services/CrmServiceTests.cs
GetIntoTeachingApiTests/Services/StoreTests.cs

We currently cache privacy policies in-memory; this PR will sync policies daily into Postgres.

Sync privacy policies to Postgres

---

GetIntoTeachingApi/Controllers/TypesController.cs
GetIntoTeachingApi/Database/DbConfiguration.cs
GetIntoTeachingApi/Startup.cs

We need to debug what's going on in production by logging out the environment.

Temporarily log out environment variables

---

GetIntoTeachingApi/Database/GetIntoTeachingDbContext.cs
GetIntoTeachingApi/Migrations/20200609110318_InitialCreate.Designer.cs
GetIntoTeachingApi/Migrations/20200609110318_InitialCreate.cs
GetIntoTeachingApi/Migrations/GetIntoTeachingDbContextModelSnapshot.cs

The extension is already setup in production, so loading it here as well throws an exception.

Remove Postgis extension

---

README.md
monitoring/alertmanager/alertmanager.yml
monitoring/alertmanager/manifest.yml
monitoring/grafana/datasources/prometheus.yml
monitoring/grafana/manifest.yml
monitoring/prometheus/alert.rules
monitoring/prometheus/manifest.yml
monitoring/prometheus/prometheus.yml

I have added the manual configuration for Grafana and Prometheus, ( Alertmanager is included but not configured )
These are place holders with working configuration. The future plan is to implement the logging using terraform. and only store the configuration locally.

Basic Metric Collection Configured

---

GetIntoTeachingApi/GetIntoTeachingApi.csproj

We're seeing a connection leak in the test environment; downgrading to see if it's related to the version we're using.

Downgrade Hangfire PostgreSql

---

GetIntoTeachingApi/GetIntoTeachingApi.csproj

This may fix our connection leak issue

Update Hangfire Postgres to 1.7

---

GetIntoTeachingApi/Database/DbConfiguration.cs
GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApiTests/Database/DbConfigurationTests.cs

The Postgres provider we were using for Hangfire seems to be leaking connections - trying this one to see if it's more stable.

Switch Hangfire Postgres provider

---

.github/workflows/sonarcloud.yml
GetIntoTeachingApi/Controllers/CallbackBookingQuotasController.cs
GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs
GetIntoTeachingApi/Jobs/LocationSyncJob.cs
GetIntoTeachingApi/Models/Candidate.cs
GetIntoTeachingApi/Models/Validators/CandidatePrivacyPolicyValidator.cs
GetIntoTeachingApi/Program.cs
GetIntoTeachingApi/Services/CrmService.cs
GetIntoTeachingApi/Services/ICrmService.cs

Add GitHub workflow to run SonarCloud - currently failing, from what I gather it's because the master branch has not been analyzed yet -- if we merge this down it _should_ analyze the master branch and make this go away:
```
Caused by: Could not find a default branch to fall back on.
```

Run dotnet-sonarscanner

---

.github/workflows/dockerbuild.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/sonarcloud.yml
terraform/paas/backend.tf
terraform/paas/dev.bk.vars
terraform/paas/test.bk.vars

Alerting added to sentry.io when a job completes regardless of status
Terraform build to dev added as well as test on release

Added messaging

---

.github/workflows/dockerbuild.yml
.github/workflows/release.yml

Used correct TF_STATE_KEY

---

GetIntoTeachingApi/Controllers/TeacherTrainingAdviser/CandidatesController.cs
GetIntoTeachingApi/Models/Candidate.cs
GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs
GetIntoTeachingApi/Models/CandidateQualification.cs
GetIntoTeachingApi/Models/MailingListAddMemberRequest.cs
GetIntoTeachingApi/Models/PhoneCall.cs
GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUpRequest.cs
GetIntoTeachingApi/Models/Validators/CandidateValidator.cs
GetIntoTeachingApiTests/Controllers/TeacherTrainingAdviser/CandidatesControllerTests.cs
GetIntoTeachingApiTests/Models/CandidatePastTeachingPositionTests.cs
GetIntoTeachingApiTests/Models/CandidateQualificationTests.cs
GetIntoTeachingApiTests/Models/CandidateTests.cs
GetIntoTeachingApiTests/Models/MailingListAddMemberRequestTests.cs
GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpRequestTests.cs
GetIntoTeachingApiTests/Models/TeachingEventAddAttendeeRequestTests.cs
GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs

Simplify the payload for TTA sign up - hidden fields will be determined by the API in a future PR, however some are currently hardcoded until we can work out behaviour with the CRM team:
https://dfedigital.atlassian.net/browse/GITPB-450

Add request model for TTA sign up

---

GetIntoTeachingApi/Controllers/TypesController.cs
GetIntoTeachingApi/Models/Candidate.cs
GetIntoTeachingApi/Models/CandidateQualification.cs
GetIntoTeachingApi/Models/PhoneCall.cs
GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs
GetIntoTeachingApi/Models/Validators/CandidateValidator.cs
GetIntoTeachingApi/Models/Validators/MailingListAddMemberValidator.cs
GetIntoTeachingApi/Models/Validators/PhoneCallValidator.cs
GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs
GetIntoTeachingApi/Models/Validators/TeachingEventAddAttendeeValidator.cs
GetIntoTeachingApi/Services/Store.cs
GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs
GetIntoTeachingApiTests/Models/PhoneCallTests.cs
GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs
GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs
GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberValidatorTests.cs
GetIntoTeachingApiTests/Models/Validators/PhoneCallValidatorTests.cs
GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs
GetIntoTeachingApiTests/Models/Validators/TeachingEventAddAttendeeValidatorTests.cs
GetIntoTeachingApiTests/Services/StoreTests.cs

- Make validation for TTA journey more robust
- Remove PhoneCall DestinationId
We are no longer asking for this field in the TTA journey.

Validation for Teacher Training Adviser sign up

---

.github/workflows/cve.yml
.github/workflows/dockerbuild.yml

Incorporating a CVE Scanner just to ensure security is so happy it cries

Incorporated CVE Scanner

---

README.md

Clarify how validators are structured.
Note Spatialite dependency for non-Windows installations.

Update README.md with validation details

---

GetIntoTeachingApi/Models/Candidate.cs
GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs
GetIntoTeachingApi/Models/Validators/CandidateValidator.cs
GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs
GetIntoTeachingApiTests/Models/CandidateTests.cs
GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs
GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs
GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs

AddressLine3 and AddressState are not collected by the front-end.

Remove unused address fields

---

GetIntoTeachingApi/Models/CandidateQualification.cs
GetIntoTeachingApi/Models/MailingListAddMember.cs
GetIntoTeachingApi/Models/Validators/MailingListAddMemberValidator.cs
GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs
GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs
GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberValidatorTests.cs

Also makes most fields optional for the mailing list and adds 'Other' as an option to candidate qualification degree status (for studying).

Collect DegreeStatusId instead of UkDegreeGradeId for mailing list

---

GetIntoTeachingApi/Controllers/TypesController.cs
GetIntoTeachingApi/Models/Candidate.cs
GetIntoTeachingApi/Models/MailingListAddMember.cs
GetIntoTeachingApi/Models/Validators/CandidateValidator.cs
GetIntoTeachingApi/Models/Validators/MailingListAddMemberValidator.cs
GetIntoTeachingApi/Services/Store.cs
GetIntoTeachingApiTests/Controllers/TypesControllerTests.cs
GetIntoTeachingApiTests/Models/CandidateTests.cs
GetIntoTeachingApiTests/Models/MailingListAddMemberTests.cs
GetIntoTeachingApiTests/Models/Validators/CandidateValidatorTests.cs
GetIntoTeachingApiTests/Models/Validators/MailingListAddMemberValidatorTests.cs
GetIntoTeachingApiTests/Services/StoreTests.cs

We no longer want to collect this in the mailing list sign up journey, so it can be removed.

Remove DescribeYourselfId

---

GetIntoTeachingApi/Controllers/PrivacyPoliciesController.cs
GetIntoTeachingApi/Services/IStore.cs
GetIntoTeachingApi/Services/Store.cs
GetIntoTeachingApiTests/Controllers/PrivacyPoliciesControllerTests.cs
GetIntoTeachingApiTests/Controllers/TeachingEventsControllerTests.cs
GetIntoTeachingApiTests/Services/StoreTests.cs

We need to be able to query a specific privacy policy on the front-end so that we can ensure the policy we display to the user is the one that they end up accepting.

Add endpoint to retrieve PrivacyPolicy by id

---

.github/workflows/dockerbuild.yml
.github/workflows/release.yml
tests/confidence/healthcheck.sh

Simple test script which will curl the application health check URL and check the SHA is what is expected.
Additionally it will check the status of the health check
All done in glorious technicolour

Added Simple Smoke test

---

GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs
GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs

If a Candidate has a degree equivalent we ask them for their preferred education phase, however we do not ask them about their GCSEs, so this should not be mandatory. We also don't ask them about degree subject or uk degree grade, so these attributes should also be optional.

Relax validation on TTA sign up

---

monitoring/grafana/dashboards/get_into_teaching_api.json

Add cache hit ratio/google api calls

---

terraform/paas/application.tf
terraform/paas/dev.env.tfvars
terraform/paas/production.env.tfvars
terraform/paas/variables.tf

Adding some additional variables for deployment to enable scaleability

Adding Instances variables

---

monitoring/grafana/dashboards/logs.json
terraform/monitoring/manual.test.sh
terraform/monitoring/postgres.tf
terraform/monitoring/redis.tf
terraform/monitoring/test.env.tfvars

Add monitoring

---

.github/workflows/monitoring.yml
Dockerfile

Added apt-get commands to update the distribution of Ubuntu within the dockerfile.
This clears the CVE

Updated Distribution

---

.github/workflows/cve.yml

Added ability to manually execute
Added saving of report as artefact

Improving execution

---

GetIntoTeachingApi/Models/TeachingEvent.cs
GetIntoTeachingApi/Models/Validators/TeachingEventRegistrationValidator.cs
GetIntoTeachingApiTests/Models/TeachingEventTests.cs
GetIntoTeachingApiTests/Models/Validators/TeachingEventRegistrationValidatorTests.cs

Reverts DFE-Digital/get-into-teaching-api#210

Revert "Add WebFeedId to TeachingEvent and prevent sign ups if null"

---

GetIntoTeachingApi/Models/CallbackBookingQuota.cs
GetIntoTeachingApiTests/Models/CallbackBookingQuotaTests.cs
GetIntoTeachingApiTests/Services/CrmServiceTests.cs

These have been updated in Dynamics - renaming here to be consistent.

Rename CallbackBookingQuota attributes

---

.github/workflows/dockerbuild.yml
.github/workflows/monitoring.yml
.github/workflows/release.yml

Added Terraform Version

---

.github/workflows/dockerbuild.yml
.github/workflows/monitoring.yml
.github/workflows/release.yml

changed 12.28 to 12.29

---

.github/workflows/ur.yml
terraform/paas/ur.bk.vars
terraform/paas/ur.env.vars

Creating new UR Environment
The YAML file in github should run from workflow user triggering, and should call terraform with ur.xxxx 
The terraform has 2 new files:
1. backend to store state, it must be ur rather than test or dev
2. The names of the applications/services in the second file must be ur rather than test or dev

Adding UR environment

---

.github/workflows/ur.yml

Adding missing version control setting

---

terraform/paas/ur.env.tfvars

Logging already exists in this space because of the other application, so should be disabled for this version

Removed Logging (already added in space)

---

terraform/paas/application.tf
terraform/paas/services.tf

Previously I had added redis to the API but it wasnt required.
I left it there but have now run out of resources so need to clamber it back

Previous Redis Service needs removing

---

.github/workflows/prod_statuscake.yml
.github/workflows/production.yml
terraform/paas/production.bk.vars
terraform/paas/production.env.tfvars
terraform/paas/services.tf
terraform/paas/variables.tf
terraform/paas/versions.tf
terraform/statuscake/production.bk.vars
terraform/statuscake/production.env.tfvars
terraform/statuscake/versions.tf

The API is required for all of the services to run, and therefore it's deployment has been designated master. 
Thus this is where we deploy logging, and other common resources from.
Once the API has been sucessfully tested the TTA and APP can layer on top

Initial Production Build

---

.github/workflows/dockerbuild.yml
.github/workflows/production.yml
.github/workflows/release.yml

SENTRY URL variable was not being set in any environment

Added Sentry secret

---

.github/workflows/dockerbuild.yml
.github/workflows/monitoring_prod.yml
.github/workflows/production.yml
.github/workflows/release.yml

Monitoring Pipelines added to deploy monitoring to DEV and PROD.

Monitoring Pipelines Added

---

.github/workflows/monitoring.yml
.github/workflows/monitoring_prod.yml

Add the CloudFoundry provider to the workflow ( needed in V12 of terraform)

Require Cloud Foundry Provider

---

.github/workflows/monitoring.yml
terraform/monitoring/grafana.tf
terraform/monitoring/variables.tf

Added Variables

---

.github/workflows/monitoring.yml
terraform/monitoring/grafana.tf
terraform/monitoring/variables.tf

Added google secrets to secret store

Google Client Keys Added

---

terraform/statuscake/backend.tf
terraform/statuscake/resources.tf
terraform/statuscake/test.env.tfvars

Ran 'terraform fmt' on terraform files to improve their format

Statuscake Terraform Tidyup of format

---

.github/workflows/monitoring.yml

Automatcially running my trash peoples work

removed automatic deploy for development monitoring

---

.github/workflows/production.yml
.github/workflows/release.yml

Production and Test Workflows changed

Test and Production to terraform 13.4

---

terraform/paas/test.env.tfvars

Increase the number of Instances to 2 on the API in QA to see if we can reproduce a bug on live

Increases Instances of API to 2 on QA

---

.github/workflows/monitoring_prod.yml
.github/workflows/statuscake.yml
terraform/statuscake/provider.tf
terraform/statuscake/versions.tf

Statuscake Terraform updated to 13.4

Devops/statuscake/terraform 13.4

---

monitoring/grafana/runtime.txt
terraform/monitoring/modules.tf

Pass version is as a parameter

---

monitoring/grafana/dashboards/get_into_teaching_api.json

- Updates various panels to the Grafana 7 version.
- Fixes bugs in some of the metrics.

Upgrade for Grafana 7

---

monitoring/alertmanager/alertmanager.yml
monitoring/prometheus/alert.rules
terraform/monitoring/modules.tf

Added simple Alertmanager call

Alertmanager Added

---

GetIntoTeachingApi/Controllers/TeachingEventsController.cs

To keep it consistent throughout.

Rename category to type

---

.github/workflows/dockerbuild.yml
.github/workflows/production.yml
.github/workflows/release.yml
terraform/paas/application.tf
terraform/paas/variables.tf

Docker have decided to limit anonymous pulls which can effect the UK Gov PaaS

Add Credentials to Docker Deploy

---

monitoring/prometheus/alert.rules

Reverts DFE-Digital/get-into-teaching-api#333
This test worked ^ it takes a few minutes to propagate and I wasn't shipping the right monitoring action last time 🤦

Revert "Test changing alert rule"

---

monitoring/prometheus/alert.rules

My new alert rules aren't appearing, I think it's because the expressions aren't right so testing the rest of the config with the example expression.

Test alert manager config

---

monitoring/prometheus/alert.rules

Alert when high 404's are happening on the app.

Add HighNotFound alert rule

---

monitoring/grafana/dashboards/get_into_teaching_apps.json
monitoring/prometheus/alert.rules

Add CPU/Memory utilisation to the app/tta dashboards.

Add system metrics to app/tta dashboards

---

monitoring/grafana/datasources/elasticsearch.yml.tmpl
monitoring/grafana/grafana.ini
monitoring/prometheus/alert.rules
monitoring/prometheus/prometheus.yml.tmpl
terraform/monitoring/modules.tf
terraform/monitoring/variables.tf

The central repository of Becoming A Teacher building blocks has changed with some of the features developed for GiT being made available to other teams.
Since these features are now in the central repository they can be removed from this local version

Made changes to bring in line with Becoming A teacher

---

GetIntoTeachingApi/appsettings.json

This configuration is in the file twice; removing the duplicate.

Remove duplicated rate limit

---

monitoring/grafana/dashboards/README.md
monitoring/grafana/dashboards/cf_overview.json
monitoring/grafana/dashboards/influxdb.json

Added Some new dashboards

---

monitoring/grafana/dashboards/cf_overview.json

Exported the wrong way, so it isnt working very well with method of delivery

Changed the Export

---

GetIntoTeachingApi/Properties/launchSettings.json

These have been committed accidentally; we'll need to cycle them.

Remove development credentials

---

GetIntoTeachingApi/Models/Location.cs
GetIntoTeachingApi/Models/Validators/TeachingEventSearchRequestValidator.cs
GetIntoTeachingApiTests/Models/Validators/TeachingEventSearchRequestValidatorTests.cs
GetIntoTeachingApiTests/Services/StoreTests.cs

- Update regex for postcodes
- Add to list of postcode parameters in validation tests
- Add store test for outward postcode

Update event search validation to allow area only postcode

---

terraform/paas/application.tf

Added bind from API Application to REDIS database in terraform

Bind to Redis

---

GetIntoTeachingApi/Controllers/OperationsController.cs
GetIntoTeachingApi/Services/IStore.cs
GetIntoTeachingApi/Services/Store.cs
GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs
GetIntoTeachingApiTests/Services/StoreTests.cs

Reverts DFE-Digital/get-into-teaching-api#397

Revert "Add endpoint to remove locations of unknown source"

---

.github/workflows/build.yml

Remove OWASP phase, not necessary in API

Remove OWASP

---

.github/workflows/build.yml

If we cannot find a merge then lets ignore the release creation
If we dont find release then we dont try to publish it

Release Creation Skipped

---

.github/workflows/build.yml

A process to replace common code with library steps to reduce change requirments

Replaced process with library

---

.github/workflows/build.yml
.github/workflows/publish_release.yml

When a release is published create a message in SLACK
When a PR is pushed create a DRAFT release at first, then when it is ready for production then convert to a published release

Common code for release

---

terraform/paas/monitoring.tf

Import the influxdb from development into the main pipeline

Development InfluxDB Imported

---

terraform/paas/production.env.tfvars

Import the Production Influx DB state into this terraform.
I have manually imported the production influxdb state into the main state, but to prevent it being overwritten the terraform needs to be merged into master ASAP
There is not change to the application

Merge Monitoring with Main Deployments

---

terraform/paas/variables.tf

Set all Variables to default in Terraform

set all variables to default

---

terraform/paas/monitoring.tf

Added missing variable

---

terraform/paas/production.env.tfvars

This activates the main pipelines monitoring deployment

Switched monitoring deployment on

---

.github/workflows/manual.yml

When deploying to production or other manual deployments, run the fix network policies script

Automatic Run Fix Network Policies

---

.github/workflows/build.yml

When deploying to Development run the Fix Network Policies after the run

Automatically run Fix network Policies

---

.github/workflows/build.yml

Use Common function CopyPRtoRelease to copy PR text to release

Use CopyPRtoRelease

---

.github/workflows/build.yml

Deploy call needs curly wurly brackets

Fix bug that only appears in Deploy

---

README.md

Add instructions for setting up a new service that integrates with the API.

Add API client details to README

---

terraform/paas/application.tf
terraform/paas/dev.env.tfvars
terraform/paas/production.env.tfvars
terraform/paas/sandbox.env.tfvars
terraform/paas/services.tf
terraform/paas/test.env.tfvars
terraform/paas/variables.tf

https://trello.com/c/EL5WMiqD/1129-rationalise-the-2-postgres-dbs-into-one
Migration plan to a single database, we are going to create a third database, but not use it. This will then be used as we move along.

Rationalise DB - Create Database

---

.github/workflows/deploy.yml

Validate the azure keys before usage, to prevent badly formed keys from causing issues further down the pipeline.
This process does not effect the API, it is a step that prevents deployment if the key was invalid. The deployment probably would have failed anyway due to the invalid key, but under certain circumstances the error with the key details could get logged.
https://github.com/DFE-Digital/get-into-teaching-api/runs/2021154429?check_suite_focus=true

Validate Azure Keys

---

.gitignore
Makefile

To add a method that will assist Developers to maintain the azure secrets.
###
**Secrets**:
This makefile gives the user the ability to safely display and edit azure secrets which are used by this project.
**Commands**:
edit-app-secrets  - Edit Application specific Secrets.
print-app-secrets - Display Application specific Secrets.
edit-monitoring-secrets  - Edit Monitoring specific Secrets.
print-monitoring-secrets - Display Monitoring specific Secrets.
**Parameters**:
All commands take the parameter development|review|test|production
**Examples**:
To edit the Application secrets for Development
make  development edit-app-secrets
To print the Monitoring secrets for Production
make  production print-monitoring-secrets

Added Makefile which will help with secrets

---

monitoring/grafana/dashboards/logit_logs.json
monitoring/grafana/dashboards/resources.json

Added new dash board that allows simple query of the logs
Added logs to resource dashboard so we can see logs verse metrics

Logit logs

---

monitoring/grafana/dashboards/get_into_teaching_api_event_search.json

I mistyped this in the original PR so no results are being pulled through into the dashboard.

Correct in-person event search metric name

---

Makefile
terraform/paas/data.tf
terraform/paas/services.tf
terraform/paas/variables.tf

[Trello](https://trello.com/c/h17wiyk6/1439-retrieve-logging-endpoint-from-secrets)
The logging endpoint has been missed from the deployment process because the secret was not maintained.
Add the secret to the API-KEYS secrets file in azure and populate the Logging service with it, during terraform deploy.
THis does not impact the application

Retrieve Logging Endpoint From Secrets

---

terraform/paas/monitoring.tf
terraform/paas/production.env.tfvars

The Grafana ELK credentials were not being set correctly. 
This is not causing a problem with the application, but just means a dashboard is failing to display

Dropped Grafana ELK credentials

---

GetIntoTeachingApi/Models/Validators/TeachingEventValidator.cs
GetIntoTeachingApiTests/Models/Validators/TeachingEventValidatorTests.cs

`summary` and `description` are optional in the CRM, so there is potential for issues if they are required here.

Remove validation for fields

---

GetIntoTeachingApi/Models/TeachingEventSearchRequest.cs
GetIntoTeachingApi/Services/Store.cs
GetIntoTeachingApiTests/Models/TeachingEventSearchRequestTests.cs
GetIntoTeachingApiTests/Services/StoreTests.cs

Add status filter to teaching event search, default to event status open.

Add status filter to teaching event search

---

terraform/paas/.gitignore
terraform/paas/provider.tf

The version of terraform is now version 14.9 it is time to switch to this version, as we also want to make changes in underlying modules
No impact on the application

Upgrade Terraform

---

monitoring/prometheus/alert.rules

[Trello](https://trello.com/c/gNipz5RF/1496-production-application-disk-usage-is-close-to-75-this-is-not-an-issue-but-would-like-to-ensure-we-have-an-alert-and-maybe-increa) 
Adding Disk usage > 80 and memory usage > 80
Adding some infrastructure alerts that link to [Confluence](https://dfedigital.atlassian.net/wiki/spaces/GGIT/pages/2727739405/Infrastructure+Alerts)

Added Infrastructure Alerts

---

monitoring/prometheus/alert.rules

Infrastructure Bug Fix

---

Dockerfile
monitoring/grafana/dashboards/http_errors.json

A dashboard to help display logged HTTP Errors and events.

Add HTTP Errors Dashboard

---

.github/workflows/deploy.yml

Remove plan stage from terraform as it can expose the  secrets.

Remove PLAN

---

GetIntoTeachingApi/Properties/launchSettings.json
GetIntoTeachingApi/Utils/Env.cs
GetIntoTeachingApiTests/Helpers/DatabaseTests.cs
GetIntoTeachingApiTests/Utils/EnvTests.cs

I mistyped this as `APPLICATION_SERVICES` when its actually `VCAP_APPLICATION`.

Correct VCAP_APPLICATION env var name

---

GetIntoTeachingApi/Controllers/CandidatesController.cs
GetIntoTeachingApiTests/Controllers/CandidatesControllerTests.cs

If the CRM is responding it should not be possible for a duplicate Candidate to be created in the system (such that the email address, first name and last name match an existing candidate).
We need to improve the logging around the scenarios when the CRM is not responding, which should either be when the integration is paused (i.e. they are updating the CRM) or an unexpected exception occurs (the request times out/the CRM is down/etc).
Add improved logging around matchback/access token generation.

Improve logging around potential duplicate Candidates

---

terraform/paas/dev.env.tfvars

Switch off logging to logit.io in development

Switch off logging to logit.io is development

---

.github/workflows/pull_request.yml
.github/workflows/sonarcloud.yml

Only send messages to SLACK when a failure happens on the MASTER branch

Only notify slack on master branch changes

---

terraform/paas/monitoring.tf

Master branch now contains our changes, so we can now use it.

Use master branch of Prometheus

---

.github/common_environment.yml
.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/pull_request.yml
.github/workflows/sonarcloud.yml
terraform/paas/application.tf
terraform/paas/data.tf

Dockerhub repository is now restrictive so moving to GHCR

Moving to GHCR from Docker hub

---

monitoring/grafana/dashboards/deployments.yml

A dashboard that uses Logit.io to show the Development velocity.
We intend on improving this dashboard.

Adding Deployments Dashboard

---

GetIntoTeachingApi/Models/Validators/TeacherTrainingAdviserSignUpValidator.cs
GetIntoTeachingApiTests/Models/Validators/TeacherTrainingAdviserSignUpValidatorTests.cs

We are re-enabling this feature in the TTA service.

Allow overseas candidates to schedule a callback

---

GetIntoTeachingApi/Services/Store.cs
GetIntoTeachingApiTests/Services/StoreTests.cs

If a teaching event is assigned a postcode that passes validation but cannot be looked up successfully from either the local database of postcode geolocations or via the Google Geocoding API then we can end up re-querying the postcode multiple times each sync. This can lead to very noisy alerts going off as we have a low-tolerance for Google Geocoding API failures (a single failure is notified).
Instead, we should cache the postcodes that fail lookup so that we don't continually receive alerts about them and we can then avoid calling the Google Geocoding API for a known bad postcode.

In-memory cache postcodes that can't be geocoded

---

terraform/paas/provider.tf

Update Cloud Foundry Provider Version

Update Cloud Foundry Provider Version

---

docs/runbooks/client-approaching-rate-limit.md
docs/runbooks/client-approaching-rate-limit_create-access-token.md
docs/runbooks/failed-jobs.md
docs/runbooks/google-api-errors.md
docs/runbooks/high-cpu.md
docs/runbooks/high-database-connections.md
docs/runbooks/high-google-api-calls.md
docs/runbooks/high-memory.md
docs/runbooks/too-many-requests.md
monitoring/prometheus/tests.yml

Initial draft of run books added

Run Books Added

---

terraform/paas/monitoring.tf
terraform/paas/provider.tf

If the secret is not in the map, then  secret["KEY"] will fail this can be resolved by using lookup( secret , "KEY" , default )

Use lookup() to extract secrets

---

terraform/paas/monitoring.tf

Added an exporter for Postgres and scrapes for prometheus. Then also added a Dashboard that displays it.

Added Postgres Database Monitoring

---

GetIntoTeachingApi/Models/ClassroomExperienceNote.cs
GetIntoTeachingApi/Models/Validators/ClassroomExperienceNoteValidator.cs
GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs
GetIntoTeachingApiTests/Models/CandidateTests.cs
GetIntoTeachingApiTests/Models/ClassroomExperienceNoteTests.cs
GetIntoTeachingApiTests/Models/Validators/ClassroomExperienceNoteValidatorTests.cs

Initially I thought the SchoolUrn was a string, but it is actually an integer exactly 6 digits in length.

Change SchoolUrn to be 6 digit int

---

GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs
GetIntoTeachingApiTests/Models/TeacherTrainingAdviserSignUpTests.cs

We are changing the front-end to include the country dial-in code in international phone numbers.
If a candidate enters an international number we want to:
- Remove any non-digit character
- Prefix the number with `00`
- If the number has the UK dial-in code, swap it for a `0`
Telephone numbers for UK-based candidates should remain unchanged.
Due to the format change we can no longer easily use the telephone number itself to determine the destination; instead, we will assume if the candidate chooses a non-UK country then the telephone number is international.

Format international phone numbers

---

GetIntoTeachingApi/Adapters/CdsServiceClientWrapper.cs
GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs
GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs
GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs
GetIntoTeachingApi/Models/CandidateQualification.cs
GetIntoTeachingApi/Models/PickListItem.cs
GetIntoTeachingApi/Services/CandidateUpserter.cs
GetIntoTeachingApiTests/Models/CandidatePastTeachingPositionTests.cs
GetIntoTeachingApiTests/Models/CandidateQualificationTests.cs
GetIntoTeachingApiTests/Models/CandidateTests.cs
GetIntoTeachingApiTests/Models/PickListItemTests.cs
GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs
GetIntoTeachingApiTests/Services/CrmServiceTests.cs

Reverts DFE-Digital/get-into-teaching-api#652
New error discovered on one of the TTA sign up flows:
>Microsoft.Xrm.Sdk.SaveChangesException: An error occured while processing this request.
---> System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'key'))

Revert "Update CdsServiceClient (take 2)"

---

GetIntoTeachingApi/Adapters/CdsServiceClientWrapper.cs
GetIntoTeachingApi/Adapters/IOrganizationServiceAdapter.cs
GetIntoTeachingApi/Adapters/OrganizationServiceAdapter.cs
GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApi/Models/CandidatePastTeachingPosition.cs
GetIntoTeachingApi/Models/CandidateQualification.cs
GetIntoTeachingApi/Models/PickListItem.cs
GetIntoTeachingApi/Program.cs
GetIntoTeachingApi/Services/CandidateUpserter.cs
GetIntoTeachingApiTests/Models/CandidatePastTeachingPositionTests.cs
GetIntoTeachingApiTests/Models/CandidateQualificationTests.cs
GetIntoTeachingApiTests/Models/CandidateTests.cs
GetIntoTeachingApiTests/Models/PickListItemTests.cs
GetIntoTeachingApiTests/Services/CandidateUpserterTests.cs
GetIntoTeachingApiTests/Services/CrmServiceTests.cs

Reverts DFE-Digital/get-into-teaching-api#654
We received an error related to deep inserting through Sentry; I need to take another look as I thought I updated all of the instances this could happen 😞

Revert "Update CdsServiceClient (take 3)"

---

monitoring/prometheus/scrapes.yml.tmpl
terraform/paas/dev.env.tfvars
terraform/paas/monitoring.tf
terraform/paas/production.env.tfvars

DNS Scrapes have been modified slightly and moved to the common monitoring solution.
This allows for common code.

DNS Scrapes

---

GetIntoTeachingApi/Models/TeachingEvent.cs
GetIntoTeachingApi/Services/CrmService.cs
GetIntoTeachingApiTests/Models/TeachingEventTests.cs
GetIntoTeachingApiTests/Services/CrmServiceTests.cs

We were seeing an error when posting a new event. Add some null checks and tests to fix.

Fix new event error

---

monitoring/grafana/dashboards/get_into_teaching_api.json

Add a panel that tracks total SE sign ups.

Add panel for SE sign ups

---

GetIntoTeachingApi/Services/CrmService.cs
GetIntoTeachingApiTests/Services/CrmServiceTests.cs

The candidate match back queries currently use LINQ, which is easier to write/understand/test than an QueryExpression, however the drawback is you can't easily scope the fields coming back from Dynamics to just those that you want (it is possible, but you need to pluck the fields you want in the `Select` clause, which doesn't fit well with how we instantiate our models from Dynamics entities).
Update match back queries to use `QueryExpression`, which should be faster albeit less readable/testable.

Optimize candidate match back queries

---

GetIntoTeachingApi/Models/Candidate.cs

This entity attribute isn't available in production yet so disabling for that environment.

Ignore FindApplyId in production

---

.github/dependabot.yml

Add more  Nuget, Terraform and Docker Dependabot checks

Implement more Dependabot

---

GetIntoTeachingApi/Models/Crm/Candidate.cs
GetIntoTeachingApi/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUp.cs
GetIntoTeachingApiTests/Models/Crm/CandidateTests.cs
GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs

Reverts DFE-Digital/get-into-teaching-api#728
This appears to have broken the matchback process; though I have no idea how -- reverting for now until I figure it out.

Revert "Handle candidates re-signing up with a closed adviser status"

---

GetIntoTeachingApiTests/Contracts/TeacherTrainingAdviserTests.cs

Bit of a shot in the dark here, but the tests fail fairly routinely on CI although I can't replicate it locally. As the contract is based on the jobs in progress I'm betting that another test leaves left over state in the job queue that is picked up when the first contract test runs.
To avoid this, we're going to flush the state before each test run (clear the job queue, wait for any in-progress jobs to finish and reset the `TrackedEntities`).

Fix flakey contract tests

---

GetIntoTeachingApiTests/Contracts/TeacherTrainingAdviserTests.cs

The contract tests queue multiple jobs, which queue other jobs themselves. I think this process may be asynchronously happening in Hangfire and it results in the queue being 'cleared' for short periods between one job finishing and the next being enqueued (as we wait for jobs to clear before finalising a contract it can result in a gap in the contract/missing a tracked entity).
To avoid flakiness we now perform a repeated check on the job queue when its in the 'cleared' state (no in-progress/queued jobs) to ensure it stays in that state for a short duration, which will hopefully resolve the flakiness in the contract tests.
If this isn't the source of the flakiness, my only other thought is that it could be to do with the app startup queueing a number of 'recurring' jobs that pre-populate …

Improve wait logic around contract test job queue

---

README.md

The feature switching implementation was added recently but I neglected to updated the README.

Update with feature switch details

---

GetIntoTeachingApi/AppStart/ApplicationBuilderExtensions.cs
GetIntoTeachingApi/AppStart/ServiceCollectionExtensions.cs
GetIntoTeachingApi/AppStart/Startup.cs
GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj

Reverts DFE-Digital/get-into-teaching-api#778
We're seeing the CrmSync job failing on the dev environment so reverting to investigate.

Revert "Bulk update dependencies"

---

monitoring/alertmanager/alertmanager.yml
monitoring/grafana/dashboards/csp_violations.json
monitoring/prometheus/alert.rules
terraform/paas/variables.tf

Reverts DFE-Digital/get-into-teaching-api#800
Routes not working so alerts are coming through every few minutes

Revert "Add google csp table grafana"

---

GetIntoTeachingApi/Controllers/OperationsController.cs

I had copy/pasted a different action and forgot to change the response types.

Fix swagger documentation for backfill endpoint

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/fix-network-policy.yml
.github/workflows/manual.yml
.github/workflows/pull_request.yml
.github/workflows/restart_prometheus.yml
.github/workflows/sonarcloud.yml
.github/workflows/trello.yml
terraform/paas/data.tf
terraform/paas/monitoring.tf
terraform/paas/provider.tf

1. Lets get all our secrets into the right locations and remove the need for discrete secrets
2. Change Terraform to use the Yaml secrets
3. Change the Workflows to use the Yaml secrets
Why well because at first we didn't have a reliable GitHub action which could grab the secrets and not display them in the log files, now that has been solved we want to use secrets across projects in the same way.

DRY out Secrets

---

monitoring/grafana/dashboards/get_into_teaching_api.json

A few of the engagement panels had stopped working properly; this corrects the metrics.

Fix engagement panels

---

GetIntoTeachingApiTests/Services/PaginatorClientTests.cs
GetIntoTeachingApiTests/Utils/EnvTests.cs

I missed these from my earlier PR.

Minor linting fixes

---

GetIntoTeachingApi/AppStart/Startup.cs

[Trello-2777](https://trello.com/c/oYLSzOTp/2777-monkey-patch-api-client-models-to-support-snakecase-attributes-in-initializer?filter=member:rossoliver15)
We were using v2 previously as that was campatible with `swagger-codegen@2`, however as we are now using `openapi-generator` we can update to the latest Open API specification/format.

Output v3 Open API specification

---

GetIntoTeachingApi/Controllers/GetIntoTeaching/TeachingEventsController.cs
GetIntoTeachingApiTests/Controllers/GetIntoTeaching/TeachingEventsControllerTests.cs

[Trello-2834](https://trello.com/c/sGBJvHr7/2834-reinstate-api-event-search-endpoint-that-returns-events-in-one-list)
We currently have a search endpoint that returns events grouped by type. The new GiT website event page displays events in a single list (instead of in groups), so it makes sense to return a single list from the API.
Once the old search by type endpoint is removed we could look to move the `Take()` call into the `Store` for it to be more efficient, but as there's no performance issues on that endpoint it may be more hassle than its worth.

Add new event search endpoint (ungrouped)

---

GetIntoTeachingApi/Controllers/SchoolsExperience/CandidatesController.cs
GetIntoTeachingApiTests/Controllers/SchoolsExperience/CandidatesControllerTests.cs

This endpoint has been tested in the Dev environment, and the CRM have now pushed their schema change to Prod. We will be merging the School Experience changes to use the new endpoint soon.

Remove feature flag from endpoint to add a new CandidateSchoolExperience

---

.github/workflows/actions/deploy/action.yml
.github/workflows/build.yml
.github/workflows/fix-network-policy.yml
.github/workflows/manual.yml
.github/workflows/pull_request.yml
.github/workflows/restart_prometheus.yml
.github/workflows/sonarcloud.yml
.github/workflows/trello.yml

Use the reusable workflow action to call other actions.
Use the new secret action to retrieve secrets.

Improve workflows

---

terraform/paas/dev.env.tfvars
terraform/paas/production.env.tfvars

Add metric gather URLs to the Prometheus Config which will gather metrics from the listed applications.

Gather School Experience Metrics

---

.github/workflows/actions/deploy/action.yml
.github/workflows/build.yml
.github/workflows/check_alert_rules.yml
.github/workflows/manual.yml
.github/workflows/pull_request.yml
.github/workflows/sonarcloud.yml
GetIntoTeachingApi/Database/GetIntoTeachingDbContext.cs
GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApi/Program.cs
GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
GetIntoTeachingApiTests/Models/GetIntoTeaching/GetIntoTeachingCallbackTests.cs
GetIntoTeachingApiTests/Models/GetIntoTeaching/MailingListAddMemberTests.cs
GetIntoTeachingApiTests/Models/GetIntoTeaching/TeachingEventAddAttendeeTests.cs
GetIntoTeachingApiTests/Models/SchoolsExperience/SchoolsExperienceSignUpTests.cs
GetIntoTeachingApiTests/Models/TeacherTrainingAdviser/TeacherTrainingAdviserSignUpTests.cs

Reverts DFE-Digital/get-into-teaching-api#936
In testing the sign ups functioned correctly but the hangfire dashboard isn't behaving; I think this is due to the change in postgres provider; going to revert while I investigate.

Revert "Update various dependencies"

---

.github/workflows/build.yml
GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj

Closes #947 #940 #939 #938 #937 #946

Update various dependencies

---

Makefile

https://trello.com/c/AmqiZOuv
Remove secrets from rails encrypted secrets, centralise in Azure keyvault, provide a safe and convenient place to store secrets used for local development
Makefile target to edit local secrets
Try `make local print-app-secrets` and `make local edit-app-secrets`

[559] Local development keyvault

---

GetIntoTeachingApi/AppStart/Startup.cs

It worked locally but not in a hosted environment; I think we need to be more explicit with the file path.

Fix dotenv file path

---

.github/workflows/actions/deploy/action.yml
.github/workflows/build-no-cache.yml
.github/workflows/build.yml
.github/workflows/manual.yml
.github/workflows/pull_request.yml
.github/workflows/restart_prometheus.yml
.github/workflows/sonarcloud.yml
.github/workflows/trello.yml

https://trello.com/c/El2I9Bk3
Document secrets and remove obsolete ones

[528] Remove GITHUB_TOKEN when not necessary

---

README.md

Thanks to @deanwilson for pointing this out!

Fix the build badge at the top of the README

---

GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj
GetIntoTeachingApiTests/Jobs/ClaimCallbackBookingSlotJobTests.cs

- Microsoft.EntityFrameworkCore 6.0.6 - 6.0.7
- Microsoft.EntityFrameworkCore.Design 6.0.6 - 6.0.7
- Microsoft.EntityFrameworkCore.Tools 6.0.6 - 6.0.7
- Microsoft.VisualStudio.Web.CodeGeneration.Design 6.0.6 - 6.0.7
- Sentry.AspNetCore 3.19.0 - 3.20.0
- Serilog.AspNetCore 5.0.0 - 6.0.1
- Swashbuckle.AspNetCore 6.3.1 - 6.4.0
- Swashbuckle.AspNetCore.Annotations 6.3.1 - 6.4.0
- Microsoft.Extensions.Caching.StackExchangeRedis 6.0.6 - 6.0.7
- YamlDotNet 11.2.1 - 12.0.0
- Microsoft.AspNetCore.DataProtection.StackExchangeRedis 6.0.6 - 6.0.7
- Microsoft.EntityFrameworkCore.Relational 6.0.6 - 6.0.7
- Microsoft.PowerPlatform.Dataverse.Client 1.0.1 - 1.0.9
- Microsoft.AspNetCore.Mvc.Testing 6.0.6 - 6.0.7

Various dependency updates

---

terraform/paas/.terraform.lock.hcl
terraform/paas/provider.tf

https://trello.com/c/Or8Y4W6H
Ensure the azurerm provider version is pinned so that the same version is always used.
Pin and update azurerm provider version

Pin azurerm provider version

---

terraform/paas/production.env.tfvars

We want to scrape the production sidekiq workers.

Add Prometheus target for sidekiq production

---

GetIntoTeachingApi/Controllers/GetIntoTeaching/TeachingEventsController.cs
GetIntoTeachingApiTests/Controllers/GetIntoTeaching/TeachingEventsControllerTests.cs

The GiT website no longer calls the search events grouped by type endpoint (instead using the new search endpoint). It can be removed from the codebase (no other service uses it).

Remove unused event search endpoint

---

GetIntoTeachingApi/env.dev

Apply have updated their API so it should handle the traffic now.

Revert "Disable Apply API integration"

---

GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj

Reverts DFE-Digital/get-into-teaching-api#1164 - I'm not sure what's gone wrong yet but its throwing errors in staging; looks like one of the postgres updates has caused an issue, not sure why I didn't hit it locally though.

Revert "Various dependency updates"

---

GetIntoTeachingApi/Controllers/OperationsController.cs
GetIntoTeachingApi/Jobs/ApplyBackfillJob.cs
GetIntoTeachingApiTests/Controllers/OperationsControllerTests.cs
GetIntoTeachingApiTests/Jobs/ApplyBackfillJobTests.cs

[Trello-4321](https://trello.com/c/EOPl2q9u/4321-update-apply-backfill-to-accept-a-date)
We want to run a backfill from a specific date; currently we backfill to the beginning of time.

Update ApplyBackfillJob to accept a date

---

GetIntoTeachingApi/Jobs/ApplyBackfillJob.cs
GetIntoTeachingApi/Jobs/ApplyCandidateSyncJob.cs
GetIntoTeachingApi/Jobs/UpsertApplicationFormJob.cs
GetIntoTeachingApiTests/Contracts/ApplyCandidateApiTests.cs
GetIntoTeachingApiTests/Jobs/ApplyBackfillJobTests.cs
GetIntoTeachingApiTests/Jobs/ApplyCandidateSyncJobTests.cs
GetIntoTeachingApiTests/Jobs/UpsertApplicationFormJobTests.cs

Reverts DFE-Digital/get-into-teaching-api#1205

Revert "Clear down all apply jobs"

---

monitoring/grafana/dashboards/get_into_teaching_api.json

Add a panel to track adviser sign ups from the apply service.

Add apply adviser sign ups panel

---

monitoring/grafana/dashboards/get_into_teaching_api.json

We want to track adviser sign ups from the GiT website.

Add GiT adviser sign ups panel

---

terraform/aks/config/development_aks.tfvars.json
terraform/aks/databases.tf
terraform/aks/variables.tf

Deploy Redis
Add redis resource in aks using terraform-modules
```make development_aks terraform-apply```
See the already deployed resources (s189t01-gitapi-dv-rg)
NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

Deploy Redis

---

GetIntoTeachingApi/GetIntoTeachingApi.csproj
GetIntoTeachingApiTests/GetIntoTeachingApiTests.csproj

Bump xunit from 2.4.2 to 2.5.0
Bump Microsoft.EntityFrameworkCore.Tools from 7.0.7 to 7.0.9 
Bump Microsoft.AspNetCore.DataProtection.StackExchangeRedis from 7.0.5 to 7.0.9 
Bump Microsoft.EntityFrameworkCore from 7.0.7 to 7.0.9 
Bump Microsoft.VisualStudio.Web.CodeGeneration.Design from 7.0.6 to 7.0.8

Dependency update

---

Makefile
README.md

Updated Makefile to target new local Key Vault for local secrets

Migrate local secrets

---

Makefile

New product tag value is "Get Into Teaching Website"

Update product tag

---

.github/workflows/build-and-deploy.yml
Makefile
global_config/production_aks.sh
terraform/aks/config/production_aks.tfvars.json
terraform/aks/config/production_aks_Terrafile

Update Makefile, add tfvars and update workflow, config to include production config 
Deployed prod resources and application. 
Running on  [GITAPI PROD HEALTH CHECK](https://getintoteachingapi-production.teacherservices.cloud/api/operations/health_check)

 Replicate Production environment

---

terraform/aks/config/production_aks.tfvars.json
terraform/aks/provider.tf
terraform/aks/secrets.tf
terraform/aks/statuscake.tf
terraform/aks/variables.tf

Add StatusCake Monitoring

---

.github/workflows/build-and-deploy.yml

update cmdlet to minimise code

Update Retrieve Slack webhook from KV Steps

---

Makefile
terraform/aks/config/production_aks.tfvars.json
terraform/aks/databases.tf
terraform/aks/variables.tf

We have observed timeouts in the application log and some users are impacted.
This upgrades production to Premium and high availibilty across availibity zones.
Run terraform plan

[670] Upgrade redis server

---

.github/workflows/manual.yml

Fixed pipeline error by Updating  the fetch secret logic for SLACK-WEBHOOK
https://trello.com/c/OLMlHbIP/929-git-api-slackwebhook-missing-error

Updated the fetch secret logic for SLACK-WEBHOOK

---

.github/workflows/build-and-deploy.yml
.github/workflows/build-no-cache.yml
.github/workflows/manual.yml
.github/workflows/pull_request.yml
.github/workflows/sonarcloud.yml
.github/workflows/trello.yml

This reverts commit 5e3ee9bb3943b084e25665ce5759288c9cb6ca70.

Revert "Bump azure/CLI from 1 to 2 (#1378)"

---

terraform/aks/statuscake.tf

https://trello.com/c/Z6eliKhq/1654-review-statuscake-contact-groups
added infra team contact group
added infra team contact group
make production terraform-plan

Added infra team group to statuscake

---

GetIntoTeachingApi/appsettings.json

Reduce logging noise in API log files

Limit entity framework db commands to warnings and errors

---

terraform/aks/config/production_aks.tfvars.json

Ship web and worker application logs to Logit.io. Enable for prod environment.
make production_aks terraform-plan

Onboard prod env to logit

---

.github/workflows/actions/deploy_v2/action.yml

The deploy workflow is using an old version of hashicorp/setup-terraform.
Update to the latest version.

Update github actions versions

---

GetIntoTeachingApi/Controllers/PickListItemsController.cs
GetIntoTeachingApi/Models/Crm/Candidate.cs
GetIntoTeachingApi/Models/GetIntoTeaching/MailingListAddMember.cs
GetIntoTeachingApi/Services/Store.cs
GetIntoTeachingApiTests/Controllers/GetIntoTeaching/MailingListControllerTests.cs
GetIntoTeachingApiTests/Controllers/PickListItemsControllerTests.cs
GetIntoTeachingApiTests/Models/GetIntoTeaching/MailingListAddMemberTests.cs

[Temporary revert of dfe_situation](https://trello.com/c/7UqINB6u/7648-temporary-revert-dfesituation-field)
This reverts commit 809b53a77922527562326918d9c681a33cd39ed5.

Revert Added candidate situation to picklist

---

GetIntoTeachingApi/AppStart/ServiceCollectionExtensions.cs

See Trello Ticket: [Fixes to address data sync issues](https://trello.com/c/75XJyerJ/7647-implement-agreed-fixes-to-address-apply-data-synch-issues)

Implement agreed fixes to address Apply data synch issues

---

GetIntoTeachingApi/AppStart/ServiceCollectionExtensions.cs

Testing hangfire errors on the dev server
This reverts commit 0bc5a9197434f29e8e1a4e6cf59253beb8c71c91.

Temporary revert concurrent hangfire background processes from 1 back to 20

---

GetIntoTeachingApi/GetIntoTeachingApi.csproj

Removed some third part NuGet package dependencies that are not being used.

Removal of unused dependencies in API

---

.github/workflows/build-and-deploy.yml

• Implement sequential deployment strategy to replace parallel deployment
- Replace separate development and test jobs with matrix-based deploy job
- Add max-parallel: 1 to ensure sequential deployment (development → test)
- Maintain proper environment dependencies and concurrency controls
• Add automatic production deployment on master branch pushes
- Create new deploy_production job that runs after dev/test deployments
- Enable full continuous deployment pipeline: build → dev → test → production
- Add proper dependency chain with needs: [build, deploy]
• Fix GitHub Actions linter errors
- Correct SHA parameter name from 'sha' to 'SHA' in GenerateReleaseFromSHA action
- Ensure all required action inputs are properly specified
• Preserve existing functionality while improving deployment …

Align deployment workflow with CD pattern

---

.github/workflows/build-and-deploy.yml

Raising a fix for failing to get the release tag

Modifying build and depoy workflow

---

GetIntoTeachingApi/Models/Crm/AdditionalEventsContactChannel.cs
GetIntoTeachingApi/Models/Crm/ContactChannelCreation.cs
GetIntoTeachingApiTests/Models/GetIntoTeaching/MailingListAddMemberTests.cs

[Add ProspectiveEvents service type CCC record ](https://trello.com/c/dr6baQTa/8284-add-prospectiveevents-contact-creation-channel-service-to-mailing-list)

Add ProspectiveEvents CCC service and map additional CCC to it

---

GetIntoTeachingApi/Models/TeacherTrainingAdviser/Validators/TeacherTrainingAdviserSignUpValidator.cs

remove some validation to take into account path for non uk degree

dropping validation on path
